/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.canal.etico.liferay.portlet.canal.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.LocalizedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Comp service. Represents a row in the &quot;canal_etico_Comp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.canal.etico.liferay.portlet.canal.manager.model.impl.CompModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.canal.etico.liferay.portlet.canal.manager.model.impl.CompImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Comp
 * @generated
 */
@ProviderType
public interface CompModel extends BaseModel<Comp>, LocalizedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a comp model instance should use the {@link Comp} interface instead.
	 */

	/**
	 * Returns the primary key of this comp.
	 *
	 * @return the primary key of this comp
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this comp.
	 *
	 * @param primaryKey the primary key of this comp
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the comp ID of this comp.
	 *
	 * @return the comp ID of this comp
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this comp.
	 *
	 * @param compId the comp ID of this comp
	 */
	public void setCompId(long compId);

	/**
	 * Returns the suite comp ID of this comp.
	 *
	 * @return the suite comp ID of this comp
	 */
	public long getSuiteCompId();

	/**
	 * Sets the suite comp ID of this comp.
	 *
	 * @param suiteCompId the suite comp ID of this comp
	 */
	public void setSuiteCompId(long suiteCompId);

	/**
	 * Returns the cif of this comp.
	 *
	 * @return the cif of this comp
	 */
	@AutoEscape
	public String getCif();

	/**
	 * Sets the cif of this comp.
	 *
	 * @param cif the cif of this comp
	 */
	public void setCif(String cif);

	/**
	 * Returns the name of this comp.
	 *
	 * @return the name of this comp
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this comp.
	 *
	 * @param name the name of this comp
	 */
	public void setName(String name);

	/**
	 * Returns the description of this comp.
	 *
	 * @return the description of this comp
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this comp in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this comp
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this comp in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this comp. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this comp in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this comp
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this comp in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this comp
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this comp.
	 *
	 * @return the locales and localized descriptions of this comp
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this comp.
	 *
	 * @param description the description of this comp
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this comp in the language.
	 *
	 * @param description the localized description of this comp
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this comp in the language, and sets the default locale.
	 *
	 * @param description the localized description of this comp
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(
		String description, Locale locale, Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this comp from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this comp
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this comp from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this comp
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale);

	/**
	 * Returns the observations of this comp.
	 *
	 * @return the observations of this comp
	 */
	public String getObservations();

	/**
	 * Returns the localized observations of this comp in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized observations of this comp
	 */
	@AutoEscape
	public String getObservations(Locale locale);

	/**
	 * Returns the localized observations of this comp in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized observations of this comp. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getObservations(Locale locale, boolean useDefault);

	/**
	 * Returns the localized observations of this comp in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized observations of this comp
	 */
	@AutoEscape
	public String getObservations(String languageId);

	/**
	 * Returns the localized observations of this comp in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized observations of this comp
	 */
	@AutoEscape
	public String getObservations(String languageId, boolean useDefault);

	@AutoEscape
	public String getObservationsCurrentLanguageId();

	@AutoEscape
	public String getObservationsCurrentValue();

	/**
	 * Returns a map of the locales and localized observationses of this comp.
	 *
	 * @return the locales and localized observationses of this comp
	 */
	public Map<Locale, String> getObservationsMap();

	/**
	 * Sets the observations of this comp.
	 *
	 * @param observations the observations of this comp
	 */
	public void setObservations(String observations);

	/**
	 * Sets the localized observations of this comp in the language.
	 *
	 * @param observations the localized observations of this comp
	 * @param locale the locale of the language
	 */
	public void setObservations(String observations, Locale locale);

	/**
	 * Sets the localized observations of this comp in the language, and sets the default locale.
	 *
	 * @param observations the localized observations of this comp
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setObservations(
		String observations, Locale locale, Locale defaultLocale);

	public void setObservationsCurrentLanguageId(String languageId);

	/**
	 * Sets the localized observationses of this comp from the map of locales and localized observationses.
	 *
	 * @param observationsMap the locales and localized observationses of this comp
	 */
	public void setObservationsMap(Map<Locale, String> observationsMap);

	/**
	 * Sets the localized observationses of this comp from the map of locales and localized observationses, and sets the default locale.
	 *
	 * @param observationsMap the locales and localized observationses of this comp
	 * @param defaultLocale the default locale
	 */
	public void setObservationsMap(
		Map<Locale, String> observationsMap, Locale defaultLocale);

	/**
	 * Returns the agreement of this comp.
	 *
	 * @return the agreement of this comp
	 */
	public String getAgreement();

	/**
	 * Returns the localized agreement of this comp in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized agreement of this comp
	 */
	@AutoEscape
	public String getAgreement(Locale locale);

	/**
	 * Returns the localized agreement of this comp in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized agreement of this comp. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getAgreement(Locale locale, boolean useDefault);

	/**
	 * Returns the localized agreement of this comp in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized agreement of this comp
	 */
	@AutoEscape
	public String getAgreement(String languageId);

	/**
	 * Returns the localized agreement of this comp in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized agreement of this comp
	 */
	@AutoEscape
	public String getAgreement(String languageId, boolean useDefault);

	@AutoEscape
	public String getAgreementCurrentLanguageId();

	@AutoEscape
	public String getAgreementCurrentValue();

	/**
	 * Returns a map of the locales and localized agreements of this comp.
	 *
	 * @return the locales and localized agreements of this comp
	 */
	public Map<Locale, String> getAgreementMap();

	/**
	 * Sets the agreement of this comp.
	 *
	 * @param agreement the agreement of this comp
	 */
	public void setAgreement(String agreement);

	/**
	 * Sets the localized agreement of this comp in the language.
	 *
	 * @param agreement the localized agreement of this comp
	 * @param locale the locale of the language
	 */
	public void setAgreement(String agreement, Locale locale);

	/**
	 * Sets the localized agreement of this comp in the language, and sets the default locale.
	 *
	 * @param agreement the localized agreement of this comp
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setAgreement(
		String agreement, Locale locale, Locale defaultLocale);

	public void setAgreementCurrentLanguageId(String languageId);

	/**
	 * Sets the localized agreements of this comp from the map of locales and localized agreements.
	 *
	 * @param agreementMap the locales and localized agreements of this comp
	 */
	public void setAgreementMap(Map<Locale, String> agreementMap);

	/**
	 * Sets the localized agreements of this comp from the map of locales and localized agreements, and sets the default locale.
	 *
	 * @param agreementMap the locales and localized agreements of this comp
	 * @param defaultLocale the default locale
	 */
	public void setAgreementMap(
		Map<Locale, String> agreementMap, Locale defaultLocale);

	/**
	 * Returns the friendly url of this comp.
	 *
	 * @return the friendly url of this comp
	 */
	@AutoEscape
	public String getFriendlyURL();

	/**
	 * Sets the friendly url of this comp.
	 *
	 * @param friendlyURL the friendly url of this comp
	 */
	public void setFriendlyURL(String friendlyURL);

	/**
	 * Returns the logo of this comp.
	 *
	 * @return the logo of this comp
	 */
	public long getLogo();

	/**
	 * Sets the logo of this comp.
	 *
	 * @param logo the logo of this comp
	 */
	public void setLogo(long logo);

	/**
	 * Returns the active of this comp.
	 *
	 * @return the active of this comp
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this comp is active.
	 *
	 * @return <code>true</code> if this comp is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this comp is active.
	 *
	 * @param active the active of this comp
	 */
	public void setActive(boolean active);

	/**
	 * Returns the start date of this comp.
	 *
	 * @return the start date of this comp
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this comp.
	 *
	 * @param startDate the start date of this comp
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the delete date of this comp.
	 *
	 * @return the delete date of this comp
	 */
	public Date getDeleteDate();

	/**
	 * Sets the delete date of this comp.
	 *
	 * @param deleteDate the delete date of this comp
	 */
	public void setDeleteDate(Date deleteDate);

	/**
	 * Returns the create date of this comp.
	 *
	 * @return the create date of this comp
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this comp.
	 *
	 * @param createDate the create date of this comp
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this comp.
	 *
	 * @return the modified date of this comp
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this comp.
	 *
	 * @param modifiedDate the modified date of this comp
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

}