/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.canal.etico.liferay.portlet.canal.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Comunicacion service. Represents a row in the &quot;canal_etico_Comunicacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.canal.etico.liferay.portlet.canal.manager.model.impl.ComunicacionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.canal.etico.liferay.portlet.canal.manager.model.impl.ComunicacionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Comunicacion
 * @generated
 */
@ProviderType
public interface ComunicacionModel extends BaseModel<Comunicacion> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a comunicacion model instance should use the {@link Comunicacion} interface instead.
	 */

	/**
	 * Returns the primary key of this comunicacion.
	 *
	 * @return the primary key of this comunicacion
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this comunicacion.
	 *
	 * @param primaryKey the primary key of this comunicacion
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the comunicacion ID of this comunicacion.
	 *
	 * @return the comunicacion ID of this comunicacion
	 */
	public long getComunicacionId();

	/**
	 * Sets the comunicacion ID of this comunicacion.
	 *
	 * @param comunicacionId the comunicacion ID of this comunicacion
	 */
	public void setComunicacionId(long comunicacionId);

	/**
	 * Returns the denuncia ID of this comunicacion.
	 *
	 * @return the denuncia ID of this comunicacion
	 */
	public long getDenunciaId();

	/**
	 * Sets the denuncia ID of this comunicacion.
	 *
	 * @param denunciaId the denuncia ID of this comunicacion
	 */
	public void setDenunciaId(long denunciaId);

	/**
	 * Returns the user ID of this comunicacion.
	 *
	 * @return the user ID of this comunicacion
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this comunicacion.
	 *
	 * @param userId the user ID of this comunicacion
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this comunicacion.
	 *
	 * @return the user uuid of this comunicacion
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this comunicacion.
	 *
	 * @param userUuid the user uuid of this comunicacion
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the descripcion of this comunicacion.
	 *
	 * @return the descripcion of this comunicacion
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this comunicacion.
	 *
	 * @param descripcion the descripcion of this comunicacion
	 */
	public void setDescripcion(String descripcion);

	/**
	 * Returns the adjunto of this comunicacion.
	 *
	 * @return the adjunto of this comunicacion
	 */
	public long getAdjunto();

	/**
	 * Sets the adjunto of this comunicacion.
	 *
	 * @param adjunto the adjunto of this comunicacion
	 */
	public void setAdjunto(long adjunto);

	/**
	 * Returns the observaciones of this comunicacion.
	 *
	 * @return the observaciones of this comunicacion
	 */
	@AutoEscape
	public String getObservaciones();

	/**
	 * Sets the observaciones of this comunicacion.
	 *
	 * @param observaciones the observaciones of this comunicacion
	 */
	public void setObservaciones(String observaciones);

	/**
	 * Returns the create date of this comunicacion.
	 *
	 * @return the create date of this comunicacion
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this comunicacion.
	 *
	 * @param createDate the create date of this comunicacion
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this comunicacion.
	 *
	 * @return the modified date of this comunicacion
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this comunicacion.
	 *
	 * @param modifiedDate the modified date of this comunicacion
	 */
	public void setModifiedDate(Date modifiedDate);

}