/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.canal.etico.liferay.portlet.canal.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DenunciaAccion service. Represents a row in the &quot;canal_etico_DenunciaAccion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.canal.etico.liferay.portlet.canal.manager.model.impl.DenunciaAccionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.canal.etico.liferay.portlet.canal.manager.model.impl.DenunciaAccionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DenunciaAccion
 * @generated
 */
@ProviderType
public interface DenunciaAccionModel extends BaseModel<DenunciaAccion> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a denuncia accion model instance should use the {@link DenunciaAccion} interface instead.
	 */

	/**
	 * Returns the primary key of this denuncia accion.
	 *
	 * @return the primary key of this denuncia accion
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this denuncia accion.
	 *
	 * @param primaryKey the primary key of this denuncia accion
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the denuncia accion ID of this denuncia accion.
	 *
	 * @return the denuncia accion ID of this denuncia accion
	 */
	public long getDenunciaAccionId();

	/**
	 * Sets the denuncia accion ID of this denuncia accion.
	 *
	 * @param denunciaAccionId the denuncia accion ID of this denuncia accion
	 */
	public void setDenunciaAccionId(long denunciaAccionId);

	/**
	 * Returns the denuncia ID of this denuncia accion.
	 *
	 * @return the denuncia ID of this denuncia accion
	 */
	public long getDenunciaId();

	/**
	 * Sets the denuncia ID of this denuncia accion.
	 *
	 * @param denunciaId the denuncia ID of this denuncia accion
	 */
	public void setDenunciaId(long denunciaId);

	/**
	 * Returns the accion ID of this denuncia accion.
	 *
	 * @return the accion ID of this denuncia accion
	 */
	public long getAccionId();

	/**
	 * Sets the accion ID of this denuncia accion.
	 *
	 * @param accionId the accion ID of this denuncia accion
	 */
	public void setAccionId(long accionId);

	/**
	 * Returns the user ID of this denuncia accion.
	 *
	 * @return the user ID of this denuncia accion
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this denuncia accion.
	 *
	 * @param userId the user ID of this denuncia accion
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this denuncia accion.
	 *
	 * @return the user uuid of this denuncia accion
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this denuncia accion.
	 *
	 * @param userUuid the user uuid of this denuncia accion
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the observaciones of this denuncia accion.
	 *
	 * @return the observaciones of this denuncia accion
	 */
	@AutoEscape
	public String getObservaciones();

	/**
	 * Sets the observaciones of this denuncia accion.
	 *
	 * @param observaciones the observaciones of this denuncia accion
	 */
	public void setObservaciones(String observaciones);

	/**
	 * Returns the create date of this denuncia accion.
	 *
	 * @return the create date of this denuncia accion
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this denuncia accion.
	 *
	 * @param createDate the create date of this denuncia accion
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this denuncia accion.
	 *
	 * @return the modified date of this denuncia accion
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this denuncia accion.
	 *
	 * @param modifiedDate the modified date of this denuncia accion
	 */
	public void setModifiedDate(Date modifiedDate);

}