/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.canal.etico.liferay.portlet.canal.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Denuncia service. Represents a row in the &quot;canal_etico_Denuncia&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.canal.etico.liferay.portlet.canal.manager.model.impl.DenunciaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.canal.etico.liferay.portlet.canal.manager.model.impl.DenunciaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Denuncia
 * @generated
 */
@ProviderType
public interface DenunciaModel extends BaseModel<Denuncia> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a denuncia model instance should use the {@link Denuncia} interface instead.
	 */

	/**
	 * Returns the primary key of this denuncia.
	 *
	 * @return the primary key of this denuncia
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this denuncia.
	 *
	 * @param primaryKey the primary key of this denuncia
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the denuncia ID of this denuncia.
	 *
	 * @return the denuncia ID of this denuncia
	 */
	public long getDenunciaId();

	/**
	 * Sets the denuncia ID of this denuncia.
	 *
	 * @param denunciaId the denuncia ID of this denuncia
	 */
	public void setDenunciaId(long denunciaId);

	/**
	 * Returns the codigo of this denuncia.
	 *
	 * @return the codigo of this denuncia
	 */
	@AutoEscape
	public String getCodigo();

	/**
	 * Sets the codigo of this denuncia.
	 *
	 * @param codigo the codigo of this denuncia
	 */
	public void setCodigo(String codigo);

	/**
	 * Returns the cif of this denuncia.
	 *
	 * @return the cif of this denuncia
	 */
	@AutoEscape
	public String getCif();

	/**
	 * Sets the cif of this denuncia.
	 *
	 * @param cif the cif of this denuncia
	 */
	public void setCif(String cif);

	/**
	 * Returns the comp ID of this denuncia.
	 *
	 * @return the comp ID of this denuncia
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this denuncia.
	 *
	 * @param compId the comp ID of this denuncia
	 */
	public void setCompId(long compId);

	/**
	 * Returns the vinculacion of this denuncia.
	 *
	 * @return the vinculacion of this denuncia
	 */
	@AutoEscape
	public String getVinculacion();

	/**
	 * Sets the vinculacion of this denuncia.
	 *
	 * @param vinculacion the vinculacion of this denuncia
	 */
	public void setVinculacion(String vinculacion);

	/**
	 * Returns the email of this denuncia.
	 *
	 * @return the email of this denuncia
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this denuncia.
	 *
	 * @param email the email of this denuncia
	 */
	public void setEmail(String email);

	/**
	 * Returns the nombre of this denuncia.
	 *
	 * @return the nombre of this denuncia
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this denuncia.
	 *
	 * @param nombre the nombre of this denuncia
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the apellidos of this denuncia.
	 *
	 * @return the apellidos of this denuncia
	 */
	@AutoEscape
	public String getApellidos();

	/**
	 * Sets the apellidos of this denuncia.
	 *
	 * @param apellidos the apellidos of this denuncia
	 */
	public void setApellidos(String apellidos);

	/**
	 * Returns the nif of this denuncia.
	 *
	 * @return the nif of this denuncia
	 */
	@AutoEscape
	public String getNif();

	/**
	 * Sets the nif of this denuncia.
	 *
	 * @param nif the nif of this denuncia
	 */
	public void setNif(String nif);

	/**
	 * Returns the telefono of this denuncia.
	 *
	 * @return the telefono of this denuncia
	 */
	@AutoEscape
	public String getTelefono();

	/**
	 * Sets the telefono of this denuncia.
	 *
	 * @param telefono the telefono of this denuncia
	 */
	public void setTelefono(String telefono);

	/**
	 * Returns the anonimo of this denuncia.
	 *
	 * @return the anonimo of this denuncia
	 */
	public boolean getAnonimo();

	/**
	 * Returns <code>true</code> if this denuncia is anonimo.
	 *
	 * @return <code>true</code> if this denuncia is anonimo; <code>false</code> otherwise
	 */
	public boolean isAnonimo();

	/**
	 * Sets whether this denuncia is anonimo.
	 *
	 * @param anonimo the anonimo of this denuncia
	 */
	public void setAnonimo(boolean anonimo);

	/**
	 * Returns the tipo of this denuncia.
	 *
	 * @return the tipo of this denuncia
	 */
	public long getTipo();

	/**
	 * Sets the tipo of this denuncia.
	 *
	 * @param tipo the tipo of this denuncia
	 */
	public void setTipo(long tipo);

	/**
	 * Returns the categoria of this denuncia.
	 *
	 * @return the categoria of this denuncia
	 */
	public long getCategoria();

	/**
	 * Sets the categoria of this denuncia.
	 *
	 * @param categoria the categoria of this denuncia
	 */
	public void setCategoria(long categoria);

	/**
	 * Returns the asunto of this denuncia.
	 *
	 * @return the asunto of this denuncia
	 */
	@AutoEscape
	public String getAsunto();

	/**
	 * Sets the asunto of this denuncia.
	 *
	 * @param asunto the asunto of this denuncia
	 */
	public void setAsunto(String asunto);

	/**
	 * Returns the descripcion of this denuncia.
	 *
	 * @return the descripcion of this denuncia
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this denuncia.
	 *
	 * @param descripcion the descripcion of this denuncia
	 */
	public void setDescripcion(String descripcion);

	/**
	 * Returns the estado of this denuncia.
	 *
	 * @return the estado of this denuncia
	 */
	public long getEstado();

	/**
	 * Sets the estado of this denuncia.
	 *
	 * @param estado the estado of this denuncia
	 */
	public void setEstado(long estado);

	/**
	 * Returns the motivo ID of this denuncia.
	 *
	 * @return the motivo ID of this denuncia
	 */
	public long getMotivoId();

	/**
	 * Sets the motivo ID of this denuncia.
	 *
	 * @param motivoId the motivo ID of this denuncia
	 */
	public void setMotivoId(long motivoId);

	/**
	 * Returns the observaciones of this denuncia.
	 *
	 * @return the observaciones of this denuncia
	 */
	@AutoEscape
	public String getObservaciones();

	/**
	 * Sets the observaciones of this denuncia.
	 *
	 * @param observaciones the observaciones of this denuncia
	 */
	public void setObservaciones(String observaciones);

	/**
	 * Returns the create date of this denuncia.
	 *
	 * @return the create date of this denuncia
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this denuncia.
	 *
	 * @param createDate the create date of this denuncia
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this denuncia.
	 *
	 * @return the modified date of this denuncia
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this denuncia.
	 *
	 * @param modifiedDate the modified date of this denuncia
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the end date of this denuncia.
	 *
	 * @return the end date of this denuncia
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this denuncia.
	 *
	 * @param endDate the end date of this denuncia
	 */
	public void setEndDate(Date endDate);

}