/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.canal.etico.liferay.portlet.canal.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.LocalizedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Motivo service. Represents a row in the &quot;canal_etico_Motivo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.canal.etico.liferay.portlet.canal.manager.model.impl.MotivoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.canal.etico.liferay.portlet.canal.manager.model.impl.MotivoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Motivo
 * @generated
 */
@ProviderType
public interface MotivoModel extends BaseModel<Motivo>, LocalizedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a motivo model instance should use the {@link Motivo} interface instead.
	 */

	/**
	 * Returns the primary key of this motivo.
	 *
	 * @return the primary key of this motivo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this motivo.
	 *
	 * @param primaryKey the primary key of this motivo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the motivo ID of this motivo.
	 *
	 * @return the motivo ID of this motivo
	 */
	public long getMotivoId();

	/**
	 * Sets the motivo ID of this motivo.
	 *
	 * @param motivoId the motivo ID of this motivo
	 */
	public void setMotivoId(long motivoId);

	/**
	 * Returns the comp ID of this motivo.
	 *
	 * @return the comp ID of this motivo
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this motivo.
	 *
	 * @param compId the comp ID of this motivo
	 */
	public void setCompId(long compId);

	/**
	 * Returns the nombre of this motivo.
	 *
	 * @return the nombre of this motivo
	 */
	public String getNombre();

	/**
	 * Returns the localized nombre of this motivo in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized nombre of this motivo
	 */
	@AutoEscape
	public String getNombre(Locale locale);

	/**
	 * Returns the localized nombre of this motivo in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized nombre of this motivo. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getNombre(Locale locale, boolean useDefault);

	/**
	 * Returns the localized nombre of this motivo in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized nombre of this motivo
	 */
	@AutoEscape
	public String getNombre(String languageId);

	/**
	 * Returns the localized nombre of this motivo in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized nombre of this motivo
	 */
	@AutoEscape
	public String getNombre(String languageId, boolean useDefault);

	@AutoEscape
	public String getNombreCurrentLanguageId();

	@AutoEscape
	public String getNombreCurrentValue();

	/**
	 * Returns a map of the locales and localized nombres of this motivo.
	 *
	 * @return the locales and localized nombres of this motivo
	 */
	public Map<Locale, String> getNombreMap();

	/**
	 * Sets the nombre of this motivo.
	 *
	 * @param nombre the nombre of this motivo
	 */
	public void setNombre(String nombre);

	/**
	 * Sets the localized nombre of this motivo in the language.
	 *
	 * @param nombre the localized nombre of this motivo
	 * @param locale the locale of the language
	 */
	public void setNombre(String nombre, Locale locale);

	/**
	 * Sets the localized nombre of this motivo in the language, and sets the default locale.
	 *
	 * @param nombre the localized nombre of this motivo
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setNombre(String nombre, Locale locale, Locale defaultLocale);

	public void setNombreCurrentLanguageId(String languageId);

	/**
	 * Sets the localized nombres of this motivo from the map of locales and localized nombres.
	 *
	 * @param nombreMap the locales and localized nombres of this motivo
	 */
	public void setNombreMap(Map<Locale, String> nombreMap);

	/**
	 * Sets the localized nombres of this motivo from the map of locales and localized nombres, and sets the default locale.
	 *
	 * @param nombreMap the locales and localized nombres of this motivo
	 * @param defaultLocale the default locale
	 */
	public void setNombreMap(
		Map<Locale, String> nombreMap, Locale defaultLocale);

	/**
	 * Returns the observaciones of this motivo.
	 *
	 * @return the observaciones of this motivo
	 */
	public String getObservaciones();

	/**
	 * Returns the localized observaciones of this motivo in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized observaciones of this motivo
	 */
	@AutoEscape
	public String getObservaciones(Locale locale);

	/**
	 * Returns the localized observaciones of this motivo in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized observaciones of this motivo. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getObservaciones(Locale locale, boolean useDefault);

	/**
	 * Returns the localized observaciones of this motivo in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized observaciones of this motivo
	 */
	@AutoEscape
	public String getObservaciones(String languageId);

	/**
	 * Returns the localized observaciones of this motivo in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized observaciones of this motivo
	 */
	@AutoEscape
	public String getObservaciones(String languageId, boolean useDefault);

	@AutoEscape
	public String getObservacionesCurrentLanguageId();

	@AutoEscape
	public String getObservacionesCurrentValue();

	/**
	 * Returns a map of the locales and localized observacioneses of this motivo.
	 *
	 * @return the locales and localized observacioneses of this motivo
	 */
	public Map<Locale, String> getObservacionesMap();

	/**
	 * Sets the observaciones of this motivo.
	 *
	 * @param observaciones the observaciones of this motivo
	 */
	public void setObservaciones(String observaciones);

	/**
	 * Sets the localized observaciones of this motivo in the language.
	 *
	 * @param observaciones the localized observaciones of this motivo
	 * @param locale the locale of the language
	 */
	public void setObservaciones(String observaciones, Locale locale);

	/**
	 * Sets the localized observaciones of this motivo in the language, and sets the default locale.
	 *
	 * @param observaciones the localized observaciones of this motivo
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setObservaciones(
		String observaciones, Locale locale, Locale defaultLocale);

	public void setObservacionesCurrentLanguageId(String languageId);

	/**
	 * Sets the localized observacioneses of this motivo from the map of locales and localized observacioneses.
	 *
	 * @param observacionesMap the locales and localized observacioneses of this motivo
	 */
	public void setObservacionesMap(Map<Locale, String> observacionesMap);

	/**
	 * Sets the localized observacioneses of this motivo from the map of locales and localized observacioneses, and sets the default locale.
	 *
	 * @param observacionesMap the locales and localized observacioneses of this motivo
	 * @param defaultLocale the default locale
	 */
	public void setObservacionesMap(
		Map<Locale, String> observacionesMap, Locale defaultLocale);

	/**
	 * Returns the activo of this motivo.
	 *
	 * @return the activo of this motivo
	 */
	public boolean getActivo();

	/**
	 * Returns <code>true</code> if this motivo is activo.
	 *
	 * @return <code>true</code> if this motivo is activo; <code>false</code> otherwise
	 */
	public boolean isActivo();

	/**
	 * Sets whether this motivo is activo.
	 *
	 * @param activo the activo of this motivo
	 */
	public void setActivo(boolean activo);

	/**
	 * Returns the create date of this motivo.
	 *
	 * @return the create date of this motivo
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this motivo.
	 *
	 * @param createDate the create date of this motivo
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this motivo.
	 *
	 * @return the modified date of this motivo
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this motivo.
	 *
	 * @param modifiedDate the modified date of this motivo
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

}