/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.canal.etico.liferay.portlet.canal.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Observacion service. Represents a row in the &quot;canal_etico_Observacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.canal.etico.liferay.portlet.canal.manager.model.impl.ObservacionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.canal.etico.liferay.portlet.canal.manager.model.impl.ObservacionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Observacion
 * @generated
 */
@ProviderType
public interface ObservacionModel extends BaseModel<Observacion> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a observacion model instance should use the {@link Observacion} interface instead.
	 */

	/**
	 * Returns the primary key of this observacion.
	 *
	 * @return the primary key of this observacion
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this observacion.
	 *
	 * @param primaryKey the primary key of this observacion
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the observacion ID of this observacion.
	 *
	 * @return the observacion ID of this observacion
	 */
	public long getObservacionId();

	/**
	 * Sets the observacion ID of this observacion.
	 *
	 * @param observacionId the observacion ID of this observacion
	 */
	public void setObservacionId(long observacionId);

	/**
	 * Returns the denuncia ID of this observacion.
	 *
	 * @return the denuncia ID of this observacion
	 */
	public long getDenunciaId();

	/**
	 * Sets the denuncia ID of this observacion.
	 *
	 * @param denunciaId the denuncia ID of this observacion
	 */
	public void setDenunciaId(long denunciaId);

	/**
	 * Returns the user ID of this observacion.
	 *
	 * @return the user ID of this observacion
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this observacion.
	 *
	 * @param userId the user ID of this observacion
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this observacion.
	 *
	 * @return the user uuid of this observacion
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this observacion.
	 *
	 * @param userUuid the user uuid of this observacion
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the descripcion of this observacion.
	 *
	 * @return the descripcion of this observacion
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this observacion.
	 *
	 * @param descripcion the descripcion of this observacion
	 */
	public void setDescripcion(String descripcion);

	/**
	 * Returns the create date of this observacion.
	 *
	 * @return the create date of this observacion
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this observacion.
	 *
	 * @param createDate the create date of this observacion
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this observacion.
	 *
	 * @return the modified date of this observacion
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this observacion.
	 *
	 * @param modifiedDate the modified date of this observacion
	 */
	public void setModifiedDate(Date modifiedDate);

}