/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.canal.etico.liferay.portlet.canal.manager.model;

import com.canal.etico.liferay.portlet.canal.manager.service.persistence.UserCompanyPK;

import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserCompany service. Represents a row in the &quot;canal_etico_UserCompany&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.canal.etico.liferay.portlet.canal.manager.model.impl.UserCompanyModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.canal.etico.liferay.portlet.canal.manager.model.impl.UserCompanyImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserCompany
 * @generated
 */
@ProviderType
public interface UserCompanyModel extends BaseModel<UserCompany> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user company model instance should use the {@link UserCompany} interface instead.
	 */

	/**
	 * Returns the primary key of this user company.
	 *
	 * @return the primary key of this user company
	 */
	public UserCompanyPK getPrimaryKey();

	/**
	 * Sets the primary key of this user company.
	 *
	 * @param primaryKey the primary key of this user company
	 */
	public void setPrimaryKey(UserCompanyPK primaryKey);

	/**
	 * Returns the user ID of this user company.
	 *
	 * @return the user ID of this user company
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user company.
	 *
	 * @param userId the user ID of this user company
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user company.
	 *
	 * @return the user uuid of this user company
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user company.
	 *
	 * @param userUuid the user uuid of this user company
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the comp ID of this user company.
	 *
	 * @return the comp ID of this user company
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this user company.
	 *
	 * @param compId the comp ID of this user company
	 */
	public void setCompId(long compId);

	/**
	 * Returns the create date of this user company.
	 *
	 * @return the create date of this user company
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this user company.
	 *
	 * @param createDate the create date of this user company
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this user company.
	 *
	 * @return the modified date of this user company
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user company.
	 *
	 * @param modifiedDate the modified date of this user company
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the delete date of this user company.
	 *
	 * @return the delete date of this user company
	 */
	public Date getDeleteDate();

	/**
	 * Sets the delete date of this user company.
	 *
	 * @param deleteDate the delete date of this user company
	 */
	public void setDeleteDate(Date deleteDate);

}