/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.canal.etico.liferay.portlet.canal.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.LocalizedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Vinculacion service. Represents a row in the &quot;canal_etico_Vinculacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.canal.etico.liferay.portlet.canal.manager.model.impl.VinculacionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.canal.etico.liferay.portlet.canal.manager.model.impl.VinculacionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Vinculacion
 * @generated
 */
@ProviderType
public interface VinculacionModel
	extends BaseModel<Vinculacion>, LocalizedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vinculacion model instance should use the {@link Vinculacion} interface instead.
	 */

	/**
	 * Returns the primary key of this vinculacion.
	 *
	 * @return the primary key of this vinculacion
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vinculacion.
	 *
	 * @param primaryKey the primary key of this vinculacion
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the vinculacion ID of this vinculacion.
	 *
	 * @return the vinculacion ID of this vinculacion
	 */
	public long getVinculacionId();

	/**
	 * Sets the vinculacion ID of this vinculacion.
	 *
	 * @param vinculacionId the vinculacion ID of this vinculacion
	 */
	public void setVinculacionId(long vinculacionId);

	/**
	 * Returns the comp ID of this vinculacion.
	 *
	 * @return the comp ID of this vinculacion
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this vinculacion.
	 *
	 * @param compId the comp ID of this vinculacion
	 */
	public void setCompId(long compId);

	/**
	 * Returns the nombre of this vinculacion.
	 *
	 * @return the nombre of this vinculacion
	 */
	public String getNombre();

	/**
	 * Returns the localized nombre of this vinculacion in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized nombre of this vinculacion
	 */
	@AutoEscape
	public String getNombre(Locale locale);

	/**
	 * Returns the localized nombre of this vinculacion in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized nombre of this vinculacion. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getNombre(Locale locale, boolean useDefault);

	/**
	 * Returns the localized nombre of this vinculacion in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized nombre of this vinculacion
	 */
	@AutoEscape
	public String getNombre(String languageId);

	/**
	 * Returns the localized nombre of this vinculacion in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized nombre of this vinculacion
	 */
	@AutoEscape
	public String getNombre(String languageId, boolean useDefault);

	@AutoEscape
	public String getNombreCurrentLanguageId();

	@AutoEscape
	public String getNombreCurrentValue();

	/**
	 * Returns a map of the locales and localized nombres of this vinculacion.
	 *
	 * @return the locales and localized nombres of this vinculacion
	 */
	public Map<Locale, String> getNombreMap();

	/**
	 * Sets the nombre of this vinculacion.
	 *
	 * @param nombre the nombre of this vinculacion
	 */
	public void setNombre(String nombre);

	/**
	 * Sets the localized nombre of this vinculacion in the language.
	 *
	 * @param nombre the localized nombre of this vinculacion
	 * @param locale the locale of the language
	 */
	public void setNombre(String nombre, Locale locale);

	/**
	 * Sets the localized nombre of this vinculacion in the language, and sets the default locale.
	 *
	 * @param nombre the localized nombre of this vinculacion
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setNombre(String nombre, Locale locale, Locale defaultLocale);

	public void setNombreCurrentLanguageId(String languageId);

	/**
	 * Sets the localized nombres of this vinculacion from the map of locales and localized nombres.
	 *
	 * @param nombreMap the locales and localized nombres of this vinculacion
	 */
	public void setNombreMap(Map<Locale, String> nombreMap);

	/**
	 * Sets the localized nombres of this vinculacion from the map of locales and localized nombres, and sets the default locale.
	 *
	 * @param nombreMap the locales and localized nombres of this vinculacion
	 * @param defaultLocale the default locale
	 */
	public void setNombreMap(
		Map<Locale, String> nombreMap, Locale defaultLocale);

	/**
	 * Returns the activo of this vinculacion.
	 *
	 * @return the activo of this vinculacion
	 */
	public boolean getActivo();

	/**
	 * Returns <code>true</code> if this vinculacion is activo.
	 *
	 * @return <code>true</code> if this vinculacion is activo; <code>false</code> otherwise
	 */
	public boolean isActivo();

	/**
	 * Sets whether this vinculacion is activo.
	 *
	 * @param activo the activo of this vinculacion
	 */
	public void setActivo(boolean activo);

	/**
	 * Returns the create date of this vinculacion.
	 *
	 * @return the create date of this vinculacion
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this vinculacion.
	 *
	 * @param createDate the create date of this vinculacion
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this vinculacion.
	 *
	 * @return the modified date of this vinculacion
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this vinculacion.
	 *
	 * @param modifiedDate the modified date of this vinculacion
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

}