/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.legalplus.liferay.portlet.legalplus.manager.model;

import com.legalplus.liferay.portlet.legalplus.manager.service.persistence.AyuntamientoPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Ayuntamiento service. Represents a row in the &quot;legalplus_Ayuntamiento&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.legalplus.liferay.portlet.legalplus.manager.model.impl.AyuntamientoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.legalplus.liferay.portlet.legalplus.manager.model.impl.AyuntamientoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Ayuntamiento
 * @generated
 */
@ProviderType
public interface AyuntamientoModel extends BaseModel<Ayuntamiento> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ayuntamiento model instance should use the {@link Ayuntamiento} interface instead.
	 */

	/**
	 * Returns the primary key of this ayuntamiento.
	 *
	 * @return the primary key of this ayuntamiento
	 */
	public AyuntamientoPK getPrimaryKey();

	/**
	 * Sets the primary key of this ayuntamiento.
	 *
	 * @param primaryKey the primary key of this ayuntamiento
	 */
	public void setPrimaryKey(AyuntamientoPK primaryKey);

	/**
	 * Returns the ccaa ID of this ayuntamiento.
	 *
	 * @return the ccaa ID of this ayuntamiento
	 */
	public long getCcaaId();

	/**
	 * Sets the ccaa ID of this ayuntamiento.
	 *
	 * @param ccaaId the ccaa ID of this ayuntamiento
	 */
	public void setCcaaId(long ccaaId);

	/**
	 * Returns the provincia ID of this ayuntamiento.
	 *
	 * @return the provincia ID of this ayuntamiento
	 */
	public long getProvinciaId();

	/**
	 * Sets the provincia ID of this ayuntamiento.
	 *
	 * @param provinciaId the provincia ID of this ayuntamiento
	 */
	public void setProvinciaId(long provinciaId);

	/**
	 * Returns the ayuntamiento ID of this ayuntamiento.
	 *
	 * @return the ayuntamiento ID of this ayuntamiento
	 */
	public long getAyuntamientoId();

	/**
	 * Sets the ayuntamiento ID of this ayuntamiento.
	 *
	 * @param ayuntamientoId the ayuntamiento ID of this ayuntamiento
	 */
	public void setAyuntamientoId(long ayuntamientoId);

	/**
	 * Returns the nombre of this ayuntamiento.
	 *
	 * @return the nombre of this ayuntamiento
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this ayuntamiento.
	 *
	 * @param nombre the nombre of this ayuntamiento
	 */
	public void setNombre(String nombre);

}