/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.legalplus.liferay.portlet.legalplus.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CCAA service. Represents a row in the &quot;legalplus_CCAA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.legalplus.liferay.portlet.legalplus.manager.model.impl.CCAAModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.legalplus.liferay.portlet.legalplus.manager.model.impl.CCAAImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CCAA
 * @generated
 */
@ProviderType
public interface CCAAModel extends BaseModel<CCAA> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ccaa model instance should use the {@link CCAA} interface instead.
	 */

	/**
	 * Returns the primary key of this ccaa.
	 *
	 * @return the primary key of this ccaa
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ccaa.
	 *
	 * @param primaryKey the primary key of this ccaa
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ccaa ID of this ccaa.
	 *
	 * @return the ccaa ID of this ccaa
	 */
	public long getCcaaId();

	/**
	 * Sets the ccaa ID of this ccaa.
	 *
	 * @param ccaaId the ccaa ID of this ccaa
	 */
	public void setCcaaId(long ccaaId);

	/**
	 * Returns the nombre of this ccaa.
	 *
	 * @return the nombre of this ccaa
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this ccaa.
	 *
	 * @param nombre the nombre of this ccaa
	 */
	public void setNombre(String nombre);

}