/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.legalplus.liferay.portlet.legalplus.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CNAES service. Represents a row in the &quot;legalplus_CNAES&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.legalplus.liferay.portlet.legalplus.manager.model.impl.CNAESModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.legalplus.liferay.portlet.legalplus.manager.model.impl.CNAESImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CNAES
 * @generated
 */
@ProviderType
public interface CNAESModel extends BaseModel<CNAES> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cnaes model instance should use the {@link CNAES} interface instead.
	 */

	/**
	 * Returns the primary key of this cnaes.
	 *
	 * @return the primary key of this cnaes
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this cnaes.
	 *
	 * @param primaryKey the primary key of this cnaes
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the cnae of this cnaes.
	 *
	 * @return the cnae of this cnaes
	 */
	@AutoEscape
	public String getCnae();

	/**
	 * Sets the cnae of this cnaes.
	 *
	 * @param cnae the cnae of this cnaes
	 */
	public void setCnae(String cnae);

	/**
	 * Returns the nombre of this cnaes.
	 *
	 * @return the nombre of this cnaes
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this cnaes.
	 *
	 * @param nombre the nombre of this cnaes
	 */
	public void setNombre(String nombre);

}