/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.legalplus.liferay.portlet.legalplus.manager.model;

import com.legalplus.liferay.portlet.legalplus.manager.service.persistence.ConsultorCompanyPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ConsultorCompany service. Represents a row in the &quot;legalplus_ConsultorCompany&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.legalplus.liferay.portlet.legalplus.manager.model.impl.ConsultorCompanyModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.legalplus.liferay.portlet.legalplus.manager.model.impl.ConsultorCompanyImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ConsultorCompany
 * @generated
 */
@ProviderType
public interface ConsultorCompanyModel extends BaseModel<ConsultorCompany> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a consultor company model instance should use the {@link ConsultorCompany} interface instead.
	 */

	/**
	 * Returns the primary key of this consultor company.
	 *
	 * @return the primary key of this consultor company
	 */
	public ConsultorCompanyPK getPrimaryKey();

	/**
	 * Sets the primary key of this consultor company.
	 *
	 * @param primaryKey the primary key of this consultor company
	 */
	public void setPrimaryKey(ConsultorCompanyPK primaryKey);

	/**
	 * Returns the app ID of this consultor company.
	 *
	 * @return the app ID of this consultor company
	 */
	public long getAppId();

	/**
	 * Sets the app ID of this consultor company.
	 *
	 * @param appId the app ID of this consultor company
	 */
	public void setAppId(long appId);

	/**
	 * Returns the user ID of this consultor company.
	 *
	 * @return the user ID of this consultor company
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this consultor company.
	 *
	 * @param userId the user ID of this consultor company
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this consultor company.
	 *
	 * @return the user uuid of this consultor company
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this consultor company.
	 *
	 * @param userUuid the user uuid of this consultor company
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the comp ID of this consultor company.
	 *
	 * @return the comp ID of this consultor company
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this consultor company.
	 *
	 * @param compId the comp ID of this consultor company
	 */
	public void setCompId(long compId);

	/**
	 * Returns the name of this consultor company.
	 *
	 * @return the name of this consultor company
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this consultor company.
	 *
	 * @param name the name of this consultor company
	 */
	public void setName(String name);

	/**
	 * Returns the last name of this consultor company.
	 *
	 * @return the last name of this consultor company
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this consultor company.
	 *
	 * @param lastName the last name of this consultor company
	 */
	public void setLastName(String lastName);

}