/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.legalplus.liferay.portlet.legalplus.manager.model;

import com.legalplus.liferay.portlet.legalplus.manager.service.persistence.ContratoCompanyPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ContratoCompany service. Represents a row in the &quot;legalplus_ContratoCompany&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.legalplus.liferay.portlet.legalplus.manager.model.impl.ContratoCompanyModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.legalplus.liferay.portlet.legalplus.manager.model.impl.ContratoCompanyImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContratoCompany
 * @generated
 */
@ProviderType
public interface ContratoCompanyModel extends BaseModel<ContratoCompany> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a contrato company model instance should use the {@link ContratoCompany} interface instead.
	 */

	/**
	 * Returns the primary key of this contrato company.
	 *
	 * @return the primary key of this contrato company
	 */
	public ContratoCompanyPK getPrimaryKey();

	/**
	 * Sets the primary key of this contrato company.
	 *
	 * @param primaryKey the primary key of this contrato company
	 */
	public void setPrimaryKey(ContratoCompanyPK primaryKey);

	/**
	 * Returns the contract ID of this contrato company.
	 *
	 * @return the contract ID of this contrato company
	 */
	public long getContractId();

	/**
	 * Sets the contract ID of this contrato company.
	 *
	 * @param contractId the contract ID of this contrato company
	 */
	public void setContractId(long contractId);

	/**
	 * Returns the comp ID of this contrato company.
	 *
	 * @return the comp ID of this contrato company
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this contrato company.
	 *
	 * @param compId the comp ID of this contrato company
	 */
	public void setCompId(long compId);

	/**
	 * Returns the familia of this contrato company.
	 *
	 * @return the familia of this contrato company
	 */
	@AutoEscape
	public String getFamilia();

	/**
	 * Sets the familia of this contrato company.
	 *
	 * @param familia the familia of this contrato company
	 */
	public void setFamilia(String familia);

	/**
	 * Returns the ccaa of this contrato company.
	 *
	 * @return the ccaa of this contrato company
	 */
	@AutoEscape
	public String getCcaa();

	/**
	 * Sets the ccaa of this contrato company.
	 *
	 * @param ccaa the ccaa of this contrato company
	 */
	public void setCcaa(String ccaa);

	/**
	 * Returns the ayuntamiento of this contrato company.
	 *
	 * @return the ayuntamiento of this contrato company
	 */
	@AutoEscape
	public String getAyuntamiento();

	/**
	 * Sets the ayuntamiento of this contrato company.
	 *
	 * @param ayuntamiento the ayuntamiento of this contrato company
	 */
	public void setAyuntamiento(String ayuntamiento);

	/**
	 * Returns the cnaes of this contrato company.
	 *
	 * @return the cnaes of this contrato company
	 */
	@AutoEscape
	public String getCnaes();

	/**
	 * Sets the cnaes of this contrato company.
	 *
	 * @param cnaes the cnaes of this contrato company
	 */
	public void setCnaes(String cnaes);

}