/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.legalplus.liferay.portlet.legalplus.manager.model;

import com.legalplus.liferay.portlet.legalplus.manager.service.persistence.EvalLegislacionPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EvalLegislacion service. Represents a row in the &quot;legalplus_EvalLegislacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.legalplus.liferay.portlet.legalplus.manager.model.impl.EvalLegislacionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.legalplus.liferay.portlet.legalplus.manager.model.impl.EvalLegislacionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EvalLegislacion
 * @generated
 */
@ProviderType
public interface EvalLegislacionModel extends BaseModel<EvalLegislacion> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a eval legislacion model instance should use the {@link EvalLegislacion} interface instead.
	 */

	/**
	 * Returns the primary key of this eval legislacion.
	 *
	 * @return the primary key of this eval legislacion
	 */
	public EvalLegislacionPK getPrimaryKey();

	/**
	 * Sets the primary key of this eval legislacion.
	 *
	 * @param primaryKey the primary key of this eval legislacion
	 */
	public void setPrimaryKey(EvalLegislacionPK primaryKey);

	/**
	 * Returns the version of this eval legislacion.
	 *
	 * @return the version of this eval legislacion
	 */
	public long getVersion();

	/**
	 * Sets the version of this eval legislacion.
	 *
	 * @param version the version of this eval legislacion
	 */
	public void setVersion(long version);

	/**
	 * Returns the comp ID of this eval legislacion.
	 *
	 * @return the comp ID of this eval legislacion
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this eval legislacion.
	 *
	 * @param compId the comp ID of this eval legislacion
	 */
	public void setCompId(long compId);

	/**
	 * Returns the legislacion ID of this eval legislacion.
	 *
	 * @return the legislacion ID of this eval legislacion
	 */
	@AutoEscape
	public String getLegislacionId();

	/**
	 * Sets the legislacion ID of this eval legislacion.
	 *
	 * @param legislacionId the legislacion ID of this eval legislacion
	 */
	public void setLegislacionId(String legislacionId);

	/**
	 * Returns the fecha of this eval legislacion.
	 *
	 * @return the fecha of this eval legislacion
	 */
	public Date getFecha();

	/**
	 * Sets the fecha of this eval legislacion.
	 *
	 * @param fecha the fecha of this eval legislacion
	 */
	public void setFecha(Date fecha);

	/**
	 * Returns the proxima of this eval legislacion.
	 *
	 * @return the proxima of this eval legislacion
	 */
	public Date getProxima();

	/**
	 * Sets the proxima of this eval legislacion.
	 *
	 * @param proxima the proxima of this eval legislacion
	 */
	public void setProxima(Date proxima);

	/**
	 * Returns the cumplimiento of this eval legislacion.
	 *
	 * @return the cumplimiento of this eval legislacion
	 */
	public int getCumplimiento();

	/**
	 * Sets the cumplimiento of this eval legislacion.
	 *
	 * @param cumplimiento the cumplimiento of this eval legislacion
	 */
	public void setCumplimiento(int cumplimiento);

	/**
	 * Returns the usuario of this eval legislacion.
	 *
	 * @return the usuario of this eval legislacion
	 */
	public long getUsuario();

	/**
	 * Sets the usuario of this eval legislacion.
	 *
	 * @param usuario the usuario of this eval legislacion
	 */
	public void setUsuario(long usuario);

	/**
	 * Returns the adjunto of this eval legislacion.
	 *
	 * @return the adjunto of this eval legislacion
	 */
	public long getAdjunto();

	/**
	 * Sets the adjunto of this eval legislacion.
	 *
	 * @param adjunto the adjunto of this eval legislacion
	 */
	public void setAdjunto(long adjunto);

	/**
	 * Returns the observaciones of this eval legislacion.
	 *
	 * @return the observaciones of this eval legislacion
	 */
	@AutoEscape
	public String getObservaciones();

	/**
	 * Sets the observaciones of this eval legislacion.
	 *
	 * @param observaciones the observaciones of this eval legislacion
	 */
	public void setObservaciones(String observaciones);

}