/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.legalplus.liferay.portlet.legalplus.manager.model;

import com.legalplus.liferay.portlet.legalplus.manager.service.persistence.HiddenLegisPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the HiddenLegis service. Represents a row in the &quot;legalplus_HiddenLegis&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.legalplus.liferay.portlet.legalplus.manager.model.impl.HiddenLegisModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.legalplus.liferay.portlet.legalplus.manager.model.impl.HiddenLegisImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HiddenLegis
 * @generated
 */
@ProviderType
public interface HiddenLegisModel extends BaseModel<HiddenLegis> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a hidden legis model instance should use the {@link HiddenLegis} interface instead.
	 */

	/**
	 * Returns the primary key of this hidden legis.
	 *
	 * @return the primary key of this hidden legis
	 */
	public HiddenLegisPK getPrimaryKey();

	/**
	 * Sets the primary key of this hidden legis.
	 *
	 * @param primaryKey the primary key of this hidden legis
	 */
	public void setPrimaryKey(HiddenLegisPK primaryKey);

	/**
	 * Returns the legislacion ID of this hidden legis.
	 *
	 * @return the legislacion ID of this hidden legis
	 */
	@AutoEscape
	public String getLegislacionId();

	/**
	 * Sets the legislacion ID of this hidden legis.
	 *
	 * @param legislacionId the legislacion ID of this hidden legis
	 */
	public void setLegislacionId(String legislacionId);

	/**
	 * Returns the empresa ID of this hidden legis.
	 *
	 * @return the empresa ID of this hidden legis
	 */
	public long getEmpresaId();

	/**
	 * Sets the empresa ID of this hidden legis.
	 *
	 * @param empresaId the empresa ID of this hidden legis
	 */
	public void setEmpresaId(long empresaId);

}