/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.legalplus.liferay.portlet.legalplus.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Legislacion service. Represents a row in the &quot;legalplus_Legislacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.legalplus.liferay.portlet.legalplus.manager.model.impl.LegislacionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.legalplus.liferay.portlet.legalplus.manager.model.impl.LegislacionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Legislacion
 * @generated
 */
@ProviderType
public interface LegislacionModel extends BaseModel<Legislacion> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a legislacion model instance should use the {@link Legislacion} interface instead.
	 */

	/**
	 * Returns the primary key of this legislacion.
	 *
	 * @return the primary key of this legislacion
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this legislacion.
	 *
	 * @param primaryKey the primary key of this legislacion
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the legislacion ID of this legislacion.
	 *
	 * @return the legislacion ID of this legislacion
	 */
	@AutoEscape
	public String getLegislacionId();

	/**
	 * Sets the legislacion ID of this legislacion.
	 *
	 * @param legislacionId the legislacion ID of this legislacion
	 */
	public void setLegislacionId(String legislacionId);

	/**
	 * Returns the nombre of this legislacion.
	 *
	 * @return the nombre of this legislacion
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this legislacion.
	 *
	 * @param nombre the nombre of this legislacion
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the familia of this legislacion.
	 *
	 * @return the familia of this legislacion
	 */
	@AutoEscape
	public String getFamilia();

	/**
	 * Sets the familia of this legislacion.
	 *
	 * @param familia the familia of this legislacion
	 */
	public void setFamilia(String familia);

	/**
	 * Returns the tipo of this legislacion.
	 *
	 * @return the tipo of this legislacion
	 */
	public long getTipo();

	/**
	 * Sets the tipo of this legislacion.
	 *
	 * @param tipo the tipo of this legislacion
	 */
	public void setTipo(long tipo);

	/**
	 * Returns the ambito of this legislacion.
	 *
	 * @return the ambito of this legislacion
	 */
	public long getAmbito();

	/**
	 * Sets the ambito of this legislacion.
	 *
	 * @param ambito the ambito of this legislacion
	 */
	public void setAmbito(long ambito);

	/**
	 * Returns the publicacion of this legislacion.
	 *
	 * @return the publicacion of this legislacion
	 */
	public Date getPublicacion();

	/**
	 * Sets the publicacion of this legislacion.
	 *
	 * @param publicacion the publicacion of this legislacion
	 */
	public void setPublicacion(Date publicacion);

	/**
	 * Returns the derogacion of this legislacion.
	 *
	 * @return the derogacion of this legislacion
	 */
	public Date getDerogacion();

	/**
	 * Sets the derogacion of this legislacion.
	 *
	 * @param derogacion the derogacion of this legislacion
	 */
	public void setDerogacion(Date derogacion);

	/**
	 * Returns the descripcion of this legislacion.
	 *
	 * @return the descripcion of this legislacion
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this legislacion.
	 *
	 * @param descripcion the descripcion of this legislacion
	 */
	public void setDescripcion(String descripcion);

	/**
	 * Returns the etiquetas of this legislacion.
	 *
	 * @return the etiquetas of this legislacion
	 */
	@AutoEscape
	public String getEtiquetas();

	/**
	 * Sets the etiquetas of this legislacion.
	 *
	 * @param etiquetas the etiquetas of this legislacion
	 */
	public void setEtiquetas(String etiquetas);

	/**
	 * Returns the enlace of this legislacion.
	 *
	 * @return the enlace of this legislacion
	 */
	@AutoEscape
	public String getEnlace();

	/**
	 * Sets the enlace of this legislacion.
	 *
	 * @param enlace the enlace of this legislacion
	 */
	public void setEnlace(String enlace);

	/**
	 * Returns the ccaa of this legislacion.
	 *
	 * @return the ccaa of this legislacion
	 */
	public long getCcaa();

	/**
	 * Sets the ccaa of this legislacion.
	 *
	 * @param ccaa the ccaa of this legislacion
	 */
	public void setCcaa(long ccaa);

	/**
	 * Returns the ayuntamiento of this legislacion.
	 *
	 * @return the ayuntamiento of this legislacion
	 */
	public long getAyuntamiento();

	/**
	 * Sets the ayuntamiento of this legislacion.
	 *
	 * @param ayuntamiento the ayuntamiento of this legislacion
	 */
	public void setAyuntamiento(long ayuntamiento);

	/**
	 * Returns the urgente of this legislacion.
	 *
	 * @return the urgente of this legislacion
	 */
	public Date getUrgente();

	/**
	 * Sets the urgente of this legislacion.
	 *
	 * @param urgente the urgente of this legislacion
	 */
	public void setUrgente(Date urgente);

	/**
	 * Returns the empresas of this legislacion.
	 *
	 * @return the empresas of this legislacion
	 */
	@AutoEscape
	public String getEmpresas();

	/**
	 * Sets the empresas of this legislacion.
	 *
	 * @param empresas the empresas of this legislacion
	 */
	public void setEmpresas(String empresas);

	/**
	 * Returns the create date of this legislacion.
	 *
	 * @return the create date of this legislacion
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this legislacion.
	 *
	 * @param createDate the create date of this legislacion
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this legislacion.
	 *
	 * @return the modified date of this legislacion
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this legislacion.
	 *
	 * @param modifiedDate the modified date of this legislacion
	 */
	public void setModifiedDate(Date modifiedDate);

}