/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.legalplus.liferay.portlet.legalplus.manager.model;

import com.legalplus.liferay.portlet.legalplus.manager.service.persistence.ProvinciaPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Provincia service. Represents a row in the &quot;legalplus_Provincia&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.legalplus.liferay.portlet.legalplus.manager.model.impl.ProvinciaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.legalplus.liferay.portlet.legalplus.manager.model.impl.ProvinciaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Provincia
 * @generated
 */
@ProviderType
public interface ProvinciaModel extends BaseModel<Provincia> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a provincia model instance should use the {@link Provincia} interface instead.
	 */

	/**
	 * Returns the primary key of this provincia.
	 *
	 * @return the primary key of this provincia
	 */
	public ProvinciaPK getPrimaryKey();

	/**
	 * Sets the primary key of this provincia.
	 *
	 * @param primaryKey the primary key of this provincia
	 */
	public void setPrimaryKey(ProvinciaPK primaryKey);

	/**
	 * Returns the ccaa ID of this provincia.
	 *
	 * @return the ccaa ID of this provincia
	 */
	public long getCcaaId();

	/**
	 * Sets the ccaa ID of this provincia.
	 *
	 * @param ccaaId the ccaa ID of this provincia
	 */
	public void setCcaaId(long ccaaId);

	/**
	 * Returns the provincia ID of this provincia.
	 *
	 * @return the provincia ID of this provincia
	 */
	public long getProvinciaId();

	/**
	 * Sets the provincia ID of this provincia.
	 *
	 * @param provinciaId the provincia ID of this provincia
	 */
	public void setProvinciaId(long provinciaId);

	/**
	 * Returns the nombre of this provincia.
	 *
	 * @return the nombre of this provincia
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this provincia.
	 *
	 * @param nombre the nombre of this provincia
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the capital ID of this provincia.
	 *
	 * @return the capital ID of this provincia
	 */
	public long getCapitalId();

	/**
	 * Sets the capital ID of this provincia.
	 *
	 * @param capitalId the capital ID of this provincia
	 */
	public void setCapitalId(long capitalId);

}