/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.legalplus.liferay.portlet.legalplus.manager.model;

import com.legalplus.liferay.portlet.legalplus.manager.service.persistence.RequisitoPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Requisito service. Represents a row in the &quot;legalplus_Requisito&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.legalplus.liferay.portlet.legalplus.manager.model.impl.RequisitoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.legalplus.liferay.portlet.legalplus.manager.model.impl.RequisitoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Requisito
 * @generated
 */
@ProviderType
public interface RequisitoModel extends BaseModel<Requisito> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a requisito model instance should use the {@link Requisito} interface instead.
	 */

	/**
	 * Returns the primary key of this requisito.
	 *
	 * @return the primary key of this requisito
	 */
	public RequisitoPK getPrimaryKey();

	/**
	 * Sets the primary key of this requisito.
	 *
	 * @param primaryKey the primary key of this requisito
	 */
	public void setPrimaryKey(RequisitoPK primaryKey);

	/**
	 * Returns the legislacion ID of this requisito.
	 *
	 * @return the legislacion ID of this requisito
	 */
	@AutoEscape
	public String getLegislacionId();

	/**
	 * Sets the legislacion ID of this requisito.
	 *
	 * @param legislacionId the legislacion ID of this requisito
	 */
	public void setLegislacionId(String legislacionId);

	/**
	 * Returns the requisito ID of this requisito.
	 *
	 * @return the requisito ID of this requisito
	 */
	@AutoEscape
	public String getRequisitoId();

	/**
	 * Sets the requisito ID of this requisito.
	 *
	 * @param requisitoId the requisito ID of this requisito
	 */
	public void setRequisitoId(String requisitoId);

	/**
	 * Returns the descripcion of this requisito.
	 *
	 * @return the descripcion of this requisito
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this requisito.
	 *
	 * @param descripcion the descripcion of this requisito
	 */
	public void setDescripcion(String descripcion);

	/**
	 * Returns the baja of this requisito.
	 *
	 * @return the baja of this requisito
	 */
	public Date getBaja();

	/**
	 * Sets the baja of this requisito.
	 *
	 * @param baja the baja of this requisito
	 */
	public void setBaja(Date baja);

	/**
	 * Returns the create date of this requisito.
	 *
	 * @return the create date of this requisito
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this requisito.
	 *
	 * @param createDate the create date of this requisito
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this requisito.
	 *
	 * @return the modified date of this requisito
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this requisito.
	 *
	 * @param modifiedDate the modified date of this requisito
	 */
	public void setModifiedDate(Date modifiedDate);

}