/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.legalplus.liferay.portlet.legalplus.manager.model;

import com.legalplus.liferay.portlet.legalplus.manager.service.persistence.RequisitoCNAESPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RequisitoCNAES service. Represents a row in the &quot;legalplus_RequisitoCNAES&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.legalplus.liferay.portlet.legalplus.manager.model.impl.RequisitoCNAESModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.legalplus.liferay.portlet.legalplus.manager.model.impl.RequisitoCNAESImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RequisitoCNAES
 * @generated
 */
@ProviderType
public interface RequisitoCNAESModel extends BaseModel<RequisitoCNAES> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a requisito cnaes model instance should use the {@link RequisitoCNAES} interface instead.
	 */

	/**
	 * Returns the primary key of this requisito cnaes.
	 *
	 * @return the primary key of this requisito cnaes
	 */
	public RequisitoCNAESPK getPrimaryKey();

	/**
	 * Sets the primary key of this requisito cnaes.
	 *
	 * @param primaryKey the primary key of this requisito cnaes
	 */
	public void setPrimaryKey(RequisitoCNAESPK primaryKey);

	/**
	 * Returns the legislacion ID of this requisito cnaes.
	 *
	 * @return the legislacion ID of this requisito cnaes
	 */
	@AutoEscape
	public String getLegislacionId();

	/**
	 * Sets the legislacion ID of this requisito cnaes.
	 *
	 * @param legislacionId the legislacion ID of this requisito cnaes
	 */
	public void setLegislacionId(String legislacionId);

	/**
	 * Returns the requisito ID of this requisito cnaes.
	 *
	 * @return the requisito ID of this requisito cnaes
	 */
	@AutoEscape
	public String getRequisitoId();

	/**
	 * Sets the requisito ID of this requisito cnaes.
	 *
	 * @param requisitoId the requisito ID of this requisito cnaes
	 */
	public void setRequisitoId(String requisitoId);

	/**
	 * Returns the cnae of this requisito cnaes.
	 *
	 * @return the cnae of this requisito cnaes
	 */
	@AutoEscape
	public String getCnae();

	/**
	 * Sets the cnae of this requisito cnaes.
	 *
	 * @param cnae the cnae of this requisito cnaes
	 */
	public void setCnae(String cnae);

	/**
	 * Returns the create date of this requisito cnaes.
	 *
	 * @return the create date of this requisito cnaes
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this requisito cnaes.
	 *
	 * @param createDate the create date of this requisito cnaes
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this requisito cnaes.
	 *
	 * @return the modified date of this requisito cnaes
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this requisito cnaes.
	 *
	 * @param modifiedDate the modified date of this requisito cnaes
	 */
	public void setModifiedDate(Date modifiedDate);

}