include-and-override=portal-developer.properties


#
# MySQL
#
jdbc.default.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.default.url=jdbc:mysql://10.51.80.3/control-adeplus?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false&serverTimezone=UTC&autoReconnect=true&useSSL=false
jdbc.default.username=control-adeplus
jdbc.default.password=IA0zlwHCiCP4o3zi


#
# Set the properties used to create the Java Mail session. The property
# prefix "mail.session." will be removed before it is used to create the
# session object. These properties will only be read if the property
# "mail.session.jndi.name" is not set.
#
mail.session.mail=false
mail.session.mail.pop3.host=mail.adeplusconsultores.com
mail.session.mail.pop3.password=sSHMn231
mail.session.mail.pop3.port=110
mail.session.mail.pop3.user=no-reply@adeplusconsultores.com
mail.session.mail.smtp.auth=true
mail.session.mail.smtp.host=mail.adeplusconsultores.com
mail.session.mail.smtp.password=HFS7Srhw
mail.session.mail.smtp.port=25
mail.session.mail.smtp.starttls.enable=true
mail.session.mail.smtp.user=no-reply@adeplusconsultores.com
mail.session.mail.store.protocol=pop3
mail.session.mail.transport.protocol=smtps


admin.email.user.added.enabled=false

#
# Specify the number of minutes before a session expires. This value is
# always overridden by the value set in web.xml.
#
session.timeout=60

#
# Specify the number of minutes before a warning is sent to the user
# informing the user of the session expiration. Specify 0 to disable any
# warnings.
#
session.timeout.warning=1

#
# Set the auto-extend mode to true to avoid having to ask the user whether
# to extend the session or not. Instead, it will be automatically extended.
# The purpose of this mode is to keep the session open as long as the user's
# browser is open with a portal page loaded. It is recommended to use this
# setting along with a smaller "session.timeout", such as 5 minutes, for
# better performance.
#
session.timeout.auto.extend=true

#
# When the property "session.timeout.auto.extend" is set to true, set the
# number of seconds between when the extend process is launched and the
# actual expiration of the session.
#
session.timeout.auto.extend.offset=10

#
# Set this to true if the user is redirected to the default page when the
# session expires.
#
session.timeout.redirect.on.expire=true

#
# Set this property to "ip" or "domain" for the redirect security method. If
# set to "domain", the portal will only redirect users to domains listed in
# the property "redirect.url.domain.allowed". If set to "ip", the portal
# will only redirect to domains whose IP address resolve to an IP address
# listed in the property "redirect.url.ip.allowed".
#
# Env: LIFERAY_REDIRECT_PERIOD_URL_PERIOD_SECURITY_PERIOD_MODE
#
redirect.url.security.mode=domain

##
## Default Logout Page
##

#
# Set the default logout page path for users relative to the server path.
# This is the page users are automatically redirected to after logging out.
# For example, if you want the default logout page to be
# http://localhost:8080/web/guest/logout, set this to /web/guest/logout. To
# activate this feature, set auth.forward.by.last.path to true. To customize
# the behavior, see com.liferay.portal.events.DefaultLogoutPageAction in the
# "logout.events.post" property above.
#
#default.logout.page.path=
default.logout.page.path=/web/guest/


#
# Set this to true if users are forwarded to the last visited path upon
# successful login. If set to false, users will be forwarded to their
# default layout page.
#
auth.forward.by.last.path=true

#
# Configure email notification settings.
#
admin.email.from.name=Adeplus Consultores
admin.email.from.address=no-reply@adeplusconsultores.com


#
# The login field is prepopulated with the company's domain name if the
# login is unpopulated and user authentication is based on email addresses.
# Set this to false to disable the behavior.
#
company.login.prepopulate.domain=false

#
# Set this to true to enable reminder queries that are used to help reset a
# user's password.
#
users.reminder.queries.enabled=false
users.reminder.queries.custom.question.enabled=false

#
# Set this to false to enable users without a reminder query to reset their
# password.
#
users.reminder.queries.required=false


##
## Authentication Pipeline
##
#
# Enter a friendly URL of a page that will be used to login portal users
# whenever the user is navigating a site and authentication is needed. By
# default, the portal's login page or the URL set in the property
# "auth.login.url" is used.
#
auth.login.site.url=/login



##
## Default Landing Page
##
#
# Set the default landing page path for logged in users relative to the
# server path. This is the page users are automatically redirected to after
# logging in. For example, if you want the default landing page to be
# http://localhost:8080/web/guest/login, set this to /web/guest/login. To
# activate this feature, set auth.forward.by.last.path to true. To customize
# the behavior, see com.liferay.portal.events.DefaultLandingPageAction in
# the "login.events.post" property above.
#
# The following variables can be used: ${liferay:screenName} and
# ${liferay:userId}.
#
default.landing.page.path=/web/guest/dashboard
#default.landing.page.path=/web/guest/login
#default.landing.page.path=/user/${liferay:screenName}/home

##
## Look and Feel
##
#
# Set the default theme ID for regular themes.
#
# Env: LIFERAY_DEFAULT_PERIOD_REGULAR_PERIOD_THEME_PERIOD_ID
#
default.regular.theme.id=adeplustheme_WAR_adeplustheme


##
## ADEPLUS Configuration
##
#
# The name of the roles created to use in Suite Adeplus. The first one is for the
# user who created all the companies. The second one is the administrator of
# the company site, and the last one is the user.
#
adeplus.rol.adeplus.admin=Adeplus Administrator
adeplus.rol.company.admin=Company Administrator
adeplus.rol.company.user=Company User

# The name of the roles created to use in Canal Ético. The first one is for the
# user who created all the companies. The second one is the administrator of
# the company site, and the last one is the user.
#
canal.etico.rol.company.admin=Canal Etico Company Administrator
canal.etico.rol.company.user=Canal Etico Company User
canal.etico.rol.adeplus.admin=Canal Etico Administrator

#
# Name for Password Policy
#
adeplus.password.policy.name=Suite Adeplus Password Policy

#
# ALIAS FOR APPLICATION CANAL ETICO / CANAL DENUNCIAS
#
adeplus.application.name.canal.etico=CANAL_DENUNCIAS
adeplus.application.name.registro.horas=REGISTRO_HORAS

#
# Days for use in admin denuncias
#
canal.etico.denuncia.days.after.create=90
canal.etico.denuncia.days.after.create.advise=83
canal.etico.denuncia.days.after.finish=3

#
# Configuration for Dashboard. Get more info url.
#
preving.dashboard.get.info.url=https://adeplusconsultores.com/formulario-servicios-adeplus/

#
# Configuration for Keycloak
#
preving.keycloak.configuration.realname=PREVING
preving.keycloak.configuration.url=https://security.suiteadeplus.com/auth/
preving.keycloak.configuration.username=adminkc
preving.keycloak.configuration.pass=6QYr5SBa
preving.keycloak.configuration.clientid=realm-management
preving.keycloak.configuration.secret=2abbad0d-35d7-4db0-a310-29dc3deb6083


#
# Configuration for mailing
#
# Suite Adeplus
preving.adeplus.mail.template.logo.url=https://www.suiteadeplus.com/documents/20121/39772/logo_adeplus.png
preving.adeplus.mail.template.background.url=https://www.suiteadeplus.com/documents/20121/39772/fondo_mail.jpg
preving.adeplus.mail.template.video.url=https://www.suiteadeplus.com/documents/20121/39772/video-ayuda.png
preving.adeplus.mail.template.video.link=https://player.vimeo.com/video/625270610?h=b90d56d67e&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479
preving.adeplus.mail.template.icon.list=https://www.suiteadeplus.com/documents/20121/39772/icon_lista.png
preving.adeplus.mail.template.logo.footer.url=https://www.suiteadeplus.com/documents/20121/39772/Logotipo_ADEPLUS_blanco.png
preving.adeplus.mail.template.logo.facebook.url=https://www.suiteadeplus.com/documents/20121/39772/facebook_mail.png
preving.adeplus.mail.template.logo.twitter.url=https://www.suiteadeplus.com/documents/20121/39772/twitter_mail.png
preving.adeplus.mail.template.logo.youtube.url=https://www.suiteadeplus.com/documents/20121/39772/youtube_mail.png
preving.adeplus.mail.template.logo.linkedin.url=https://www.suiteadeplus.com/documents/20121/39772/linkedin_mail.png
# Canal Ético
preving.canal.etico.mail.template.logo.url=https://www.suiteadeplus.com/documents/20121/39772/logo_adeplus.jpg
preving.canal.etico.mail.template.background.url=https://www.suiteadeplus.com/documents/20121/39772/fondo_mail.jpg
preving.canal.etico.mail.template.video.url=https://www.suiteadeplus.com/documents/20121/39772/video-ayuda.png
preving.canal.etico.mail.template.icon.list=https://www.suiteadeplus.com/documents/20121/39772/icon_lista.png
preving.canal.etico.mail.template.logo.footer.url=https://www.suiteadeplus.com/documents/20121/39772/Logotipo_ADEPLUS_blanco.png
preving.canal.etico.mail.template.logo.facebook.url=https://www.suiteadeplus.com/documents/20121/39772/facebook_mail.png
preving.canal.etico.mail.template.logo.twitter.url=https://www.suiteadeplus.com/documents/20121/39772/twitter_mail.png
preving.canal.etico.mail.template.logo.youtube.url=https://www.suiteadeplus.com/documents/20121/39772/youtube_mail.png
preving.canal.etico.mail.template.logo.linkedin.url=https://www.suiteadeplus.com/documents/20121/39772/linkedin_mail.png