include-and-override=portal-developer.properties

include-and-override=portal-developer.properties

#
# MySQL
#
jdbc.default.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.default.url=jdbc:mysql://10.27.96.3:3306/control_horario?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false&serverTimezone=UTC&autoReconnect=true&useSSL=false
jdbc.default.username=control
jdbc.default.password=1o2s7UsY

#
# Set the properties used to create the Java Mail session. The property
# prefix "mail.session." will be removed before it is used to create the
# session object. These properties will only be read if the property
# "mail.session.jndi.name" is not set.
#
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_POP_NUMBER3__PERIOD_HOST
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_POP_NUMBER3__PERIOD_PASSWORD
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_POP_NUMBER3__PERIOD_PORT
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_POP_NUMBER3__PERIOD_USER
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_SMTP_PERIOD_AUTH
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_SMTP_PERIOD_HOST
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_SMTP_PERIOD_PASSWORD
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_SMTP_PERIOD_PORT
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_SMTP_PERIOD_STARTTLS_PERIOD_ENABLE
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_SMTP_PERIOD_USER
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_STORE_PERIOD_PROTOCOL
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_TRANSPORT_PERIOD_PROTOCOL
#
mail.session.mail=false
mail.session.mail.pop3.host=mail.preving.com
mail.session.mail.pop3.password=sSHMn231
mail.session.mail.pop3.port=110
mail.session.mail.pop3.user=no-reply@miregistrodehoras.com
mail.session.mail.smtp.auth=true
mail.session.mail.smtp.host=mail.preving.com
mail.session.mail.smtp.password=sSHMn231
mail.session.mail.smtp.port=465
mail.session.mail.smtp.starttls.enable=true
mail.session.mail.smtp.user=no-reply@miregistrodehoras.com
mail.session.mail.store.protocol=pop3
mail.session.mail.transport.protocol=smtps


admin.email.user.added.enabled=false
admin.email.user.added.subject=
admin.email.user.added.no.password.body=
admin.email.user.added.reset.password.body=

#
# Specify the number of minutes before a session expires. This value is
# always overridden by the value set in web.xml.
#
# Env: LIFERAY_SESSION_PERIOD_TIMEOUT
#
session.timeout=60

#
# Specify the number of minutes before a warning is sent to the user
# informing the user of the session expiration. Specify 0 to disable any
# warnings.
#
# Env: LIFERAY_SESSION_PERIOD_TIMEOUT_PERIOD_WARNING
#
session.timeout.warning=1

#
# Set the auto-extend mode to true to avoid having to ask the user whether
# to extend the session or not. Instead, it will be automatically extended.
# The purpose of this mode is to keep the session open as long as the user's
# browser is open with a portal page loaded. It is recommended to use this
# setting along with a smaller "session.timeout", such as 5 minutes, for
# better performance.
#
# Env: LIFERAY_SESSION_PERIOD_TIMEOUT_PERIOD_AUTO_PERIOD_EXTEND
#
session.timeout.auto.extend=true

#
# When the property "session.timeout.auto.extend" is set to true, set the
# number of seconds between when the extend process is launched and the
# actual expiration of the session.
#
# Env: LIFERAY_SESSION_PERIOD_TIMEOUT_PERIOD_AUTO_PERIOD_EXTEND_PERIOD_OFFSET
#
session.timeout.auto.extend.offset=10

#
# Set this to true if the user is redirected to the default page when the
# session expires.
#
# Env: LIFERAY_SESSION_PERIOD_TIMEOUT_PERIOD_REDIRECT_PERIOD_ON_PERIOD_EXPIRE
#
session.timeout.redirect.on.expire=true


##
## Default Logout Page
##

#
# Set the default logout page path for users relative to the server path.
# This is the page users are automatically redirected to after logging out.
# For example, if you want the default logout page to be
# http://localhost:8080/web/guest/logout, set this to /web/guest/logout. To
# activate this feature, set auth.forward.by.last.path to true. To customize
# the behavior, see com.liferay.portal.events.DefaultLogoutPageAction in the
# "logout.events.post" property above.
#
# Env: LIFERAY_DEFAULT_PERIOD_LOGOUT_PERIOD_PAGE_PERIOD_PATH
#
default.logout.page.path=
#default.logout.page.path=/web/guest/logout

#
# Env: LIFERAY_LOGOUT_PERIOD_EVENTS_PERIOD_POST
#
#logout.events.post=com.preving.liferay.portlet.login.redirect.action.KeycloakLoginPostAction
#logout.events.post=\
#    com.liferay.portal.events.LogoutPostAction,\ps
#    com.liferay.portal.events.DefaultLogoutPageAction
logout.events.post=com.preving.liferay.portlet.login.redirect.action.KeycloakLoginPostAction,com.liferay.portal.events.LogoutPostAction,com.liferay.portal.events.GarbageCollectorAction

#
# Set this to true if users are forwarded to the last visited path upon
# successful login. If set to false, users will be forwarded to their
# default layout page.
#
# Env: LIFERAY_AUTH_PERIOD_FORWARD_PERIOD_BY_PERIOD_LAST_PERIOD_PATH
#
auth.forward.by.last.path=true

#
# Configure email notification settings.
#
# Env: LIFERAY_ADMIN_PERIOD_EMAIL_PERIOD_FROM_PERIOD_ADDRESS
# Env: LIFERAY_ADMIN_PERIOD_EMAIL_PERIOD_FROM_PERIOD_NAME
#
admin.email.from.name=Administrador de Mi registro de horas
admin.email.from.address=no-reply@miregistrodehoras.com


#
# Configure email notification settings.
#
# Env: LIFERAY_ADMIN_PERIOD_EMAIL_PERIOD_FROM_PERIOD_ADDRESS
# Env: LIFERAY_ADMIN_PERIOD_EMAIL_PERIOD_FROM_PERIOD_NAME
#
admin.email.from.name=Preving Admin
admin.email.from.address=no-reply@miregistrodehoras.com

#
# Env: LIFERAY_ANNOUNCEMENTS_PERIOD_EMAIL_PERIOD_TO_PERIOD_ADDRESS
# Env: LIFERAY_ANNOUNCEMENTS_PERIOD_EMAIL_PERIOD_TO_PERIOD_NAME
#
announcements.email.to.name=Preving Admin
announcements.email.to.address=no-reply@miregistrodehoras.com


#
# Set this property to "ip" or "domain" for the redirect security method. If
# set to "domain", the portal will only redirect users to domains listed in
# the property "redirect.url.domain.allowed". If set to "ip", the portal
# will only redirect to domains whose IP address resolve to an IP address
# listed in the property "redirect.url.ip.allowed".
#
# Env: LIFERAY_REDIRECT_PERIOD_URL_PERIOD_SECURITY_PERIOD_MODE
#
redirect.url.security.mode=domain


#
# Input a list of comma delimited domains which the portal is allowed to
# redirect to. Input a blank list to allow any domain. Specifying a domain
# with a leading "*." allows redirects to subdomains.
#
# Env: LIFERAY_REDIRECT_PERIOD_URL_PERIOD_DOMAINS_PERIOD_ALLOWED
#
redirect.url.domains.allowed=miregistrodehoras.es,www.miregistrodehoras.es,miregistrodehoras.com,www.miregistrodehoras.com

#
# Input a list of comma delimited IPs which the portal is allowed to
# redirect to. Input a blank list to allow any IP. SERVER_IP will be
# replaced with the IP of the host server.
#
# Env: LIFERAY_REDIRECT_PERIOD_URL_PERIOD_IPS_PERIOD_ALLOWED
#
redirect.url.ips.allowed=\
    127.0.0.1,\
    10.132.0.4

#
# Set this to true to use the property "web.server.forward.host.header" to
# get the host. The property "web.server.host" must be set its default
# value.
#
web.server.forwarded.host.enabled=true

#
# Set this to true to use the property "web.server.forward.port.header" to
# get the port.
#
web.server.forwarded.port.enabled=true

#
# Set this to true to use the property "web.server.forward.protocol.header"
# to get the protocol. The property "web.server.protocol" must not have been
# overriden.
#
web.server.forwarded.protocol.enabled=true


#
# Specify the group id and the article id of the Journal article that will
# be displayed as the terms of use. The default text will be used if no
# Journal article is specified.
#
terms.of.use.journal.article.group.id=20123
terms.of.use.journal.article.id=44786
terms.of.use.journal.article.id.admin=44752


#
# The login field is prepopulated with the company's domain name if the
# login is unpopulated and user authentication is based on email addresses.
# Set this to false to disable the behavior.
#
company.login.prepopulate.domain=false

#
# Set this to true to enable reminder queries that are used to help reset a
# user's password.
#
users.reminder.queries.enabled=false
users.reminder.queries.custom.question.enabled=false

#
# Set this to false to enable users without a reminder query to reset their
# password.
#
users.reminder.queries.required=false

#
# The name of the roles created to use in Preving. The first one is for the
# user who created all the companies. The second one is the administrator of
# the company site, and the last one is the user.
#
preving.roles.preving.site.admin.name=Preving Administrator
preving.roles.company.admin.name=Preving Company Admin
preving.roles.company.site.admin.name=Preving Company Site Admin
preving.roles.company.site.user.name=Preving Company Site User


#
# The names of expando fields for Preving.
#
preving.expando.user.salary=salario
preving.expando.user.nif=nif
preving.expando.user.end.date=fechaBaja
preving.expando.user.work.center=centroTrabajo

#
# The name of "Procedencia".
#
preving.source.default=TOTALDAT;SOURCE1;SOURCE2;SOURCE3

