/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adeplus.liferay.portlet.suite.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ApplicationLicense service. Represents a row in the &quot;adeplus_ApplicationLicense&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adeplus.liferay.portlet.suite.manager.model.impl.ApplicationLicenseModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adeplus.liferay.portlet.suite.manager.model.impl.ApplicationLicenseImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ApplicationLicense
 * @generated
 */
@ProviderType
public interface ApplicationLicenseModel extends BaseModel<ApplicationLicense> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a application license model instance should use the {@link ApplicationLicense} interface instead.
	 */

	/**
	 * Returns the primary key of this application license.
	 *
	 * @return the primary key of this application license
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this application license.
	 *
	 * @param primaryKey the primary key of this application license
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the license ID of this application license.
	 *
	 * @return the license ID of this application license
	 */
	public long getLicenseId();

	/**
	 * Sets the license ID of this application license.
	 *
	 * @param licenseId the license ID of this application license
	 */
	public void setLicenseId(long licenseId);

	/**
	 * Returns the application ID of this application license.
	 *
	 * @return the application ID of this application license
	 */
	public long getApplicationId();

	/**
	 * Sets the application ID of this application license.
	 *
	 * @param applicationId the application ID of this application license
	 */
	public void setApplicationId(long applicationId);

	/**
	 * Returns the name of this application license.
	 *
	 * @return the name of this application license
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this application license.
	 *
	 * @param name the name of this application license
	 */
	public void setName(String name);

	/**
	 * Returns the permission role key of this application license.
	 *
	 * @return the permission role key of this application license
	 */
	@AutoEscape
	public String getPermissionRoleKey();

	/**
	 * Sets the permission role key of this application license.
	 *
	 * @param permissionRoleKey the permission role key of this application license
	 */
	public void setPermissionRoleKey(String permissionRoleKey);

	/**
	 * Returns the create date of this application license.
	 *
	 * @return the create date of this application license
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this application license.
	 *
	 * @param createDate the create date of this application license
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the delete date of this application license.
	 *
	 * @return the delete date of this application license
	 */
	public Date getDeleteDate();

	/**
	 * Sets the delete date of this application license.
	 *
	 * @param deleteDate the delete date of this application license
	 */
	public void setDeleteDate(Date deleteDate);

	/**
	 * Returns the modified date of this application license.
	 *
	 * @return the modified date of this application license
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this application license.
	 *
	 * @param modifiedDate the modified date of this application license
	 */
	public void setModifiedDate(Date modifiedDate);

}