/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adeplus.liferay.portlet.suite.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.LocalizedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Application service. Represents a row in the &quot;adeplus_Application&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adeplus.liferay.portlet.suite.manager.model.impl.ApplicationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adeplus.liferay.portlet.suite.manager.model.impl.ApplicationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Application
 * @generated
 */
@ProviderType
public interface ApplicationModel
	extends BaseModel<Application>, LocalizedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a application model instance should use the {@link Application} interface instead.
	 */

	/**
	 * Returns the primary key of this application.
	 *
	 * @return the primary key of this application
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this application.
	 *
	 * @param primaryKey the primary key of this application
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the application ID of this application.
	 *
	 * @return the application ID of this application
	 */
	public long getApplicationId();

	/**
	 * Sets the application ID of this application.
	 *
	 * @param applicationId the application ID of this application
	 */
	public void setApplicationId(long applicationId);

	/**
	 * Returns the name of this application.
	 *
	 * @return the name of this application
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this application.
	 *
	 * @param name the name of this application
	 */
	public void setName(String name);

	/**
	 * Returns the description of this application.
	 *
	 * @return the description of this application
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this application in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this application
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this application in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this application. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this application in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this application
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this application in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this application
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this application.
	 *
	 * @return the locales and localized descriptions of this application
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this application.
	 *
	 * @param description the description of this application
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this application in the language.
	 *
	 * @param description the localized description of this application
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this application in the language, and sets the default locale.
	 *
	 * @param description the localized description of this application
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(
		String description, Locale locale, Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this application from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this application
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this application from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this application
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale);

	/**
	 * Returns the url of this application.
	 *
	 * @return the url of this application
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this application.
	 *
	 * @param url the url of this application
	 */
	public void setUrl(String url);

	/**
	 * Returns the configuration of this application.
	 *
	 * @return the configuration of this application
	 */
	@AutoEscape
	public String getConfiguration();

	/**
	 * Sets the configuration of this application.
	 *
	 * @param configuration the configuration of this application
	 */
	public void setConfiguration(String configuration);

	/**
	 * Returns the roles of this application.
	 *
	 * @return the roles of this application
	 */
	@AutoEscape
	public String getRoles();

	/**
	 * Sets the roles of this application.
	 *
	 * @param roles the roles of this application
	 */
	public void setRoles(String roles);

	/**
	 * Returns the alias of this application.
	 *
	 * @return the alias of this application
	 */
	@AutoEscape
	public String getAlias();

	/**
	 * Sets the alias of this application.
	 *
	 * @param alias the alias of this application
	 */
	public void setAlias(String alias);

	/**
	 * Returns the keycloak_client of this application.
	 *
	 * @return the keycloak_client of this application
	 */
	@AutoEscape
	public String getKeycloak_client();

	/**
	 * Sets the keycloak_client of this application.
	 *
	 * @param keycloak_client the keycloak_client of this application
	 */
	public void setKeycloak_client(String keycloak_client);

	/**
	 * Returns the keycloak_secret of this application.
	 *
	 * @return the keycloak_secret of this application
	 */
	@AutoEscape
	public String getKeycloak_secret();

	/**
	 * Sets the keycloak_secret of this application.
	 *
	 * @param keycloak_secret the keycloak_secret of this application
	 */
	public void setKeycloak_secret(String keycloak_secret);

	/**
	 * Returns the logo of this application.
	 *
	 * @return the logo of this application
	 */
	public long getLogo();

	/**
	 * Sets the logo of this application.
	 *
	 * @param logo the logo of this application
	 */
	public void setLogo(long logo);

	/**
	 * Returns the order of this application.
	 *
	 * @return the order of this application
	 */
	public Integer getOrder();

	/**
	 * Sets the order of this application.
	 *
	 * @param order the order of this application
	 */
	public void setOrder(Integer order);

	/**
	 * Returns the limit admins of this application.
	 *
	 * @return the limit admins of this application
	 */
	public boolean getLimitAdmins();

	/**
	 * Returns <code>true</code> if this application is limit admins.
	 *
	 * @return <code>true</code> if this application is limit admins; <code>false</code> otherwise
	 */
	public boolean isLimitAdmins();

	/**
	 * Sets whether this application is limit admins.
	 *
	 * @param limitAdmins the limit admins of this application
	 */
	public void setLimitAdmins(boolean limitAdmins);

	/**
	 * Returns the limit users of this application.
	 *
	 * @return the limit users of this application
	 */
	public boolean getLimitUsers();

	/**
	 * Returns <code>true</code> if this application is limit users.
	 *
	 * @return <code>true</code> if this application is limit users; <code>false</code> otherwise
	 */
	public boolean isLimitUsers();

	/**
	 * Sets whether this application is limit users.
	 *
	 * @param limitUsers the limit users of this application
	 */
	public void setLimitUsers(boolean limitUsers);

	/**
	 * Returns the limit num admins of this application.
	 *
	 * @return the limit num admins of this application
	 */
	public long getLimitNumAdmins();

	/**
	 * Sets the limit num admins of this application.
	 *
	 * @param limitNumAdmins the limit num admins of this application
	 */
	public void setLimitNumAdmins(long limitNumAdmins);

	/**
	 * Returns the limit num users of this application.
	 *
	 * @return the limit num users of this application
	 */
	public long getLimitNumUsers();

	/**
	 * Sets the limit num users of this application.
	 *
	 * @param limitNumUsers the limit num users of this application
	 */
	public void setLimitNumUsers(long limitNumUsers);

	/**
	 * Returns the create date of this application.
	 *
	 * @return the create date of this application
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this application.
	 *
	 * @param createDate the create date of this application
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this application.
	 *
	 * @return the modified date of this application
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this application.
	 *
	 * @param modifiedDate the modified date of this application
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

}