/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adeplus.liferay.portlet.suite.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AuditadoDataApi service. Represents a row in the &quot;adeplus_AuditadoDataApi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adeplus.liferay.portlet.suite.manager.model.impl.AuditadoDataApiModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adeplus.liferay.portlet.suite.manager.model.impl.AuditadoDataApiImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AuditadoDataApi
 * @generated
 */
@ProviderType
public interface AuditadoDataApiModel extends BaseModel<AuditadoDataApi> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a auditado data api model instance should use the {@link AuditadoDataApi} interface instead.
	 */

	/**
	 * Returns the primary key of this auditado data api.
	 *
	 * @return the primary key of this auditado data api
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this auditado data api.
	 *
	 * @param primaryKey the primary key of this auditado data api
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id data temporal of this auditado data api.
	 *
	 * @return the id data temporal of this auditado data api
	 */
	public long getIdDataTemporal();

	/**
	 * Sets the id data temporal of this auditado data api.
	 *
	 * @param idDataTemporal the id data temporal of this auditado data api
	 */
	public void setIdDataTemporal(long idDataTemporal);

	/**
	 * Returns the mensaje of this auditado data api.
	 *
	 * @return the mensaje of this auditado data api
	 */
	@AutoEscape
	public String getMensaje();

	/**
	 * Sets the mensaje of this auditado data api.
	 *
	 * @param mensaje the mensaje of this auditado data api
	 */
	public void setMensaje(String mensaje);

	/**
	 * Returns the procesado date of this auditado data api.
	 *
	 * @return the procesado date of this auditado data api
	 */
	public Date getProcesadoDate();

	/**
	 * Sets the procesado date of this auditado data api.
	 *
	 * @param procesadoDate the procesado date of this auditado data api
	 */
	public void setProcesadoDate(Date procesadoDate);

	/**
	 * Returns the procesado of this auditado data api.
	 *
	 * @return the procesado of this auditado data api
	 */
	public Integer getProcesado();

	/**
	 * Sets the procesado of this auditado data api.
	 *
	 * @param procesado the procesado of this auditado data api
	 */
	public void setProcesado(Integer procesado);

	/**
	 * Returns the evento of this auditado data api.
	 *
	 * @return the evento of this auditado data api
	 */
	@AutoEscape
	public String getEvento();

	/**
	 * Sets the evento of this auditado data api.
	 *
	 * @param evento the evento of this auditado data api
	 */
	public void setEvento(String evento);

	/**
	 * Returns the cif of this auditado data api.
	 *
	 * @return the cif of this auditado data api
	 */
	@AutoEscape
	public String getCif();

	/**
	 * Sets the cif of this auditado data api.
	 *
	 * @param cif the cif of this auditado data api
	 */
	public void setCif(String cif);

	/**
	 * Returns the id client of this auditado data api.
	 *
	 * @return the id client of this auditado data api
	 */
	public long getIdClient();

	/**
	 * Sets the id client of this auditado data api.
	 *
	 * @param idClient the id client of this auditado data api
	 */
	public void setIdClient(long idClient);

	/**
	 * Returns the id contract of this auditado data api.
	 *
	 * @return the id contract of this auditado data api
	 */
	public long getIdContract();

	/**
	 * Sets the id contract of this auditado data api.
	 *
	 * @param idContract the id contract of this auditado data api
	 */
	public void setIdContract(long idContract);

	/**
	 * Returns the app of this auditado data api.
	 *
	 * @return the app of this auditado data api
	 */
	@AutoEscape
	public String getApp();

	/**
	 * Sets the app of this auditado data api.
	 *
	 * @param app the app of this auditado data api
	 */
	public void setApp(String app);

	/**
	 * Returns the change state date of this auditado data api.
	 *
	 * @return the change state date of this auditado data api
	 */
	public Date getChangeStateDate();

	/**
	 * Sets the change state date of this auditado data api.
	 *
	 * @param changeStateDate the change state date of this auditado data api
	 */
	public void setChangeStateDate(Date changeStateDate);

	/**
	 * Returns the state of this auditado data api.
	 *
	 * @return the state of this auditado data api
	 */
	public boolean getState();

	/**
	 * Returns <code>true</code> if this auditado data api is state.
	 *
	 * @return <code>true</code> if this auditado data api is state; <code>false</code> otherwise
	 */
	public boolean isState();

	/**
	 * Sets whether this auditado data api is state.
	 *
	 * @param state the state of this auditado data api
	 */
	public void setState(boolean state);

	/**
	 * Returns the user ID change state of this auditado data api.
	 *
	 * @return the user ID change state of this auditado data api
	 */
	public long getUserIdChangeState();

	/**
	 * Sets the user ID change state of this auditado data api.
	 *
	 * @param userIdChangeState the user ID change state of this auditado data api
	 */
	public void setUserIdChangeState(long userIdChangeState);

}