/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adeplus.liferay.portlet.suite.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Audit service. Represents a row in the &quot;adeplus_Audit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adeplus.liferay.portlet.suite.manager.model.impl.AuditModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adeplus.liferay.portlet.suite.manager.model.impl.AuditImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Audit
 * @generated
 */
@ProviderType
public interface AuditModel extends BaseModel<Audit>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a audit model instance should use the {@link Audit} interface instead.
	 */

	/**
	 * Returns the primary key of this audit.
	 *
	 * @return the primary key of this audit
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this audit.
	 *
	 * @param primaryKey the primary key of this audit
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the audit ID of this audit.
	 *
	 * @return the audit ID of this audit
	 */
	public long getAuditId();

	/**
	 * Sets the audit ID of this audit.
	 *
	 * @param auditId the audit ID of this audit
	 */
	public void setAuditId(long auditId);

	/**
	 * Returns the company ID of this audit.
	 *
	 * @return the company ID of this audit
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this audit.
	 *
	 * @param companyId the company ID of this audit
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this audit.
	 *
	 * @return the group ID of this audit
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this audit.
	 *
	 * @param groupId the group ID of this audit
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this audit.
	 *
	 * @return the user ID of this audit
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this audit.
	 *
	 * @param userId the user ID of this audit
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this audit.
	 *
	 * @return the user uuid of this audit
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this audit.
	 *
	 * @param userUuid the user uuid of this audit
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the action of this audit.
	 *
	 * @return the action of this audit
	 */
	@AutoEscape
	public String getAction();

	/**
	 * Sets the action of this audit.
	 *
	 * @param action the action of this audit
	 */
	public void setAction(String action);

	/**
	 * Returns the description of this audit.
	 *
	 * @return the description of this audit
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this audit.
	 *
	 * @param description the description of this audit
	 */
	public void setDescription(String description);

	/**
	 * Returns the date of this audit.
	 *
	 * @return the date of this audit
	 */
	public Date getDate();

	/**
	 * Sets the date of this audit.
	 *
	 * @param date the date of this audit
	 */
	public void setDate(Date date);

}