/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adeplus.liferay.portlet.suite.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.LocalizedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CompClientApplication service. Represents a row in the &quot;adeplus_CompClientApplication&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adeplus.liferay.portlet.suite.manager.model.impl.CompClientApplicationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adeplus.liferay.portlet.suite.manager.model.impl.CompClientApplicationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CompClientApplication
 * @generated
 */
@ProviderType
public interface CompClientApplicationModel
	extends BaseModel<CompClientApplication>, LocalizedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a comp client application model instance should use the {@link CompClientApplication} interface instead.
	 */

	/**
	 * Returns the primary key of this comp client application.
	 *
	 * @return the primary key of this comp client application
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this comp client application.
	 *
	 * @param primaryKey the primary key of this comp client application
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the empresa ID of this comp client application.
	 *
	 * @return the empresa ID of this comp client application
	 */
	public long getEmpresaId();

	/**
	 * Sets the empresa ID of this comp client application.
	 *
	 * @param empresaId the empresa ID of this comp client application
	 */
	public void setEmpresaId(long empresaId);

	/**
	 * Returns the cif of this comp client application.
	 *
	 * @return the cif of this comp client application
	 */
	@AutoEscape
	public String getCif();

	/**
	 * Sets the cif of this comp client application.
	 *
	 * @param cif the cif of this comp client application
	 */
	public void setCif(String cif);

	/**
	 * Returns the comp ID of this comp client application.
	 *
	 * @return the comp ID of this comp client application
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this comp client application.
	 *
	 * @param compId the comp ID of this comp client application
	 */
	public void setCompId(long compId);

	/**
	 * Returns the client ID of this comp client application.
	 *
	 * @return the client ID of this comp client application
	 */
	public long getClientId();

	/**
	 * Sets the client ID of this comp client application.
	 *
	 * @param clientId the client ID of this comp client application
	 */
	public void setClientId(long clientId);

	/**
	 * Returns the contract ID of this comp client application.
	 *
	 * @return the contract ID of this comp client application
	 */
	public long getContractId();

	/**
	 * Sets the contract ID of this comp client application.
	 *
	 * @param contractId the contract ID of this comp client application
	 */
	public void setContractId(long contractId);

	/**
	 * Returns the application ID of this comp client application.
	 *
	 * @return the application ID of this comp client application
	 */
	@AutoEscape
	public String getApplicationId();

	/**
	 * Sets the application ID of this comp client application.
	 *
	 * @param applicationId the application ID of this comp client application
	 */
	public void setApplicationId(String applicationId);

	/**
	 * Returns the name of this comp client application.
	 *
	 * @return the name of this comp client application
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this comp client application.
	 *
	 * @param name the name of this comp client application
	 */
	public void setName(String name);

	/**
	 * Returns the description of this comp client application.
	 *
	 * @return the description of this comp client application
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this comp client application.
	 *
	 * @param description the description of this comp client application
	 */
	public void setDescription(String description);

	/**
	 * Returns the observations of this comp client application.
	 *
	 * @return the observations of this comp client application
	 */
	public String getObservations();

	/**
	 * Returns the localized observations of this comp client application in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized observations of this comp client application
	 */
	@AutoEscape
	public String getObservations(Locale locale);

	/**
	 * Returns the localized observations of this comp client application in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized observations of this comp client application. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getObservations(Locale locale, boolean useDefault);

	/**
	 * Returns the localized observations of this comp client application in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized observations of this comp client application
	 */
	@AutoEscape
	public String getObservations(String languageId);

	/**
	 * Returns the localized observations of this comp client application in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized observations of this comp client application
	 */
	@AutoEscape
	public String getObservations(String languageId, boolean useDefault);

	@AutoEscape
	public String getObservationsCurrentLanguageId();

	@AutoEscape
	public String getObservationsCurrentValue();

	/**
	 * Returns a map of the locales and localized observationses of this comp client application.
	 *
	 * @return the locales and localized observationses of this comp client application
	 */
	public Map<Locale, String> getObservationsMap();

	/**
	 * Sets the observations of this comp client application.
	 *
	 * @param observations the observations of this comp client application
	 */
	public void setObservations(String observations);

	/**
	 * Sets the localized observations of this comp client application in the language.
	 *
	 * @param observations the localized observations of this comp client application
	 * @param locale the locale of the language
	 */
	public void setObservations(String observations, Locale locale);

	/**
	 * Sets the localized observations of this comp client application in the language, and sets the default locale.
	 *
	 * @param observations the localized observations of this comp client application
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setObservations(
		String observations, Locale locale, Locale defaultLocale);

	public void setObservationsCurrentLanguageId(String languageId);

	/**
	 * Sets the localized observationses of this comp client application from the map of locales and localized observationses.
	 *
	 * @param observationsMap the locales and localized observationses of this comp client application
	 */
	public void setObservationsMap(Map<Locale, String> observationsMap);

	/**
	 * Sets the localized observationses of this comp client application from the map of locales and localized observationses, and sets the default locale.
	 *
	 * @param observationsMap the locales and localized observationses of this comp client application
	 * @param defaultLocale the default locale
	 */
	public void setObservationsMap(
		Map<Locale, String> observationsMap, Locale defaultLocale);

	/**
	 * Returns the id estado of this comp client application.
	 *
	 * @return the id estado of this comp client application
	 */
	@AutoEscape
	public String getIdEstado();

	/**
	 * Sets the id estado of this comp client application.
	 *
	 * @param idEstado the id estado of this comp client application
	 */
	public void setIdEstado(String idEstado);

	/**
	 * Returns the logo of this comp client application.
	 *
	 * @return the logo of this comp client application
	 */
	public long getLogo();

	/**
	 * Sets the logo of this comp client application.
	 *
	 * @param logo the logo of this comp client application
	 */
	public void setLogo(long logo);

	/**
	 * Returns the start date of this comp client application.
	 *
	 * @return the start date of this comp client application
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this comp client application.
	 *
	 * @param startDate the start date of this comp client application
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the delete date of this comp client application.
	 *
	 * @return the delete date of this comp client application
	 */
	public Date getDeleteDate();

	/**
	 * Sets the delete date of this comp client application.
	 *
	 * @param deleteDate the delete date of this comp client application
	 */
	public void setDeleteDate(Date deleteDate);

	/**
	 * Returns the create date of this comp client application.
	 *
	 * @return the create date of this comp client application
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this comp client application.
	 *
	 * @param createDate the create date of this comp client application
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this comp client application.
	 *
	 * @return the modified date of this comp client application
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this comp client application.
	 *
	 * @param modifiedDate the modified date of this comp client application
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

}