/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adeplus.liferay.portlet.suite.manager.model;

import com.adeplus.liferay.portlet.suite.manager.service.persistence.CompApplicationPK;

import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CompApplication service. Represents a row in the &quot;adeplus_CompApplication&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adeplus.liferay.portlet.suite.manager.model.impl.CompApplicationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adeplus.liferay.portlet.suite.manager.model.impl.CompApplicationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CompApplication
 * @generated
 */
@ProviderType
public interface CompApplicationModel extends BaseModel<CompApplication> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a comp application model instance should use the {@link CompApplication} interface instead.
	 */

	/**
	 * Returns the primary key of this comp application.
	 *
	 * @return the primary key of this comp application
	 */
	public CompApplicationPK getPrimaryKey();

	/**
	 * Sets the primary key of this comp application.
	 *
	 * @param primaryKey the primary key of this comp application
	 */
	public void setPrimaryKey(CompApplicationPK primaryKey);

	/**
	 * Returns the comp ID of this comp application.
	 *
	 * @return the comp ID of this comp application
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this comp application.
	 *
	 * @param compId the comp ID of this comp application
	 */
	public void setCompId(long compId);

	/**
	 * Returns the application ID of this comp application.
	 *
	 * @return the application ID of this comp application
	 */
	public long getApplicationId();

	/**
	 * Sets the application ID of this comp application.
	 *
	 * @param applicationId the application ID of this comp application
	 */
	public void setApplicationId(long applicationId);

	/**
	 * Returns the license ID of this comp application.
	 *
	 * @return the license ID of this comp application
	 */
	public long getLicenseId();

	/**
	 * Sets the license ID of this comp application.
	 *
	 * @param licenseId the license ID of this comp application
	 */
	public void setLicenseId(long licenseId);

	/**
	 * Returns the create date of this comp application.
	 *
	 * @return the create date of this comp application
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this comp application.
	 *
	 * @param createDate the create date of this comp application
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the delete date of this comp application.
	 *
	 * @return the delete date of this comp application
	 */
	public Date getDeleteDate();

	/**
	 * Sets the delete date of this comp application.
	 *
	 * @param deleteDate the delete date of this comp application
	 */
	public void setDeleteDate(Date deleteDate);

	/**
	 * Returns the modified date of this comp application.
	 *
	 * @return the modified date of this comp application
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this comp application.
	 *
	 * @param modifiedDate the modified date of this comp application
	 */
	public void setModifiedDate(Date modifiedDate);

}