/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adeplus.liferay.portlet.suite.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Role service. Represents a row in the &quot;adeplus_Role&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adeplus.liferay.portlet.suite.manager.model.impl.RoleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adeplus.liferay.portlet.suite.manager.model.impl.RoleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Role
 * @generated
 */
@ProviderType
public interface RoleModel extends BaseModel<Role> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a role model instance should use the {@link Role} interface instead.
	 */

	/**
	 * Returns the primary key of this role.
	 *
	 * @return the primary key of this role
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this role.
	 *
	 * @param primaryKey the primary key of this role
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the role ID of this role.
	 *
	 * @return the role ID of this role
	 */
	public long getRoleId();

	/**
	 * Sets the role ID of this role.
	 *
	 * @param roleId the role ID of this role
	 */
	public void setRoleId(long roleId);

	/**
	 * Returns the application ID of this role.
	 *
	 * @return the application ID of this role
	 */
	public long getApplicationId();

	/**
	 * Sets the application ID of this role.
	 *
	 * @param applicationId the application ID of this role
	 */
	public void setApplicationId(long applicationId);

	/**
	 * Returns the name of this role.
	 *
	 * @return the name of this role
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this role.
	 *
	 * @param name the name of this role
	 */
	public void setName(String name);

	/**
	 * Returns the alias of this role.
	 *
	 * @return the alias of this role
	 */
	@AutoEscape
	public String getAlias();

	/**
	 * Sets the alias of this role.
	 *
	 * @param alias the alias of this role
	 */
	public void setAlias(String alias);

	/**
	 * Returns the create date of this role.
	 *
	 * @return the create date of this role
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this role.
	 *
	 * @param createDate the create date of this role
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this role.
	 *
	 * @return the modified date of this role
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this role.
	 *
	 * @param modifiedDate the modified date of this role
	 */
	public void setModifiedDate(Date modifiedDate);

}