/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adeplus.liferay.portlet.suite.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TemporalDataApi service. Represents a row in the &quot;adeplus_TemporalDataApi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adeplus.liferay.portlet.suite.manager.model.impl.TemporalDataApiModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adeplus.liferay.portlet.suite.manager.model.impl.TemporalDataApiImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TemporalDataApi
 * @generated
 */
@ProviderType
public interface TemporalDataApiModel extends BaseModel<TemporalDataApi> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a temporal data api model instance should use the {@link TemporalDataApi} interface instead.
	 */

	/**
	 * Returns the primary key of this temporal data api.
	 *
	 * @return the primary key of this temporal data api
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this temporal data api.
	 *
	 * @param primaryKey the primary key of this temporal data api
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id data temporal of this temporal data api.
	 *
	 * @return the id data temporal of this temporal data api
	 */
	public long getIdDataTemporal();

	/**
	 * Sets the id data temporal of this temporal data api.
	 *
	 * @param idDataTemporal the id data temporal of this temporal data api
	 */
	public void setIdDataTemporal(long idDataTemporal);

	/**
	 * Returns the type event of this temporal data api.
	 *
	 * @return the type event of this temporal data api
	 */
	@AutoEscape
	public String getTypeEvent();

	/**
	 * Sets the type event of this temporal data api.
	 *
	 * @param typeEvent the type event of this temporal data api
	 */
	public void setTypeEvent(String typeEvent);

	/**
	 * Returns the data api empresa of this temporal data api.
	 *
	 * @return the data api empresa of this temporal data api
	 */
	@AutoEscape
	public String getDataApiEmpresa();

	/**
	 * Sets the data api empresa of this temporal data api.
	 *
	 * @param dataApiEmpresa the data api empresa of this temporal data api
	 */
	public void setDataApiEmpresa(String dataApiEmpresa);

	/**
	 * Returns the data api applicaciones of this temporal data api.
	 *
	 * @return the data api applicaciones of this temporal data api
	 */
	@AutoEscape
	public String getDataApiApplicaciones();

	/**
	 * Sets the data api applicaciones of this temporal data api.
	 *
	 * @param dataApiApplicaciones the data api applicaciones of this temporal data api
	 */
	public void setDataApiApplicaciones(String dataApiApplicaciones);

	/**
	 * Returns the data api usuarios of this temporal data api.
	 *
	 * @return the data api usuarios of this temporal data api
	 */
	@AutoEscape
	public String getDataApiUsuarios();

	/**
	 * Sets the data api usuarios of this temporal data api.
	 *
	 * @param dataApiUsuarios the data api usuarios of this temporal data api
	 */
	public void setDataApiUsuarios(String dataApiUsuarios);

	/**
	 * Returns the procesado of this temporal data api.
	 *
	 * @return the procesado of this temporal data api
	 */
	public Integer getProcesado();

	/**
	 * Sets the procesado of this temporal data api.
	 *
	 * @param procesado the procesado of this temporal data api
	 */
	public void setProcesado(Integer procesado);

	/**
	 * Returns the create date of this temporal data api.
	 *
	 * @return the create date of this temporal data api
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this temporal data api.
	 *
	 * @param createDate the create date of this temporal data api
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the procesado date of this temporal data api.
	 *
	 * @return the procesado date of this temporal data api
	 */
	public Date getProcesadoDate();

	/**
	 * Sets the procesado date of this temporal data api.
	 *
	 * @param procesadoDate the procesado date of this temporal data api
	 */
	public void setProcesadoDate(Date procesadoDate);

}