/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adeplus.liferay.portlet.suite.manager.model;

import com.adeplus.liferay.portlet.suite.manager.service.persistence.UserApplicationClientPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserApplicationClient service. Represents a row in the &quot;adeplus_UserApplicationClient&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adeplus.liferay.portlet.suite.manager.model.impl.UserApplicationClientModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adeplus.liferay.portlet.suite.manager.model.impl.UserApplicationClientImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserApplicationClient
 * @generated
 */
@ProviderType
public interface UserApplicationClientModel
	extends BaseModel<UserApplicationClient> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user application client model instance should use the {@link UserApplicationClient} interface instead.
	 */

	/**
	 * Returns the primary key of this user application client.
	 *
	 * @return the primary key of this user application client
	 */
	public UserApplicationClientPK getPrimaryKey();

	/**
	 * Sets the primary key of this user application client.
	 *
	 * @param primaryKey the primary key of this user application client
	 */
	public void setPrimaryKey(UserApplicationClientPK primaryKey);

	/**
	 * Returns the empresa ID of this user application client.
	 *
	 * @return the empresa ID of this user application client
	 */
	public long getEmpresaId();

	/**
	 * Sets the empresa ID of this user application client.
	 *
	 * @param empresaId the empresa ID of this user application client
	 */
	public void setEmpresaId(long empresaId);

	/**
	 * Returns the user ID of this user application client.
	 *
	 * @return the user ID of this user application client
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user application client.
	 *
	 * @param userId the user ID of this user application client
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user application client.
	 *
	 * @return the user uuid of this user application client
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user application client.
	 *
	 * @param userUuid the user uuid of this user application client
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the comp ID of this user application client.
	 *
	 * @return the comp ID of this user application client
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this user application client.
	 *
	 * @param compId the comp ID of this user application client
	 */
	public void setCompId(long compId);

	/**
	 * Returns the client ID of this user application client.
	 *
	 * @return the client ID of this user application client
	 */
	public long getClientId();

	/**
	 * Sets the client ID of this user application client.
	 *
	 * @param clientId the client ID of this user application client
	 */
	public void setClientId(long clientId);

	/**
	 * Returns the contract ID of this user application client.
	 *
	 * @return the contract ID of this user application client
	 */
	public long getContractId();

	/**
	 * Sets the contract ID of this user application client.
	 *
	 * @param contractId the contract ID of this user application client
	 */
	public void setContractId(long contractId);

	/**
	 * Returns the application ID of this user application client.
	 *
	 * @return the application ID of this user application client
	 */
	@AutoEscape
	public String getApplicationId();

	/**
	 * Sets the application ID of this user application client.
	 *
	 * @param applicationId the application ID of this user application client
	 */
	public void setApplicationId(String applicationId);

	/**
	 * Returns the admin of this user application client.
	 *
	 * @return the admin of this user application client
	 */
	public boolean getAdmin();

	/**
	 * Returns <code>true</code> if this user application client is admin.
	 *
	 * @return <code>true</code> if this user application client is admin; <code>false</code> otherwise
	 */
	public boolean isAdmin();

	/**
	 * Sets whether this user application client is admin.
	 *
	 * @param admin the admin of this user application client
	 */
	public void setAdmin(boolean admin);

	/**
	 * Returns the create date of this user application client.
	 *
	 * @return the create date of this user application client
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this user application client.
	 *
	 * @param createDate the create date of this user application client
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the delete date of this user application client.
	 *
	 * @return the delete date of this user application client
	 */
	public Date getDeleteDate();

	/**
	 * Sets the delete date of this user application client.
	 *
	 * @param deleteDate the delete date of this user application client
	 */
	public void setDeleteDate(Date deleteDate);

	/**
	 * Returns the modified date of this user application client.
	 *
	 * @return the modified date of this user application client
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user application client.
	 *
	 * @param modifiedDate the modified date of this user application client
	 */
	public void setModifiedDate(Date modifiedDate);

}