/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adeplus.liferay.portlet.suite.manager.model;

import com.adeplus.liferay.portlet.suite.manager.service.persistence.UserCompanyClientPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserCompanyClient service. Represents a row in the &quot;adeplus_UserCompanyClient&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adeplus.liferay.portlet.suite.manager.model.impl.UserCompanyClientModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adeplus.liferay.portlet.suite.manager.model.impl.UserCompanyClientImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserCompanyClient
 * @generated
 */
@ProviderType
public interface UserCompanyClientModel extends BaseModel<UserCompanyClient> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user company client model instance should use the {@link UserCompanyClient} interface instead.
	 */

	/**
	 * Returns the primary key of this user company client.
	 *
	 * @return the primary key of this user company client
	 */
	public UserCompanyClientPK getPrimaryKey();

	/**
	 * Sets the primary key of this user company client.
	 *
	 * @param primaryKey the primary key of this user company client
	 */
	public void setPrimaryKey(UserCompanyClientPK primaryKey);

	/**
	 * Returns the user ID of this user company client.
	 *
	 * @return the user ID of this user company client
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user company client.
	 *
	 * @param userId the user ID of this user company client
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user company client.
	 *
	 * @return the user uuid of this user company client
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user company client.
	 *
	 * @param userUuid the user uuid of this user company client
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the empresa ID of this user company client.
	 *
	 * @return the empresa ID of this user company client
	 */
	public long getEmpresaId();

	/**
	 * Sets the empresa ID of this user company client.
	 *
	 * @param empresaId the empresa ID of this user company client
	 */
	public void setEmpresaId(long empresaId);

	/**
	 * Returns the comp ID of this user company client.
	 *
	 * @return the comp ID of this user company client
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this user company client.
	 *
	 * @param compId the comp ID of this user company client
	 */
	public void setCompId(long compId);

	/**
	 * Returns the name of this user company client.
	 *
	 * @return the name of this user company client
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this user company client.
	 *
	 * @param name the name of this user company client
	 */
	public void setName(String name);

	/**
	 * Returns the last name of this user company client.
	 *
	 * @return the last name of this user company client
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this user company client.
	 *
	 * @param lastName the last name of this user company client
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the nif of this user company client.
	 *
	 * @return the nif of this user company client
	 */
	@AutoEscape
	public String getNif();

	/**
	 * Sets the nif of this user company client.
	 *
	 * @param nif the nif of this user company client
	 */
	public void setNif(String nif);

	/**
	 * Returns the email of this user company client.
	 *
	 * @return the email of this user company client
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this user company client.
	 *
	 * @param email the email of this user company client
	 */
	public void setEmail(String email);

	/**
	 * Returns the phone of this user company client.
	 *
	 * @return the phone of this user company client
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this user company client.
	 *
	 * @param phone the phone of this user company client
	 */
	public void setPhone(String phone);

	/**
	 * Returns the admin of this user company client.
	 *
	 * @return the admin of this user company client
	 */
	public boolean getAdmin();

	/**
	 * Returns <code>true</code> if this user company client is admin.
	 *
	 * @return <code>true</code> if this user company client is admin; <code>false</code> otherwise
	 */
	public boolean isAdmin();

	/**
	 * Sets whether this user company client is admin.
	 *
	 * @param admin the admin of this user company client
	 */
	public void setAdmin(boolean admin);

	/**
	 * Returns the default user comp of this user company client.
	 *
	 * @return the default user comp of this user company client
	 */
	public boolean getDefaultUserComp();

	/**
	 * Returns <code>true</code> if this user company client is default user comp.
	 *
	 * @return <code>true</code> if this user company client is default user comp; <code>false</code> otherwise
	 */
	public boolean isDefaultUserComp();

	/**
	 * Sets whether this user company client is default user comp.
	 *
	 * @param defaultUserComp the default user comp of this user company client
	 */
	public void setDefaultUserComp(boolean defaultUserComp);

	/**
	 * Returns the default client ID of this user company client.
	 *
	 * @return the default client ID of this user company client
	 */
	public long getDefaultClientId();

	/**
	 * Sets the default client ID of this user company client.
	 *
	 * @param defaultClientId the default client ID of this user company client
	 */
	public void setDefaultClientId(long defaultClientId);

	/**
	 * Returns the default contract ID of this user company client.
	 *
	 * @return the default contract ID of this user company client
	 */
	public long getDefaultContractId();

	/**
	 * Sets the default contract ID of this user company client.
	 *
	 * @param defaultContractId the default contract ID of this user company client
	 */
	public void setDefaultContractId(long defaultContractId);

	/**
	 * Returns the default empresa ID of this user company client.
	 *
	 * @return the default empresa ID of this user company client
	 */
	public long getDefaultEmpresaId();

	/**
	 * Sets the default empresa ID of this user company client.
	 *
	 * @param defaultEmpresaId the default empresa ID of this user company client
	 */
	public void setDefaultEmpresaId(long defaultEmpresaId);

	/**
	 * Returns the user end date of this user company client.
	 *
	 * @return the user end date of this user company client
	 */
	public Date getUserEndDate();

	/**
	 * Sets the user end date of this user company client.
	 *
	 * @param userEndDate the user end date of this user company client
	 */
	public void setUserEndDate(Date userEndDate);

	/**
	 * Returns the create date of this user company client.
	 *
	 * @return the create date of this user company client
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this user company client.
	 *
	 * @param createDate the create date of this user company client
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this user company client.
	 *
	 * @return the modified date of this user company client
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user company client.
	 *
	 * @param modifiedDate the modified date of this user company client
	 */
	public void setModifiedDate(Date modifiedDate);

}