/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adeplus.liferay.portlet.suite.manager.model;

import com.adeplus.liferay.portlet.suite.manager.service.persistence.UserApplicationPK;

import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserApplication service. Represents a row in the &quot;adeplus_UserApplication&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adeplus.liferay.portlet.suite.manager.model.impl.UserApplicationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adeplus.liferay.portlet.suite.manager.model.impl.UserApplicationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserApplication
 * @generated
 */
@ProviderType
public interface UserApplicationModel extends BaseModel<UserApplication> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user application model instance should use the {@link UserApplication} interface instead.
	 */

	/**
	 * Returns the primary key of this user application.
	 *
	 * @return the primary key of this user application
	 */
	public UserApplicationPK getPrimaryKey();

	/**
	 * Sets the primary key of this user application.
	 *
	 * @param primaryKey the primary key of this user application
	 */
	public void setPrimaryKey(UserApplicationPK primaryKey);

	/**
	 * Returns the user ID of this user application.
	 *
	 * @return the user ID of this user application
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user application.
	 *
	 * @param userId the user ID of this user application
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user application.
	 *
	 * @return the user uuid of this user application
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user application.
	 *
	 * @param userUuid the user uuid of this user application
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the comp ID of this user application.
	 *
	 * @return the comp ID of this user application
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this user application.
	 *
	 * @param compId the comp ID of this user application
	 */
	public void setCompId(long compId);

	/**
	 * Returns the application ID of this user application.
	 *
	 * @return the application ID of this user application
	 */
	public long getApplicationId();

	/**
	 * Sets the application ID of this user application.
	 *
	 * @param applicationId the application ID of this user application
	 */
	public void setApplicationId(long applicationId);

	/**
	 * Returns the admin of this user application.
	 *
	 * @return the admin of this user application
	 */
	public boolean getAdmin();

	/**
	 * Returns <code>true</code> if this user application is admin.
	 *
	 * @return <code>true</code> if this user application is admin; <code>false</code> otherwise
	 */
	public boolean isAdmin();

	/**
	 * Sets whether this user application is admin.
	 *
	 * @param admin the admin of this user application
	 */
	public void setAdmin(boolean admin);

	/**
	 * Returns the create date of this user application.
	 *
	 * @return the create date of this user application
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this user application.
	 *
	 * @param createDate the create date of this user application
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the delete date of this user application.
	 *
	 * @return the delete date of this user application
	 */
	public Date getDeleteDate();

	/**
	 * Sets the delete date of this user application.
	 *
	 * @param deleteDate the delete date of this user application
	 */
	public void setDeleteDate(Date deleteDate);

	/**
	 * Returns the modified date of this user application.
	 *
	 * @return the modified date of this user application
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user application.
	 *
	 * @param modifiedDate the modified date of this user application
	 */
	public void setModifiedDate(Date modifiedDate);

}