/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adeplus.liferay.portlet.suite.manager.model;

import com.adeplus.liferay.portlet.suite.manager.service.persistence.UserRolePK;

import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserRole service. Represents a row in the &quot;adeplus_UserRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adeplus.liferay.portlet.suite.manager.model.impl.UserRoleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adeplus.liferay.portlet.suite.manager.model.impl.UserRoleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserRole
 * @generated
 */
@ProviderType
public interface UserRoleModel extends BaseModel<UserRole> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user role model instance should use the {@link UserRole} interface instead.
	 */

	/**
	 * Returns the primary key of this user role.
	 *
	 * @return the primary key of this user role
	 */
	public UserRolePK getPrimaryKey();

	/**
	 * Sets the primary key of this user role.
	 *
	 * @param primaryKey the primary key of this user role
	 */
	public void setPrimaryKey(UserRolePK primaryKey);

	/**
	 * Returns the user ID of this user role.
	 *
	 * @return the user ID of this user role
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user role.
	 *
	 * @param userId the user ID of this user role
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user role.
	 *
	 * @return the user uuid of this user role
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user role.
	 *
	 * @param userUuid the user uuid of this user role
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the comp ID of this user role.
	 *
	 * @return the comp ID of this user role
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this user role.
	 *
	 * @param compId the comp ID of this user role
	 */
	public void setCompId(long compId);

	/**
	 * Returns the role ID of this user role.
	 *
	 * @return the role ID of this user role
	 */
	public long getRoleId();

	/**
	 * Sets the role ID of this user role.
	 *
	 * @param roleId the role ID of this user role
	 */
	public void setRoleId(long roleId);

	/**
	 * Returns the create date of this user role.
	 *
	 * @return the create date of this user role
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this user role.
	 *
	 * @param createDate the create date of this user role
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this user role.
	 *
	 * @return the modified date of this user role
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user role.
	 *
	 * @param modifiedDate the modified date of this user role
	 */
	public void setModifiedDate(Date modifiedDate);

}