name=Inspinia
module-group-id=Themeray
module-incremental-version=1
tags=
short-description=
long-description=
change-log=
page-url=http://www.themeray.com
author=Themeray, Innotall GmbH
licenses=LGPL
liferay-versions=7.3.0+
module-version=1.0.0
