include-and-override=portal-developer.properties

#
# MySQL
#
jdbc.default.driverClassName=com.mysql.cj.jdbc.Driver
#jdbc.default.url=jdbc:mysql://localhost/lfr-72-preving?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false&serverTimezone=UTC
jdbc.default.url=jdbc:mysql://localhost/lfr-72-timesheet?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false&serverTimezone=UTC
jdbc.default.username=root
jdbc.default.password=root

#
# Set the properties used to create the Java Mail session. The property
# prefix "mail.session." will be removed before it is used to create the
# session object. These properties will only be read if the property
# "mail.session.jndi.name" is not set.
#
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_POP_NUMBER3__PERIOD_HOST
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_POP_NUMBER3__PERIOD_PASSWORD
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_POP_NUMBER3__PERIOD_PORT
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_POP_NUMBER3__PERIOD_USER
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_SMTP_PERIOD_AUTH
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_SMTP_PERIOD_HOST
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_SMTP_PERIOD_PASSWORD
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_SMTP_PERIOD_PORT
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_SMTP_PERIOD_STARTTLS_PERIOD_ENABLE
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_SMTP_PERIOD_USER
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_STORE_PERIOD_PROTOCOL
# Env: LIFERAY_MAIL_PERIOD_SESSION_PERIOD_MAIL_PERIOD_TRANSPORT_PERIOD_PROTOCOL
#
mail.session.mail=false
mail.session.mail.pop3.host=localhost
mail.session.mail.pop3.password=
mail.session.mail.pop3.port=465
mail.session.mail.pop3.user=no-reply@miregistrodehoras.com
mail.session.mail.smtp.auth=true
mail.session.mail.smtp.host=mail.preving.com
mail.session.mail.smtp.password=M31x2DdK
mail.session.mail.smtp.port=465
mail.session.mail.smtp.starttls.enable=true
mail.session.mail.smtp.user=no-reply@miregistrodehoras.com
mail.session.mail.store.protocol=pop3
mail.session.mail.transport.protocol=smtps


#
# Specify the number of minutes before a session expires. This value is
# always overridden by the value set in web.xml.
#
# Env: LIFERAY_SESSION_PERIOD_TIMEOUT
#
session.timeout=60

#
# Specify the number of minutes before a warning is sent to the user
# informing the user of the session expiration. Specify 0 to disable any
# warnings.
#
# Env: LIFERAY_SESSION_PERIOD_TIMEOUT_PERIOD_WARNING
#
session.timeout.warning=1

#
# Set the auto-extend mode to true to avoid having to ask the user whether
# to extend the session or not. Instead, it will be automatically extended.
# The purpose of this mode is to keep the session open as long as the user's
# browser is open with a portal page loaded. It is recommended to use this
# setting along with a smaller "session.timeout", such as 5 minutes, for
# better performance.
#
# Env: LIFERAY_SESSION_PERIOD_TIMEOUT_PERIOD_AUTO_PERIOD_EXTEND
#
session.timeout.auto.extend=true

#
# When the property "session.timeout.auto.extend" is set to true, set the
# number of seconds between when the extend process is launched and the
# actual expiration of the session.
#
# Env: LIFERAY_SESSION_PERIOD_TIMEOUT_PERIOD_AUTO_PERIOD_EXTEND_PERIOD_OFFSET
#
session.timeout.auto.extend.offset=10

#
# Set this to true if the user is redirected to the default page when the
# session expires.
#
# Env: LIFERAY_SESSION_PERIOD_TIMEOUT_PERIOD_REDIRECT_PERIOD_ON_PERIOD_EXPIRE
#
session.timeout.redirect.on.expire=true


#
# Configure email notification settings.
#
# Env: LIFERAY_ADMIN_PERIOD_EMAIL_PERIOD_FROM_PERIOD_ADDRESS
# Env: LIFERAY_ADMIN_PERIOD_EMAIL_PERIOD_FROM_PERIOD_NAME
#
admin.email.from.name=Preving Admin
admin.email.from.address=no-reply@miregistrodehoras.com

#
# Env: LIFERAY_ANNOUNCEMENTS_PERIOD_EMAIL_PERIOD_TO_PERIOD_ADDRESS
# Env: LIFERAY_ANNOUNCEMENTS_PERIOD_EMAIL_PERIOD_TO_PERIOD_NAME
#
announcements.email.to.name=Preving Admin
announcements.email.to.address=no-reply@miregistrodehoras.com

#
# Specify the group id and the article id of the Journal article that will
# be displayed as the terms of use. The default text will be used if no
# Journal article is specified.
#
terms.of.use.journal.article.group.id=20123
terms.of.use.journal.article.id=39119
terms.of.use.journal.article.id.admin=39103


#
# The login field is prepopulated with the company's domain name if the
# login is unpopulated and user authentication is based on email addresses.
# Set this to false to disable the behavior.
#
company.login.prepopulate.domain=false

#
# Set this to true to enable reminder queries that are used to help reset a
# user's password.
#
users.reminder.queries.enabled=false
users.reminder.queries.custom.question.enabled=false

#
# Set this to false to enable users without a reminder query to reset their
# password.
#
users.reminder.queries.required=false

#
# The name of the roles created to use in Preving. The first one is for the
# user who created all the companies. The second one is the administrator of
# the company site, and the last one is the user.
#
preving.roles.preving.site.admin.name=Preving Administrator
preving.roles.company.site.admin.name=Preving Company Site Admin
preving.roles.company.site.user.name=Preving Company User


#
# The names of expando fields for Preving.
#
preving.expando.user.salary=salario
preving.expando.user.nif=nif
preving.expando.user.end.date=fechaBaja
preving.expando.user.work.center=centroTrabajo

#
# The name of "Procedencia".
#
preving.source.default=TOTALDAT;SOURCE1;SOURCE2;SOURCE3

#
# Configure company date end email notification settings.
#
preving.company.date.end.cron.expression=0 15 0 1/1 * ? *
preving.company.date.end.admin.email.from.name=Administrador Preving
preving.company.date.end.admin.email.from.address=admin@preving.com
preving.company.date.end.admin.email.subject=La aplicaci\u00C3\u00B3n de control horario ha finalizado
preving.company.date.end.admin.email.body=A partir de este momento ya no podr\u00C3\u00A1 utilizar la aplicaci\u00C3\u00B3n de control horario. Contacte con el administrador de Preving para m\u00C3\u00A1s informaci\u00C3\u00B3n.

#
# Configure user date end cron.
#
preving.user.date.end.cron.expression=0 25 0 1/1 * ? *
