var language = {
    cuestionarioSi: "Si",
    cuestionarioNo: "No",
    cuestionarioNoConvenio: "No, viene determinado en el Convenio de aplicación de ámbito superior a la Empresa",
    cuestionarioNoAplica: "No aplica",
    cuestionario11: "1. Describa brevemente la trayectoria de su Organización.",
    cuestionario12: "2. Indique, en su caso, peculiaridades de la actividad desarrollada y de cada centro de trabajo.",
    cuestionario13: "3. Indique si su Organización dispone de un Canal ético o canal de denuncias.",
    cuestionario14: "4. Indique los medios empleados para comunicar a las personas trabajadoras de la Organización los procesos de selección y contratación, formación, promoción profesional, la existencia de medidas de conciliación, y las medidas existentes contra la prevención del acoso. (respuesta múltiple)",
    canal: "Canal de comunicación",
    seleccion: "Selección y contratación",
    formacion: "Formación",
    promocion: "Promoción profesional",
    conciliacion: "Medidas de conciliación",
    acoso: "Medidas de acoso",
    reuniones: "Reuniones",
    plantilla: "Presentaciones a la plantilla",
    correo: "Correo electrónico",
    anuncios: "Tablón de anuncios",
    nomina: "Mensajes en nómina mensual",
    revista: "Periódico o revista interna",
    internet: "Intranet",
    apps: "Apps de mensajería instantánea u otras apliaciones online",
    comunicacion: "No comunico este proceso",
    cuestionario25: "5. ¿Su Organización ya tiene realizada una descripción de perfiles profesionales y puestos de trabajo?",
    cuestionario251: "5.1. Si respondió afirmativamente a la pregunta 5, indique si la descripción se ha realizado de todos los puestos de trabajo de la Organización.",
    cuestionario252: "5.2. Si respondió afirmativamente a la pregunta 5, indique si la descripción realizada es exhaustiva, incluyendo entre otros: Departamento, puesto superior inmediato, misión, funciones principales... ",
    cuestionario253: "5.3. Si respondió afirmativamente a la pregunta 5, indique si la descripción se ha realizado mediante la colaboración de los distintos departamentos de su Organización, con el de Recursos humanos.",
    cuestionario254: "5.4. Si respondió afirmativamente a la pregunta 5, indique si la descripción es revisada periódicamente.",
    cuestionario255: "5.5. Si respondió afirmativamente a la pregunta 5, indique si el lenguaje de la descripción de puestos de trabajo ha sido revisado a fin de garantizar el lenguaje inclusivo.",
    cuestionario26: "6. La Organización realiza la selección y contratación de acuerdo a:",
    cuestionario261: "Política y criterios de contratación corporativos",
    cuestionario262: "Criterios establecidos de manera indivdidualizada para cada contratación",
    cuestionario263: "Cada persona responsable establece su propio criterio",
    cuestionario264: "Depende del perfil del puesto: directivo, mando intermedio u otros puestos de no responsabilidad",
    cuestionario27: "7. ¿La Organización gestiona con medios propios todo el proceso de selección?",
    cuestionario271: "No, cuenta con empresas externas",
    cuestionario28: "8. Internamente, en el proceso de selección del candidato/a intervienen: (seleccione tantas opciones como corresponda)",
    cuestionario281: "Personal del departamento de Recursos humanos",
    cuestionario282: "Personal responsable del departamento que solicita la incorporación",
    cuestionario283: "Personal directivo",
    cuestionario29: "9. Indique los métodos utilizados para la gestión y retención de talento en la Organización: (seleccione tantas opciones como corresponda)",
    cuestionario291: "Política de bienestar laboral",
    cuestionario292: "Conciliación de la vida personal, familiar y laboral",
    cuestionario293: "Plan de promoción interna",
    cuestionario294: "Ninguna medida implantada orientada al resultado: gestión y retención del talento",
    cuestionario295: "Otros (especifique cuales):",
    cuestionario30: "10. La causa mayoritaria de las incorporaciones del último año es:",
    cuestionario301: "Rotación de personal",
    cuestionario302: "Incremento o necesidades de la producción",
    cuestionario311: "11. ¿El sistema de clasificación profesional vigente ha sido acordado en el seno de la Organización?",
    cuestionario3111: "11.1. Si respondió afirmativamente a la pregunta 11, indique si los criterios del sistema de clasificación son revisados periódicamente.",
    cuestionario3112: "11.2. Si respondió afirmativamente a la pregunta 11, indique si el lenguaje empleado en la documentación del sistema de clasificación profesional ha sido revisado a fin de garantizar el lenguaje inclusivo.",
    cuestionario312: "12. ¿El sistema de clasificación profesional comprende todos los puestos de trabajo de la Organización?",
    cuestionario413: "13. ¿La Organización documenta un Plan de formación anual?",
    cuestionario4131: "13.1. Si respondió afirmativamente a la pregunta 13, indique si el Plan cuenta expresamente entre sus objetivos con la integración de la Igualdad entre Hombres y Mujeres en todos los procesos de la Organización.",
    cuestionario4132: "13.2. Si respondió afirmativamente a la pregunta 13, indique si se realiza un seguimiento de la ejecución y el grado de consecución de objetivos del Plan de formación.",
    cuestionario414: "14. ¿La Organización aprueba permisos para la concurrencia a exámenes de sus personas trabajadoras?",
    cuestionario415: "15. ¿Se han adoptado medidas para la adaptación de la jornada ordinaria de trabajo para la asistencia a cursos de formación profesional?",
    cuestionario416: "16. ¿El Plan de formación incluye la formación necesaria para favorecer la adaptación de la persona trabajadora a las modificaciones operadas en el puesto?",
    cuestionario517: "17. En relación a los criterios tenidos en cuenta en la promoción profesional, indique porcentualmente cuál es la incidencia de la formación del candidato.",
    cuestionario5171: "Menos del 25%",
    cuestionario5172: "Entre un 25% y un 50%",
    cuestionario5173: "Más de un 50%",
    cuestionario518: "18. En relación a los criterios tenidos en cuenta en la promoción profesional, indique porcentualmente cuál es la incidencia de la antigüedad del candidato.",
    cuestionario5181: "Menos del 25%",
    cuestionario5182: "Entre un 25% y un 50%",
    cuestionario5183: "Más de un 50%",
    cuestionario519: "19. En relación a los criterios tenidos en cuenta en la promoción profesional, indique porcentualmente cuál es la incidencia de los méritos del candidato (nivel de contribución, responsabilidades y exigencias).",
    cuestionario5191: "Menos del 25%",
    cuestionario5192: "Entre un 25% y un 50%",
    cuestionario5193: "Más de un 50%",
    cuestionario520: "20. En relación a los criterios tenidos en cuenta en la promoción profesional, indique porcentualmente cuál es la incidencia de las facultades organizativas del empresario.",
    cuestionario5201: "Menos del 25%",
    cuestionario5202: "Entre un 25% y un 50%",
    cuestionario5203: "Más de un 50%",
    cuestionario521: "21. Indique si las promociones se vinculan mayoritariamente a:",
    cuestionario5211: "Movilidad geográfica",
    cuestionario5212: "Dedicación exclusiva",
    cuestionario5213: "Disponibilidad para viajar",
    cuestionario5214: "Ninguna de las anteriores",
    cuestionario522: "22. Indique si los criterios para ascender han sido acordados en el seno de la Organización.",
    cuestionario5221: "Sí",
    cuestionario5222: "No, vienen establecidos en el convenio colectivo de ámbito superior de la organización",
    cuestionario5223: "No, no están documentados",
    cuestionario523: "23. Indique si los criterios para promocionar económicamente a un trabajador han sido acordados en el seno de la Organización.",
    cuestionario5231: "Sí",
    cuestionario5232: "No, vienen establecidos en el convenio colectivo de ámbito superior de la empresa",
    cuestionario5233: "No, no están documentados",
    cuestionario624: "24. Indique si existe en la Organización un sistema de primas que retribuya la producción y/o calidad del trabajo.",
    cuestionario6241: "24.1. Si respondió afirmativamente a la pregunta 24, indique si el pago de primas se establece para todos los puestos.",
    cuestionario62411: "Si",
    cuestionario62412: "No aplica",
    cuestionario62413: "No (especifique cuales): ",
    cuestionario6242: "24.2. Si respondió afirmativamente a la pregunta 24, indique si el sistema de medición del trabajo:",
    cuestionario62421: "Se basa en datos objetivos y cuantificables",
    cuestionario62422: "Se basa directamente en valoración subjetiva del personal con funciones de supervisión",
    cuestionario62423: "No aplica",
    cuestionario625: "25. Indique si existe en la Organización un sistema de incentivos directamente vinculado a la consecución de objetivos económicos.",
    cuestionario6251: "25.1 Si respondió afirmativamente a la pregunta 25, indique si el pago de incentivos se establece para todos los puestos.",
    cuestionario626: "26. La Organización emplea a trabajadores/as en modalidad de teletrabajo.",
    cuestionario6261: "26.1. Si respondió afirmativamente a la pregunta 26, indique si el teletrabajo se aplica más a:",
    cuestionario2611: "Mujeres",
    cuestionario2612: "Hombres",
    cuestionario2613: "De manera equilibrada",
    cuestionario2614: "No aplica",
    cuestionario6262: "26.2. Si respondió afirmativamente a la pregunta 26, indique si los procesos de gestión de Prevención de Riesgos Laborales y medición del trabajo se han adaptado a esta modalidad de trabajo.",
    cuestionario627: "27. ¿La Organización ha dispuesto medidas de prevención de riesgos laborales con perspectiva de género (ej. riesgos laborales específicos para mujeres embarazadas, en situación de lactancia, etc.)?",
    cuestionario628: "28. ¿La Organización ha establecido e informado a la plantilla de los criterios de utilización de los dispositivos digitales por las personas trabajadoras, respetando en todo caso los estándares mínimos de protección de su intimidad? ",
    cuestionario629: "29. ¿La Organización tiene aprobada e implantada una Política de desconexión digital?",
    cuestionario630: "30. Indique si el principal motivo de solicitud de excedencia en su Organización ha sido el cuidado de familiares.",
    cuestionario631: "31. Indique si las excedencias han sido solicitadas mayoritariamente por:",
    cuestionario6311: "Hombres",
    cuestionario6312: "Mujeres",
    cuestionario6313: "De manera equilibrada",
    cuestionario632: "32. Indique si el absentismo repercute mayoritariamente en:",
    cuestionario321: "Hombres",
    cuestionario322: "Mujeres",
    cuestionario323: "De manera equilibrada",
    cuestionario633: "33. Indique si el principal motivo de ausencias no justificadas en su Organización ha sido el cuidado de familiares:",
    cuestionario634: "34. ¿La Organización aplica medidas que complementan lo dispuesto en el art. 39 ET sobre la movilidad funcional?",
    cuestionario635: "35. ¿La Organización aplica medidas que complementan lo dispuesto en el art. 40 ET sobre la movilidad geográfica?",
    cuestionario636: "36. ¿En los últimos tres años se han producido modificaciones sustanciales de las condiciones de trabajo (art. 41 ET)?",
    cuestionario6361: "36.1 Si respondió afirmativamente a la pregunta 36, indique si las modificaciones han tenido impacto mayoritariamente en:",
    cuestionario63611: "Hombres",
    cuestionario63612: "Mujeres",
    cuestionario63613: "De manera equilibrada",
    cuestionario63614: "No aplica",
    cuestionario637: "37. ¿Su Organización cuenta con trabajadores/as cedidos por otra empresa?",
    cuestionario6371: "37.1. Si respondió afirmativamente a la pregunta 37, indique orientativamente qué porcentaje de personas de su Organización son cedidas y/o provienen de ETT.",
    cuestionario3711: "0-3%",
    cuestionario3712: "4-9%",
    cuestionario3713: ">10%",
    cuestionario3714: "No aplica",
    cuestionario6372: "37.2. Si respondió afirmativamente a la pregunta 37, indique si a este personal se le aplican las mismas condiciones que a la plantilla de la Organización.",
    cuestionario638: "38. ¿Se han producido inaplicaciones del Convenio Colectivo (art. 82.3 ET)? *",
    cuestionario639: "39. ¿Su Organización ha implantado un proceso de revisión del sistema de organización y control del trabajo?",
    cuestionario6391: "39.1. Si respondió afirmativamente a la pregunta 39, ¿en la elaboración del protocolo de revisión del sistema de organización y control del trabajo ha intervenido personal con formación en igualdad? ",
    cuestionario6392: "39.2. Si respondió afirmativamente a la pregunta 39, ¿el protocolo de revisión del sistema de organización y control del trabajo ha sido revisado para garantizar el lenguaje inclusivo empleado?",
    cuestionario640: "40. ¿Su Organización ha implantado un sistema documentado de estudio de tiempos de realización del trabajo?",
    cuestionario6401: "40.1. Si respondió afirmativamente a la pregunta 40, ¿en la elaboración del estudio de tiempo ha intervenido personal con formación en igualdad?",
    cuestionario6402: "40.2. Si respondió afirmativamente a la pregunta 40, ¿el estudio de tiempo ha sido revisado para garantizar el lenguaje inclusivo empleado?",
    cuestionario741: "41. ¿La Organización tiene implantadas medidas para facilitar la conciliación personal, familiar y laboral y promover el ejercicio corresponsable de dichos derechos?",
    cuestionario7411: "41.1. Si respondió afirmativamente la pregunta 41, indique las medidas implantadas.",
    cuestionario74111: "Guardería en la organización",
    cuestionario74112: "Subvenciones económicas para guardería o ayuda escolar",
    cuestionario74113: "Flexibilidad de horarios en la entrada, la salida o durante el tiempo de la comida",
    cuestionario74114: "Jornada coincidente con el horario escolar",
    cuestionario74115: "Teletrabajo o trabajo a distancia (TAD)",
    cuestionario74116: "Ampliación el permiso de maternidad o paternidad",
    cuestionario74117: "Otras (especifique cuáles): ",
    cuestionario742: "42. La Organización aplica con carácter preferente a personas trabajadoras con responsabilidades de cuidado medidas que favorezcan la conciliación con: cambios de funciones, distribución irregular de la jornada, cambios de centro sin cambio de residencia, modificaciones sustanciales de las condiciones de trabajo, traslados, desplazamientos…",
    cuestionario843: "43. ¿La participación de Mujeres y Hombres en los distintos niveles jerárquicos, grupos y subgrupos profesionales y su evolución en los cuatro años anteriores a la elaboración del diagnóstico ha sido positiva, tendiendo al equilibrio?",
    cuestionario844: "44. En los últimos cuatro años, ¿el número de personas del sexo infrarrepresentado que ha comenzado a ocupar puestos de responsabilidad ha sido notablemente superior al del otro sexo?",
    cuestionario945: "45. ¿Dispone de un procedimiento para la sensibilización, prevención, detección y actuación contra el acoso sexual y/o por razón de sexo?",
    cuestionario9451: "45.1. Si respondió afirmativamente a la pregunta 45, ¿el procedimiento dispone de una declaración de principios, de la definición de acoso sexual y por razón de sexo, e identifica las conductas que pudieran ser constitutivas de acoso?",
    cuestionario9452: "45.2. Si respondió afirmativamente a la pregunta 45, ¿el procedimiento dispone del protocolo de actuación frente al acoso para dar cauce a las quejas o denuncias que pudieran producirse, así como medidas cautelares y/o medidas correctivas aplicables?",
    cuestionario9453: "45.3. Si respondió afirmativamente a la pregunta 45, ¿el procedimiento identifica las medidas reactivas frente al acoso y, en su caso, el régimen disciplinario?",
    cuestionario9454: "45.4. Si respondió afirmativamente a la pregunta 45, ¿el procedimiento aplica el principio de prevención y sensibilización del acoso sexual y por razón de sexo: información y accesibilidad de los procedimientos y medidas?",
    cuestionario9455: "45.5. Si respondió afirmativamente a la pregunta 45, ¿el procedimiento aplica el principio de confidencialidad y respeto a la intimidad y dignidad de las personas afectadas?",
    cuestionario9456: "45.6. Si respondió afirmativamente a la pregunta 45, ¿el procedimiento respeta el principio de presunción de inocencia de la supuesta persona acosado?",
    cuestionario9457: "45.7. Si respondió afirmativamente a la pregunta 45, ¿el procedimiento prohíbe represalias en la supuesta víctima o personas que apoyen la denuncia o denuncien supuestos de acoso sexual y por razón de sexo?",
    cuestionario9458: "45.8. Si respondió afirmativamente a la pregunta 45, ¿el procedimiento se aplica con diligencia y celeridad?",
    cuestionario9459: "45.9. Si respondió afirmativamente a la pregunta 45, ¿el procedimiento garantiza los derechos laborales y de protección social de las víctimas?",
    cuestionario1046: "46. ¿La Organización tiene identificadas mujeres víctimas de violencia de género que trabajan en la Organización?",
    cuestionario1047: "47. ¿Se prevé asesoramiento o apoyo profesional psicológico y/o médico a las víctimas de violencia de género?",
    cuestionario1048: "48. ¿Se amplían los derechos laborales y/o las medidas legalmente establecidas para las víctimas de violencia de género?",
    cuestionario1049: "49. ¿La Organización tiene un programa de inserción, permanencia y/o promoción de colectivos especiales (víctimas de violencia de género, personas en situación o riesgo de exclusión social, …)?",
    cuestionario1150: "50. ¿Las denominaciones de los puestos de trabajo se han adecuado al lenguaje inclusivo?",
    cuestionario1151: "51. ¿El lenguaje de la comunicación externa de la Organización ha sido revisado para garantizar que sea inclusivo?",
    cuestionario1152: "52. ¿Los logos e imágenes representativas y/o utilizadas por la Organización han sido revisadas para evitar que resulten sexistas?",
    cuestionario1253: "Si lo desea, indique a continuación comentarios sobre cualquiera de los aspectos tratados en el cuestionario."
}