var language = {
    cuestionarioSi: "Sí",
    cuestionarioNo: "No",
    cuestionarioNoConvenio: "No, ve determinat al Conveni d’aplicació d’àmbit superior a l’Empresa",
    cuestionarioNoAplica: "No aplica",
    cuestionario11: "1. Descrigui breument la trajectòria de la seva Organització.",
    cuestionario12: "3. Indiqui si la seva Organització disposa d’un Canal ètic o canal de denúncies.",
    cuestionario13: "3. Indique si su Organización dispone de un Canal ético o canal de denuncias.",
    cuestionario14: "4. Indiqui els mitjans emprats per comunicar a les persones treballadores de l'Organització els processos de selecció i contractació, formació, promoció professional, l'existència de mesures de conciliació i les mesures existents contra la prevenció de l'assetjament. (resposta múltiple)",
    canal: "Canal de comunicació",
    seleccion: "Selecció i contractació",
    formacion: "Formació",
    promocion: "Promoció professional",
    conciliacion: "Mesures de conciliació",
    acoso: "Mesures d’assetjament",
    reuniones: "Reunions",
    plantilla: "Presentacions a la plantilla",
    correo: "Correu electrònic",
    anuncios: "Tauler d’anuncis",
    nomina: "Missatges en nòmina mensual",
    revista: "Periòdic o revista interna",
    internet: "Intranet",
    apps: "Apps de missatgeria instantània o altres aplicacions en línia",
    comunicacion: "No comunico aquest procés",
    cuestionario25: "5. La seva organització ja té realitzada una descripció de perfils professionals i llocs de treball?",
    cuestionario251: "5.1. Si ha respost afirmativament a la pregunta 5, indiqui si la descripció s'ha realitzat de tots els llocs de treball de l'Organització.",
    cuestionario252: "5.2. Si ha respost afirmativament a la pregunta 5, indiqui si la descripció realitzada és exhaustiva, incloent-hi entre d'altres: Departament, lloc superior immediat, missió, funcions principals...",
    cuestionario253: "5.3. Si ha respost afirmativament a la pregunta 5, indiqui si la descripció s'ha realitzat mitjançant la col·laboració dels diferents departaments de la seva Organització, amb el de Recursos humans.",
    cuestionario254: "5.4. Si ha respost afirmativament a la pregunta 5, indiqui si la descripció es revisa periòdicament.",
    cuestionario255: "5.5. Si ha respost afirmativament a la pregunta 5, indiqui si el llenguatge de la descripció de llocs de treball ha estat revisat per tal de garantir el llenguatge inclusiu.",
    cuestionario26: "6. L'Organització realitza la selecció i contractació d'acord amb:",
    cuestionario261: "Política i criteris de contractació corporatius",
    cuestionario262: "Criteris establerts de manera individualitzada per a cada contractació",
    cuestionario263: "Cada persona responsable estableix el seu propi criteri",
    cuestionario264: "Depèn del perfil del lloc: directiu, cap intermedi o altres llocs de no responsabilitat",
    cuestionario27: "7. L'Organització gestiona amb mitjans propis tot el procés de selecció?",
    cuestionario271: "No, compta amb empreses externes",
    cuestionario28: "8. Internament, en el procés de selecció del candidat/a intervenen: (seleccioni tantes opcions com correspongui)",
    cuestionario281: "Personal del departament de Recursos humans",
    cuestionario282: "Personal responsable del departament que sol·licita la incorporació",
    cuestionario283: "Personal directiu",
    cuestionario29: "9. Indiqui els mètodes utilitzats per a la gestió i retenció de talent a l'Organització: (seleccioni tantes opcions com correspongui)",
    cuestionario291: "Política de benestar laboral",
    cuestionario292: "Conciliació de la vida personal, familiar i laboral",
    cuestionario293: "Pla de promoció interna",
    cuestionario294: "Cap mesura implantada orientada al resultat: gestió i retenció del talent",
    cuestionario295: "Altres (especifiqui quins):",
    cuestionario30: "10. La causa majoritària de les incorporacions del darrer any és:",
    cuestionario301: "Rotació de personal",
    cuestionario302: "Increment o necessitats de la producció",
    cuestionario311: "11. El sistema de classificació professional vigent ha estat acordat al si de l'Organització?",
    cuestionario3111: "11.1. Si ha respost afirmativament a la pregunta 11, indiqui si els criteris del sistema de classificació es revisen periòdicament.",
    cuestionario3112: "11.2. Si ha respost afirmativament a la pregunta 11, indiqui si el llenguatge empleat a la documentació del sistema de classificació professional ha estat revisat per tal de garantir el llenguatge inclusiu.",
    cuestionario312: "12. El sistema de classificació professional comprèn tots els llocs de treball de l’Organització?",
    cuestionario413: "13. L’Organització documenta un Pla de formació anual?",
    cuestionario4131: "13.1. Si ha respost afirmativament a la pregunta 13, indiqui si el Pla compta expressament entre els seus objectius amb la integració de la Igualtat entre Homes i Dones a tots els processos de l’Organització.",
    cuestionario4132: "13.2. Si ha respost afirmativament a la pregunta 13, indiqui si es fa un seguiment de l'execució i el grau d'assoliment d'objectius del Pla de formació.",
    cuestionario414: "14. L'Organització aprova permisos per a la concurrència a exàmens de les persones treballadores?",
    cuestionario415: "15. S'han adoptat mesures per a l'adaptació de la jornada ordinària de treball per a l'assistència a cursos de formació professional?",
    cuestionario416: "16. El Pla de formació inclou la formació necessària per afavorir l'adaptació de la persona treballadora a les modificacions operades al lloc?",
    cuestionario517: "17. En relació amb els criteris tinguts en compte en la promoció professional, indiqui percentualment quina és la incidència de la formació del candidat.",
    cuestionario5171: "Menys del 25%",
    cuestionario5172: "Entre un 25% i un 50%",
    cuestionario5173: "Més d’un 50%",
    cuestionario518: "18. En relació amb els criteris tinguts en compte en la promoció professional, indiqui percentualment quina és la incidència de l’antiguitat del candidat.",
    cuestionario5181: "Menys del 25%",
    cuestionario5182: "Entre un 25% i un 50%",
    cuestionario5183: "Més d’un 50%",
    cuestionario519: "19. En relació amb els criteris tinguts en compte en la promoció professional, indiqui percentualment quina és la incidència dels mèrits del candidat (nivell de contribució, responsabilitats i exigències).",
    cuestionario5191: "Menys del 25%",
    cuestionario5192: "Entre un 25% i un 50%",
    cuestionario5193: "Més d’un 50%",
    cuestionario520: "20. En relació amb els criteris tinguts en compte en la promoció professional, indiqui percentualment quina és la incidència de les facultats organitzatives de l’empresari.",
    cuestionario5201: "Menys del 25%",
    cuestionario5202: "Entre un 25% i un 50%",
    cuestionario5203: "Més d’un 50%",
    cuestionario521: "21. Indiqui si les promocions es vinculen majoritàriament a:",
    cuestionario5211: "Mobilitat geogràfica",
    cuestionario5212: "Dedicación exclusiva",
    cuestionario5213: "Disponibilitat per viatjar",
    cuestionario5214: "Cap de les anteriors",
    cuestionario522: "22. Indiqui si els criteris per a ascendir han estat acordats en el si de l'Organització.",
    cuestionario5221: "Sí",
    cuestionario5222: "No, venen establerts al conveni col·lectiu d’àmbit superior de l’organització",
    cuestionario5223: "No, no estan documentats",
    cuestionario523: "23. Indiqui si els criteris per a promocionar econòmicament a un treballador han estat acordats en el si de l'Organització.",
    cuestionario5231: "Sí",
    cuestionario5232: "No, venen establerts al conveni col·lectiu d’àmbit superior de l’empresa",
    cuestionario5233: "No, no estan documentats",
    cuestionario624: "24. Indiqui si existeix a l'Organització un sistema de primes que retribueixi la producció i/o qualitat del treball.",
    cuestionario6241: "24.1. Si ha respost afirmativament a la pregunta 24, indiqui si el pagament de primes s'estableix per a tots els llocs.",
    cuestionario62411: "Sí",
    cuestionario62412: "No aplica",
    cuestionario62413: "No (especifiqui quins): ",
    cuestionario6242: "24.2. Si ha respost afirmativament a la pregunta 24, indiqui si el sistema de mesurament del treball:",
    cuestionario62421: "Es basa en dades objectives i quantificables",
    cuestionario62422: "Es basa directament en la valoració subjectiva del personal amb funcions de supervisió",
    cuestionario62423: "No aplica",
    cuestionario625: "25. Indiqui si a l'Organització hi ha un sistema d'incentius directament vinculat a la consecució d'objectius econòmics.",
    cuestionario6251: "25.1 Si ha respost afirmativament a la pregunta 25, indiqui si el pagament d’incentius s'estableix per a tots els llocs.",
    cuestionario626: "26. L'Organització ocupa treballadors/ores en modalitat de teletreball.",
    cuestionario6261: "26.1. Si ha respost afirmativament a la pregunta 26, indiqui si el teletreball s’aplica més a:",
    cuestionario2611: "Dones",
    cuestionario2612: "Homes",
    cuestionario2613: "De manera equilibrada",
    cuestionario2614: "No aplica",
    cuestionario6262: "26.2. Si ha respost afirmativament a la pregunta 26, indiqui si els processos de gestió de Prevenció de Riscos Laborals i mesurament del treball s'han adaptat a aquesta modalitat de treball.",
    cuestionario627: "27. L'Organització ha disposat mesures de prevenció de riscos laborals amb perspectiva de gènere (ex. riscos laborals específics per a dones embarassades, en situació de lactància, etc.)?",
    cuestionario628: "28. L'Organització ha establert i informat a la plantilla dels criteris d'utilització dels dispositius digitals per les persones treballadores, respectant, en tot cas, els estàndards mínims de protecció de la seva intimitat? ",
    cuestionario629: "29. L'Organització té aprovada i implantada una política de desconnexió digital?",
    cuestionario630: "30. Indiqui si el principal motiu de sol·licitud d'excedència a la seva Organització ha estat la cura de familiars.",
    cuestionario631: "31. Indiqui si les excedències han estat sol·licitades majoritàriament per:",
    cuestionario6311: "Homes",
    cuestionario6312: "Dones",
    cuestionario6313: "De manera equilibrada",
    cuestionario632: "32. Indiqui si l'absentisme repercuteix majoritàriament en:",
    cuestionario321: "Homes",
    cuestionario322: "Dones",
    cuestionario323: "De manera equilibrada",
    cuestionario633: "33. Indiqui si el principal motiu d’absències no justificades a la seva Organització ha estat la cura de familiars:",
    cuestionario634: "34. L'Organització aplica mesures que complementen el que disposa l'art. 39 ET sobre la mobilitat funcional?",
    cuestionario635: "35. L'Organització aplica mesures que complementen el que disposa l'art. 40 ET sobre la mobilitat geogràfica?",
    cuestionario636: "36. En els darrers tres anys s'han produït modificacions substancials de les condicions de treball (art. 41 ET)?",
    cuestionario6361: "36.1 Si respondió afirmativamente a la pregunta 36, indique si las modificaciones han tenido impacto mayoritariamente en:",
    cuestionario63611: "Homes",
    cuestionario63612: "Dones",
    cuestionario63613: "De manera equilibrada",
    cuestionario63614: "No aplica",
    cuestionario637: "37. La seva organització compta amb treballadors/es cedits per una altra empresa?",
    cuestionario6371: "37.1. Si ha respost afirmativament a la pregunta 37, indiqui de manera orientativa quin percentatge de persones de la seva organització són cedides i/o provenen d'ETT.",
    cuestionario3711: "0-3%",
    cuestionario3712: "4-9%",
    cuestionario3713: ">10%",
    cuestionario3714: "No aplica",
    cuestionario6372: "37.2. Si ha respost afirmativament a la pregunta 37, indiqui si a aquest personal se li apliquen les mateixes condicions que a la plantilla de l'Organització.",
    cuestionario638: "38. S'han produït inaplicacions del Conveni Col·lectiu (art. 82.3 ET)? *",
    cuestionario639: "39. La seva organització ha implantat un procés de revisió del sistema d'organització i control del treball?",
    cuestionario6391: "39.1. Si ha respost afirmativament a la pregunta 39, en l'elaboració del protocol de revisió del sistema d'organització i control del treball ha intervingut personal amb formació en igualtat?",
    cuestionario6392: "39.2. Si ha respost afirmativament a la pregunta 39, el protocol de revisió del sistema d'organització i control del treball ha estat revisat per garantir el llenguatge inclusiu emprat?",
    cuestionario640: "40. La vostra organització ha implantat un sistema documentat d'estudi de temps de realització del treball?",
    cuestionario6401: "40.1. Si ha respost afirmativament a la pregunta 40, en l'elaboració de l'estudi de temps ha intervingut personal amb formació en igualtat?",
    cuestionario6402: "40.2. Si ha respost afirmativament a la pregunta 40, l'estudi de temps ha estat revisat per garantir el llenguatge inclusiu emprat?",
    cuestionario741: "41. L'Organització té implantades mesures per facilitar la conciliació personal, familiar i laboral i promoure l'exercici coresponsable d’aquests drets?",
    cuestionario7411: "41.1. Si ha respost afirmativament la pregunta 41, indiqui les mesures implantades.",
    cuestionario74111: "Guarderia a l'organització",
    cuestionario74112: "Subvencions econòmiques per a guarderia o ajuda escolar",
    cuestionario74113: "Flexibilitat d'horaris a l'entrada, sortida o durant el temps del dinar",
    cuestionario74114: "Jornada coincident amb l’horari escolar",
    cuestionario74115: "Teletreball o treball a distància (TAD)",
    cuestionario74116: "Ampliació del permís de maternitat o paternitat",
    cuestionario74117: "Altres (especifiqui quins): ",
    cuestionario742: "42. L'Organització aplica amb caràcter preferent a persones treballadores amb responsabilitats de cura mesures que afavoreixin la conciliació amb: canvis de funcions, distribució irregular de la jornada, canvis de centre sense canvi de residència, modificacions substancials de les condicions de treball, trasllats, desplaçaments... ",
    cuestionario843: "43. La participació de Dones i Homes als diferents nivells jeràrquics, grups i subgrups professionals i la seva evolució en els quatre anys anteriors a l'elaboració del diagnòstic ha estat positiva, amb tendència a l'equilibri?",
    cuestionario844: "44. En els darrers quatre anys, el nombre de persones del sexe infrarepresentat que ha començat a ocupar llocs de responsabilitat ha estat notablement superior al de l'altre sexe?",
    cuestionario945: "45. Disposa d'un procediment per a la sensibilització, la prevenció, la detecció i l'actuació contra l'assetjament sexual i/o per raó de sexe?",
    cuestionario9451: "45.1. Si ha respost afirmativament a la pregunta 45, el procediment disposa d'una declaració de principis, de la definició d'assetjament sexual i per raó de sexe, i identifica les conductes que puguin ser constitutives d'assetjament?",
    cuestionario9452: "45.2. Si ha respost afirmativament a la pregunta 45, el procediment disposa del protocol d'actuació davant de l'assetjament per donar via a les queixes o denúncies que es puguin produir, així com mesures cautelars i/o mesures correctives aplicables?",
    cuestionario9453: "45.3. Si ha respost afirmativament a la pregunta 45, el procediment identifica les mesures reactives davant l'assetjament i, si escau, el règim disciplinari?",
    cuestionario9454: "45.4. Si ha respost afirmativament a la pregunta 45, el procediment aplica el principi de prevenció i sensibilització de l'assetjament sexual i per raó de sexe: informació i accessibilitat dels procediments i mesures?",
    cuestionario9455: "45.5. Si ha respost afirmativament a la pregunta 45, el procediment aplica el principi de confidencialitat i respecte a la intimitat i dignitat de les persones afectades?",
    cuestionario9456: "45.6. Si ha respost afirmativament a la pregunta 45, el procediment respecta el principi de presumpció d'innocència de la suposada persona assetjadora?",
    cuestionario9457: "45.7. Si ha respost afirmativament a la pregunta 45, el procediment prohibeix represàlies contra la suposada víctima o persones que donin suport a la denúncia o denunciïn supòsits d'assetjament sexual i per raó de sexe?",
    cuestionario9458: "45.8. Si ha respost afirmativament a la pregunta 45, el procediment s'aplica amb diligència i celeritat?",
    cuestionario9459: "45.9. Si ha respost afirmativament a la pregunta 45, el procediment garanteix els drets laborals i de protecció social de les víctimes?",
    cuestionario1046: "46. L'Organització té identificades dones víctimes de violència de gènere que treballen a l'Organització?",
    cuestionario1047: "47. Es preveu assessorament o suport professional psicològic i/o mèdic a les víctimes de violència de gènere?",
    cuestionario1048: "48. S'amplien els drets laborals i/o les mesures legalment establertes per a les víctimes de violència de gènere?",
    cuestionario1049: "49. L'Organització té un programa d'inserció, permanència i/o promoció de col·lectius especials (víctimes de violència de gènere, persones en situació o risc d'exclusió social…)?",
    cuestionario1150: "50. Les denominacions dels llocs de treball s'han adequat al llenguatge inclusiu?",
    cuestionario1151: "51. El llenguatge de la comunicació externa de l'Organització ha estat revisat per garantir que sigui inclusiu?",
    cuestionario1152: "52. Els logotips i les imatges representatives i/o utilitzades per l'Organització han estat revisades per evitar que resultin sexistes?",
    cuestionario1253: "Si ho desitja, indiqui a continuació comentaris sobre qualsevol dels aspectes tractats al qüestionari."
}