/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.plan.igualdad.liferay.portlet.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import com.plan.igualdad.liferay.portlet.manager.service.persistence.AreaPK;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Area service. Represents a row in the &quot;planigualdad_Area&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.plan.igualdad.liferay.portlet.manager.model.impl.AreaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.plan.igualdad.liferay.portlet.manager.model.impl.AreaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Area
 * @generated
 */
@ProviderType
public interface AreaModel extends BaseModel<Area> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a area model instance should use the {@link Area} interface instead.
	 */

	/**
	 * Returns the primary key of this area.
	 *
	 * @return the primary key of this area
	 */
	public AreaPK getPrimaryKey();

	/**
	 * Sets the primary key of this area.
	 *
	 * @param primaryKey the primary key of this area
	 */
	public void setPrimaryKey(AreaPK primaryKey);

	/**
	 * Returns the area ID of this area.
	 *
	 * @return the area ID of this area
	 */
	public long getAreaId();

	/**
	 * Sets the area ID of this area.
	 *
	 * @param areaId the area ID of this area
	 */
	public void setAreaId(long areaId);

	/**
	 * Returns the version ID of this area.
	 *
	 * @return the version ID of this area
	 */
	public long getVersionId();

	/**
	 * Sets the version ID of this area.
	 *
	 * @param versionId the version ID of this area
	 */
	public void setVersionId(long versionId);

	/**
	 * Returns the comp ID of this area.
	 *
	 * @return the comp ID of this area
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this area.
	 *
	 * @param compId the comp ID of this area
	 */
	public void setCompId(long compId);

	/**
	 * Returns the nombre of this area.
	 *
	 * @return the nombre of this area
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this area.
	 *
	 * @param nombre the nombre of this area
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the baja of this area.
	 *
	 * @return the baja of this area
	 */
	public Date getBaja();

	/**
	 * Sets the baja of this area.
	 *
	 * @param baja the baja of this area
	 */
	public void setBaja(Date baja);

}