/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.plan.igualdad.liferay.portlet.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Cuestionario service. Represents a row in the &quot;planigualdad_Cuestionario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.plan.igualdad.liferay.portlet.manager.model.impl.CuestionarioModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.plan.igualdad.liferay.portlet.manager.model.impl.CuestionarioImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Cuestionario
 * @generated
 */
@ProviderType
public interface CuestionarioModel extends BaseModel<Cuestionario> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cuestionario model instance should use the {@link Cuestionario} interface instead.
	 */

	/**
	 * Returns the primary key of this cuestionario.
	 *
	 * @return the primary key of this cuestionario
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cuestionario.
	 *
	 * @param primaryKey the primary key of this cuestionario
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cuestionario ID of this cuestionario.
	 *
	 * @return the cuestionario ID of this cuestionario
	 */
	public long getCuestionarioId();

	/**
	 * Sets the cuestionario ID of this cuestionario.
	 *
	 * @param cuestionarioId the cuestionario ID of this cuestionario
	 */
	public void setCuestionarioId(long cuestionarioId);

	/**
	 * Returns the comp ID of this cuestionario.
	 *
	 * @return the comp ID of this cuestionario
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this cuestionario.
	 *
	 * @param compId the comp ID of this cuestionario
	 */
	public void setCompId(long compId);

	/**
	 * Returns the version ID of this cuestionario.
	 *
	 * @return the version ID of this cuestionario
	 */
	public long getVersionId();

	/**
	 * Sets the version ID of this cuestionario.
	 *
	 * @param versionId the version ID of this cuestionario
	 */
	public void setVersionId(long versionId);

	/**
	 * Returns the user ID of this cuestionario.
	 *
	 * @return the user ID of this cuestionario
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this cuestionario.
	 *
	 * @param userId the user ID of this cuestionario
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this cuestionario.
	 *
	 * @return the user uuid of this cuestionario
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this cuestionario.
	 *
	 * @param userUuid the user uuid of this cuestionario
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the respuestas cuestionario of this cuestionario.
	 *
	 * @return the respuestas cuestionario of this cuestionario
	 */
	@AutoEscape
	public String getRespuestasCuestionario();

	/**
	 * Sets the respuestas cuestionario of this cuestionario.
	 *
	 * @param respuestasCuestionario the respuestas cuestionario of this cuestionario
	 */
	public void setRespuestasCuestionario(String respuestasCuestionario);

	/**
	 * Returns the observaciones of this cuestionario.
	 *
	 * @return the observaciones of this cuestionario
	 */
	@AutoEscape
	public String getObservaciones();

	/**
	 * Sets the observaciones of this cuestionario.
	 *
	 * @param observaciones the observaciones of this cuestionario
	 */
	public void setObservaciones(String observaciones);

	/**
	 * Returns the version cuestionario of this cuestionario.
	 *
	 * @return the version cuestionario of this cuestionario
	 */
	public Integer getVersionCuestionario();

	/**
	 * Sets the version cuestionario of this cuestionario.
	 *
	 * @param versionCuestionario the version cuestionario of this cuestionario
	 */
	public void setVersionCuestionario(Integer versionCuestionario);

	/**
	 * Returns the create date of this cuestionario.
	 *
	 * @return the create date of this cuestionario
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this cuestionario.
	 *
	 * @param createDate the create date of this cuestionario
	 */
	public void setCreateDate(Date createDate);

}