/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.plan.igualdad.liferay.portlet.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import com.plan.igualdad.liferay.portlet.manager.service.persistence.EstadisticaPK;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Estadistica service. Represents a row in the &quot;planigualdad_Estadistica&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.plan.igualdad.liferay.portlet.manager.model.impl.EstadisticaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.plan.igualdad.liferay.portlet.manager.model.impl.EstadisticaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Estadistica
 * @generated
 */
@ProviderType
public interface EstadisticaModel extends BaseModel<Estadistica> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a estadistica model instance should use the {@link Estadistica} interface instead.
	 */

	/**
	 * Returns the primary key of this estadistica.
	 *
	 * @return the primary key of this estadistica
	 */
	public EstadisticaPK getPrimaryKey();

	/**
	 * Sets the primary key of this estadistica.
	 *
	 * @param primaryKey the primary key of this estadistica
	 */
	public void setPrimaryKey(EstadisticaPK primaryKey);

	/**
	 * Returns the comp ID of this estadistica.
	 *
	 * @return the comp ID of this estadistica
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this estadistica.
	 *
	 * @param compId the comp ID of this estadistica
	 */
	public void setCompId(long compId);

	/**
	 * Returns the version ID of this estadistica.
	 *
	 * @return the version ID of this estadistica
	 */
	public long getVersionId();

	/**
	 * Sets the version ID of this estadistica.
	 *
	 * @param versionId the version ID of this estadistica
	 */
	public void setVersionId(long versionId);

	/**
	 * Returns the seccion ID of this estadistica.
	 *
	 * @return the seccion ID of this estadistica
	 */
	public long getSeccionId();

	/**
	 * Sets the seccion ID of this estadistica.
	 *
	 * @param seccionId the seccion ID of this estadistica
	 */
	public void setSeccionId(long seccionId);

	/**
	 * Returns the estadistica of this estadistica.
	 *
	 * @return the estadistica of this estadistica
	 */
	@AutoEscape
	public String getEstadistica();

	/**
	 * Sets the estadistica of this estadistica.
	 *
	 * @param estadistica the estadistica of this estadistica
	 */
	public void setEstadistica(String estadistica);

}