/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.plan.igualdad.liferay.portlet.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EstadoEmpresa service. Represents a row in the &quot;planigualdad_EstadoEmpresa&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.plan.igualdad.liferay.portlet.manager.model.impl.EstadoEmpresaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.plan.igualdad.liferay.portlet.manager.model.impl.EstadoEmpresaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EstadoEmpresa
 * @generated
 */
@ProviderType
public interface EstadoEmpresaModel extends BaseModel<EstadoEmpresa> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a estado empresa model instance should use the {@link EstadoEmpresa} interface instead.
	 */

	/**
	 * Returns the primary key of this estado empresa.
	 *
	 * @return the primary key of this estado empresa
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this estado empresa.
	 *
	 * @param primaryKey the primary key of this estado empresa
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the comp ID of this estado empresa.
	 *
	 * @return the comp ID of this estado empresa
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this estado empresa.
	 *
	 * @param compId the comp ID of this estado empresa
	 */
	public void setCompId(long compId);

	/**
	 * Returns the estado ID of this estado empresa.
	 *
	 * @return the estado ID of this estado empresa
	 */
	@AutoEscape
	public String getEstadoId();

	/**
	 * Sets the estado ID of this estado empresa.
	 *
	 * @param estadoId the estado ID of this estado empresa
	 */
	public void setEstadoId(String estadoId);

}