/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.plan.igualdad.liferay.portlet.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Evaluacion service. Represents a row in the &quot;planigualdad_Evaluacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.plan.igualdad.liferay.portlet.manager.model.impl.EvaluacionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.plan.igualdad.liferay.portlet.manager.model.impl.EvaluacionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Evaluacion
 * @generated
 */
@ProviderType
public interface EvaluacionModel extends BaseModel<Evaluacion> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a evaluacion model instance should use the {@link Evaluacion} interface instead.
	 */

	/**
	 * Returns the primary key of this evaluacion.
	 *
	 * @return the primary key of this evaluacion
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this evaluacion.
	 *
	 * @param primaryKey the primary key of this evaluacion
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the evaluacion ID of this evaluacion.
	 *
	 * @return the evaluacion ID of this evaluacion
	 */
	public long getEvaluacionId();

	/**
	 * Sets the evaluacion ID of this evaluacion.
	 *
	 * @param evaluacionId the evaluacion ID of this evaluacion
	 */
	public void setEvaluacionId(long evaluacionId);

	/**
	 * Returns the comp ID of this evaluacion.
	 *
	 * @return the comp ID of this evaluacion
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this evaluacion.
	 *
	 * @param compId the comp ID of this evaluacion
	 */
	public void setCompId(long compId);

	/**
	 * Returns the version ID of this evaluacion.
	 *
	 * @return the version ID of this evaluacion
	 */
	public long getVersionId();

	/**
	 * Sets the version ID of this evaluacion.
	 *
	 * @param versionId the version ID of this evaluacion
	 */
	public void setVersionId(long versionId);

	/**
	 * Returns the user ID of this evaluacion.
	 *
	 * @return the user ID of this evaluacion
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this evaluacion.
	 *
	 * @param userId the user ID of this evaluacion
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this evaluacion.
	 *
	 * @return the user uuid of this evaluacion
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this evaluacion.
	 *
	 * @param userUuid the user uuid of this evaluacion
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the datos generales of this evaluacion.
	 *
	 * @return the datos generales of this evaluacion
	 */
	@AutoEscape
	public String getDatosGenerales();

	/**
	 * Sets the datos generales of this evaluacion.
	 *
	 * @param datosGenerales the datos generales of this evaluacion
	 */
	public void setDatosGenerales(String datosGenerales);

	/**
	 * Returns the informacion resultados of this evaluacion.
	 *
	 * @return the informacion resultados of this evaluacion
	 */
	@AutoEscape
	public String getInformacionResultados();

	/**
	 * Sets the informacion resultados of this evaluacion.
	 *
	 * @param informacionResultados the informacion resultados of this evaluacion
	 */
	public void setInformacionResultados(String informacionResultados);

	/**
	 * Returns the informacion implantacion of this evaluacion.
	 *
	 * @return the informacion implantacion of this evaluacion
	 */
	@AutoEscape
	public String getInformacionImplantacion();

	/**
	 * Sets the informacion implantacion of this evaluacion.
	 *
	 * @param informacionImplantacion the informacion implantacion of this evaluacion
	 */
	public void setInformacionImplantacion(String informacionImplantacion);

	/**
	 * Returns the informacion impacto of this evaluacion.
	 *
	 * @return the informacion impacto of this evaluacion
	 */
	@AutoEscape
	public String getInformacionImpacto();

	/**
	 * Sets the informacion impacto of this evaluacion.
	 *
	 * @param informacionImpacto the informacion impacto of this evaluacion
	 */
	public void setInformacionImpacto(String informacionImpacto);

	/**
	 * Returns the conclusion of this evaluacion.
	 *
	 * @return the conclusion of this evaluacion
	 */
	@AutoEscape
	public String getConclusion();

	/**
	 * Sets the conclusion of this evaluacion.
	 *
	 * @param conclusion the conclusion of this evaluacion
	 */
	public void setConclusion(String conclusion);

	/**
	 * Returns the observaciones of this evaluacion.
	 *
	 * @return the observaciones of this evaluacion
	 */
	@AutoEscape
	public String getObservaciones();

	/**
	 * Sets the observaciones of this evaluacion.
	 *
	 * @param observaciones the observaciones of this evaluacion
	 */
	public void setObservaciones(String observaciones);

	/**
	 * Returns the version evaluacion of this evaluacion.
	 *
	 * @return the version evaluacion of this evaluacion
	 */
	public Integer getVersionEvaluacion();

	/**
	 * Sets the version evaluacion of this evaluacion.
	 *
	 * @param versionEvaluacion the version evaluacion of this evaluacion
	 */
	public void setVersionEvaluacion(Integer versionEvaluacion);

	/**
	 * Returns the create date of this evaluacion.
	 *
	 * @return the create date of this evaluacion
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this evaluacion.
	 *
	 * @param createDate the create date of this evaluacion
	 */
	public void setCreateDate(Date createDate);

}