/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.plan.igualdad.liferay.portlet.manager.model;

import com.liferay.portal.kernel.model.BaseModel;

import com.plan.igualdad.liferay.portlet.manager.service.persistence.FechaHitoPK;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FechaHito service. Represents a row in the &quot;planigualdad_FechaHito&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.plan.igualdad.liferay.portlet.manager.model.impl.FechaHitoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.plan.igualdad.liferay.portlet.manager.model.impl.FechaHitoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FechaHito
 * @generated
 */
@ProviderType
public interface FechaHitoModel extends BaseModel<FechaHito> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fecha hito model instance should use the {@link FechaHito} interface instead.
	 */

	/**
	 * Returns the primary key of this fecha hito.
	 *
	 * @return the primary key of this fecha hito
	 */
	public FechaHitoPK getPrimaryKey();

	/**
	 * Sets the primary key of this fecha hito.
	 *
	 * @param primaryKey the primary key of this fecha hito
	 */
	public void setPrimaryKey(FechaHitoPK primaryKey);

	/**
	 * Returns the hito ID of this fecha hito.
	 *
	 * @return the hito ID of this fecha hito
	 */
	public long getHitoId();

	/**
	 * Sets the hito ID of this fecha hito.
	 *
	 * @param hitoId the hito ID of this fecha hito
	 */
	public void setHitoId(long hitoId);

	/**
	 * Returns the version ID of this fecha hito.
	 *
	 * @return the version ID of this fecha hito
	 */
	public long getVersionId();

	/**
	 * Sets the version ID of this fecha hito.
	 *
	 * @param versionId the version ID of this fecha hito
	 */
	public void setVersionId(long versionId);

	/**
	 * Returns the comp ID of this fecha hito.
	 *
	 * @return the comp ID of this fecha hito
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this fecha hito.
	 *
	 * @param compId the comp ID of this fecha hito
	 */
	public void setCompId(long compId);

	/**
	 * Returns the fecha of this fecha hito.
	 *
	 * @return the fecha of this fecha hito
	 */
	public Date getFecha();

	/**
	 * Sets the fecha of this fecha hito.
	 *
	 * @param fecha the fecha of this fecha hito
	 */
	public void setFecha(Date fecha);

}