/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.plan.igualdad.liferay.portlet.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Hito service. Represents a row in the &quot;planigualdad_Hito&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.plan.igualdad.liferay.portlet.manager.model.impl.HitoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.plan.igualdad.liferay.portlet.manager.model.impl.HitoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Hito
 * @generated
 */
@ProviderType
public interface HitoModel extends BaseModel<Hito> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a hito model instance should use the {@link Hito} interface instead.
	 */

	/**
	 * Returns the primary key of this hito.
	 *
	 * @return the primary key of this hito
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this hito.
	 *
	 * @param primaryKey the primary key of this hito
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the hito ID of this hito.
	 *
	 * @return the hito ID of this hito
	 */
	public long getHitoId();

	/**
	 * Sets the hito ID of this hito.
	 *
	 * @param hitoId the hito ID of this hito
	 */
	public void setHitoId(long hitoId);

	/**
	 * Returns the nombre of this hito.
	 *
	 * @return the nombre of this hito
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this hito.
	 *
	 * @param nombre the nombre of this hito
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the peso of this hito.
	 *
	 * @return the peso of this hito
	 */
	@AutoEscape
	public String getPeso();

	/**
	 * Sets the peso of this hito.
	 *
	 * @param peso the peso of this hito
	 */
	public void setPeso(String peso);

}