/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.plan.igualdad.liferay.portlet.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import com.plan.igualdad.liferay.portlet.manager.service.persistence.ImagenCanvasEstPK;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ImagenCanvasEst service. Represents a row in the &quot;planigualdad_ImagenCanvasEst&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.plan.igualdad.liferay.portlet.manager.model.impl.ImagenCanvasEstModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.plan.igualdad.liferay.portlet.manager.model.impl.ImagenCanvasEstImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ImagenCanvasEst
 * @generated
 */
@ProviderType
public interface ImagenCanvasEstModel extends BaseModel<ImagenCanvasEst> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a imagen canvas est model instance should use the {@link ImagenCanvasEst} interface instead.
	 */

	/**
	 * Returns the primary key of this imagen canvas est.
	 *
	 * @return the primary key of this imagen canvas est
	 */
	public ImagenCanvasEstPK getPrimaryKey();

	/**
	 * Sets the primary key of this imagen canvas est.
	 *
	 * @param primaryKey the primary key of this imagen canvas est
	 */
	public void setPrimaryKey(ImagenCanvasEstPK primaryKey);

	/**
	 * Returns the comp ID of this imagen canvas est.
	 *
	 * @return the comp ID of this imagen canvas est
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this imagen canvas est.
	 *
	 * @param compId the comp ID of this imagen canvas est
	 */
	public void setCompId(long compId);

	/**
	 * Returns the version ID of this imagen canvas est.
	 *
	 * @return the version ID of this imagen canvas est
	 */
	public long getVersionId();

	/**
	 * Sets the version ID of this imagen canvas est.
	 *
	 * @param versionId the version ID of this imagen canvas est
	 */
	public void setVersionId(long versionId);

	/**
	 * Returns the seccion ID of this imagen canvas est.
	 *
	 * @return the seccion ID of this imagen canvas est
	 */
	public long getSeccionId();

	/**
	 * Sets the seccion ID of this imagen canvas est.
	 *
	 * @param seccionId the seccion ID of this imagen canvas est
	 */
	public void setSeccionId(long seccionId);

	/**
	 * Returns the img canvas ID of this imagen canvas est.
	 *
	 * @return the img canvas ID of this imagen canvas est
	 */
	@AutoEscape
	public String getImgCanvasId();

	/**
	 * Sets the img canvas ID of this imagen canvas est.
	 *
	 * @param imgCanvasId the img canvas ID of this imagen canvas est
	 */
	public void setImgCanvasId(String imgCanvasId);

	/**
	 * Returns the parte img of this imagen canvas est.
	 *
	 * @return the parte img of this imagen canvas est
	 */
	public long getParteImg();

	/**
	 * Sets the parte img of this imagen canvas est.
	 *
	 * @param parteImg the parte img of this imagen canvas est
	 */
	public void setParteImg(long parteImg);

	/**
	 * Returns the canvas image of this imagen canvas est.
	 *
	 * @return the canvas image of this imagen canvas est
	 */
	@AutoEscape
	public String getCanvasImage();

	/**
	 * Sets the canvas image of this imagen canvas est.
	 *
	 * @param canvasImage the canvas image of this imagen canvas est
	 */
	public void setCanvasImage(String canvasImage);

}