/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.plan.igualdad.liferay.portlet.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Informes service. Represents a row in the &quot;planigualdad_Informes&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.plan.igualdad.liferay.portlet.manager.model.impl.InformesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.plan.igualdad.liferay.portlet.manager.model.impl.InformesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Informes
 * @generated
 */
@ProviderType
public interface InformesModel extends BaseModel<Informes> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a informes model instance should use the {@link Informes} interface instead.
	 */

	/**
	 * Returns the primary key of this informes.
	 *
	 * @return the primary key of this informes
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this informes.
	 *
	 * @param primaryKey the primary key of this informes
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the informe ID of this informes.
	 *
	 * @return the informe ID of this informes
	 */
	public long getInformeId();

	/**
	 * Sets the informe ID of this informes.
	 *
	 * @param informeId the informe ID of this informes
	 */
	public void setInformeId(long informeId);

	/**
	 * Returns the comp ID of this informes.
	 *
	 * @return the comp ID of this informes
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this informes.
	 *
	 * @param compId the comp ID of this informes
	 */
	public void setCompId(long compId);

	/**
	 * Returns the user ID of this informes.
	 *
	 * @return the user ID of this informes
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this informes.
	 *
	 * @param userId the user ID of this informes
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this informes.
	 *
	 * @return the user uuid of this informes
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this informes.
	 *
	 * @param userUuid the user uuid of this informes
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the version ID of this informes.
	 *
	 * @return the version ID of this informes
	 */
	public long getVersionId();

	/**
	 * Sets the version ID of this informes.
	 *
	 * @param versionId the version ID of this informes
	 */
	public void setVersionId(long versionId);

	/**
	 * Returns the tipo informe of this informes.
	 *
	 * @return the tipo informe of this informes
	 */
	@AutoEscape
	public String getTipoInforme();

	/**
	 * Sets the tipo informe of this informes.
	 *
	 * @param tipoInforme the tipo informe of this informes
	 */
	public void setTipoInforme(String tipoInforme);

	/**
	 * Returns the version informe of this informes.
	 *
	 * @return the version informe of this informes
	 */
	public Integer getVersionInforme();

	/**
	 * Sets the version informe of this informes.
	 *
	 * @param versionInforme the version informe of this informes
	 */
	public void setVersionInforme(Integer versionInforme);

	/**
	 * Returns the parametros informe of this informes.
	 *
	 * @return the parametros informe of this informes
	 */
	@AutoEscape
	public String getParametrosInforme();

	/**
	 * Sets the parametros informe of this informes.
	 *
	 * @param parametrosInforme the parametros informe of this informes
	 */
	public void setParametrosInforme(String parametrosInforme);

	/**
	 * Returns the beans informe of this informes.
	 *
	 * @return the beans informe of this informes
	 */
	@AutoEscape
	public String getBeansInforme();

	/**
	 * Sets the beans informe of this informes.
	 *
	 * @param beansInforme the beans informe of this informes
	 */
	public void setBeansInforme(String beansInforme);

	/**
	 * Returns the formato of this informes.
	 *
	 * @return the formato of this informes
	 */
	@AutoEscape
	public String getFormato();

	/**
	 * Sets the formato of this informes.
	 *
	 * @param formato the formato of this informes
	 */
	public void setFormato(String formato);

	/**
	 * Returns the create date of this informes.
	 *
	 * @return the create date of this informes
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this informes.
	 *
	 * @param createDate the create date of this informes
	 */
	public void setCreateDate(Date createDate);

}