/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.plan.igualdad.liferay.portlet.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Medida service. Represents a row in the &quot;planigualdad_Medida&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.plan.igualdad.liferay.portlet.manager.model.impl.MedidaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.plan.igualdad.liferay.portlet.manager.model.impl.MedidaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Medida
 * @generated
 */
@ProviderType
public interface MedidaModel extends BaseModel<Medida> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a medida model instance should use the {@link Medida} interface instead.
	 */

	/**
	 * Returns the primary key of this medida.
	 *
	 * @return the primary key of this medida
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this medida.
	 *
	 * @param primaryKey the primary key of this medida
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the medida ID of this medida.
	 *
	 * @return the medida ID of this medida
	 */
	public long getMedidaId();

	/**
	 * Sets the medida ID of this medida.
	 *
	 * @param medidaId the medida ID of this medida
	 */
	public void setMedidaId(long medidaId);

	/**
	 * Returns the comp ID of this medida.
	 *
	 * @return the comp ID of this medida
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this medida.
	 *
	 * @param compId the comp ID of this medida
	 */
	public void setCompId(long compId);

	/**
	 * Returns the version ID of this medida.
	 *
	 * @return the version ID of this medida
	 */
	public long getVersionId();

	/**
	 * Sets the version ID of this medida.
	 *
	 * @param versionId the version ID of this medida
	 */
	public void setVersionId(long versionId);

	/**
	 * Returns the user ID of this medida.
	 *
	 * @return the user ID of this medida
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this medida.
	 *
	 * @param userId the user ID of this medida
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this medida.
	 *
	 * @return the user uuid of this medida
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this medida.
	 *
	 * @param userUuid the user uuid of this medida
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the datos generales of this medida.
	 *
	 * @return the datos generales of this medida
	 */
	@AutoEscape
	public String getDatosGenerales();

	/**
	 * Sets the datos generales of this medida.
	 *
	 * @param datosGenerales the datos generales of this medida
	 */
	public void setDatosGenerales(String datosGenerales);

	/**
	 * Returns the cumplimentacion of this medida.
	 *
	 * @return the cumplimentacion of this medida
	 */
	@AutoEscape
	public String getCumplimentacion();

	/**
	 * Sets the cumplimentacion of this medida.
	 *
	 * @param cumplimentacion the cumplimentacion of this medida
	 */
	public void setCumplimentacion(String cumplimentacion);

	/**
	 * Returns the is medida predefinida of this medida.
	 *
	 * @return the is medida predefinida of this medida
	 */
	public Boolean getIsMedidaPredefinida();

	/**
	 * Sets the is medida predefinida of this medida.
	 *
	 * @param isMedidaPredefinida the is medida predefinida of this medida
	 */
	public void setIsMedidaPredefinida(Boolean isMedidaPredefinida);

	/**
	 * Returns the medida predefinida ID of this medida.
	 *
	 * @return the medida predefinida ID of this medida
	 */
	@AutoEscape
	public String getMedidaPredefinidaId();

	/**
	 * Sets the medida predefinida ID of this medida.
	 *
	 * @param medidaPredefinidaId the medida predefinida ID of this medida
	 */
	public void setMedidaPredefinidaId(String medidaPredefinidaId);

	/**
	 * Returns the version medida of this medida.
	 *
	 * @return the version medida of this medida
	 */
	public Integer getVersionMedida();

	/**
	 * Sets the version medida of this medida.
	 *
	 * @param versionMedida the version medida of this medida
	 */
	public void setVersionMedida(Integer versionMedida);

	/**
	 * Returns the version original medida ID of this medida.
	 *
	 * @return the version original medida ID of this medida
	 */
	public long getVersionOriginalMedidaId();

	/**
	 * Sets the version original medida ID of this medida.
	 *
	 * @param versionOriginalMedidaId the version original medida ID of this medida
	 */
	public void setVersionOriginalMedidaId(long versionOriginalMedidaId);

	/**
	 * Returns the create date of this medida.
	 *
	 * @return the create date of this medida
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this medida.
	 *
	 * @param createDate the create date of this medida
	 */
	public void setCreateDate(Date createDate);

}