/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.plan.igualdad.liferay.portlet.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import com.plan.igualdad.liferay.portlet.manager.service.persistence.OrganizacionPK;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Organizacion service. Represents a row in the &quot;planigualdad_Organizacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.plan.igualdad.liferay.portlet.manager.model.impl.OrganizacionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.plan.igualdad.liferay.portlet.manager.model.impl.OrganizacionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Organizacion
 * @generated
 */
@ProviderType
public interface OrganizacionModel extends BaseModel<Organizacion> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a organizacion model instance should use the {@link Organizacion} interface instead.
	 */

	/**
	 * Returns the primary key of this organizacion.
	 *
	 * @return the primary key of this organizacion
	 */
	public OrganizacionPK getPrimaryKey();

	/**
	 * Sets the primary key of this organizacion.
	 *
	 * @param primaryKey the primary key of this organizacion
	 */
	public void setPrimaryKey(OrganizacionPK primaryKey);

	/**
	 * Returns the organizacion ID of this organizacion.
	 *
	 * @return the organizacion ID of this organizacion
	 */
	public long getOrganizacionId();

	/**
	 * Sets the organizacion ID of this organizacion.
	 *
	 * @param organizacionId the organizacion ID of this organizacion
	 */
	public void setOrganizacionId(long organizacionId);

	/**
	 * Returns the version ID of this organizacion.
	 *
	 * @return the version ID of this organizacion
	 */
	public long getVersionId();

	/**
	 * Sets the version ID of this organizacion.
	 *
	 * @param versionId the version ID of this organizacion
	 */
	public void setVersionId(long versionId);

	/**
	 * Returns the comp ID of this organizacion.
	 *
	 * @return the comp ID of this organizacion
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this organizacion.
	 *
	 * @param compId the comp ID of this organizacion
	 */
	public void setCompId(long compId);

	/**
	 * Returns the anno constitucion of this organizacion.
	 *
	 * @return the anno constitucion of this organizacion
	 */
	@AutoEscape
	public String getAnnoConstitucion();

	/**
	 * Sets the anno constitucion of this organizacion.
	 *
	 * @param annoConstitucion the anno constitucion of this organizacion
	 */
	public void setAnnoConstitucion(String annoConstitucion);

	/**
	 * Returns the pagina web of this organizacion.
	 *
	 * @return the pagina web of this organizacion
	 */
	@AutoEscape
	public String getPaginaWeb();

	/**
	 * Sets the pagina web of this organizacion.
	 *
	 * @param paginaWeb the pagina web of this organizacion
	 */
	public void setPaginaWeb(String paginaWeb);

	/**
	 * Returns the domicilio social of this organizacion.
	 *
	 * @return the domicilio social of this organizacion
	 */
	@AutoEscape
	public String getDomicilioSocial();

	/**
	 * Sets the domicilio social of this organizacion.
	 *
	 * @param domicilioSocial the domicilio social of this organizacion
	 */
	public void setDomicilioSocial(String domicilioSocial);

	/**
	 * Returns the facturacion anual of this organizacion.
	 *
	 * @return the facturacion anual of this organizacion
	 */
	@AutoEscape
	public String getFacturacionAnual();

	/**
	 * Sets the facturacion anual of this organizacion.
	 *
	 * @param facturacionAnual the facturacion anual of this organizacion
	 */
	public void setFacturacionAnual(String facturacionAnual);

	/**
	 * Returns the forma juridica of this organizacion.
	 *
	 * @return the forma juridica of this organizacion
	 */
	@AutoEscape
	public String getFormaJuridica();

	/**
	 * Sets the forma juridica of this organizacion.
	 *
	 * @param formaJuridica the forma juridica of this organizacion
	 */
	public void setFormaJuridica(String formaJuridica);

	/**
	 * Returns the nombre responsable entidad of this organizacion.
	 *
	 * @return the nombre responsable entidad of this organizacion
	 */
	@AutoEscape
	public String getNombreResponsableEntidad();

	/**
	 * Sets the nombre responsable entidad of this organizacion.
	 *
	 * @param nombreResponsableEntidad the nombre responsable entidad of this organizacion
	 */
	public void setNombreResponsableEntidad(String nombreResponsableEntidad);

	/**
	 * Returns the telefono responsable entidad of this organizacion.
	 *
	 * @return the telefono responsable entidad of this organizacion
	 */
	@AutoEscape
	public String getTelefonoResponsableEntidad();

	/**
	 * Sets the telefono responsable entidad of this organizacion.
	 *
	 * @param telefonoResponsableEntidad the telefono responsable entidad of this organizacion
	 */
	public void setTelefonoResponsableEntidad(
		String telefonoResponsableEntidad);

	/**
	 * Returns the cargo responsable entidad of this organizacion.
	 *
	 * @return the cargo responsable entidad of this organizacion
	 */
	@AutoEscape
	public String getCargoResponsableEntidad();

	/**
	 * Sets the cargo responsable entidad of this organizacion.
	 *
	 * @param cargoResponsableEntidad the cargo responsable entidad of this organizacion
	 */
	public void setCargoResponsableEntidad(String cargoResponsableEntidad);

	/**
	 * Returns the email responsable entidad of this organizacion.
	 *
	 * @return the email responsable entidad of this organizacion
	 */
	@AutoEscape
	public String getEmailResponsableEntidad();

	/**
	 * Sets the email responsable entidad of this organizacion.
	 *
	 * @param emailResponsableEntidad the email responsable entidad of this organizacion
	 */
	public void setEmailResponsableEntidad(String emailResponsableEntidad);

	/**
	 * Returns the nombre responsable igualdad of this organizacion.
	 *
	 * @return the nombre responsable igualdad of this organizacion
	 */
	@AutoEscape
	public String getNombreResponsableIgualdad();

	/**
	 * Sets the nombre responsable igualdad of this organizacion.
	 *
	 * @param nombreResponsableIgualdad the nombre responsable igualdad of this organizacion
	 */
	public void setNombreResponsableIgualdad(String nombreResponsableIgualdad);

	/**
	 * Returns the telefono responsable igualdad of this organizacion.
	 *
	 * @return the telefono responsable igualdad of this organizacion
	 */
	@AutoEscape
	public String getTelefonoResponsableIgualdad();

	/**
	 * Sets the telefono responsable igualdad of this organizacion.
	 *
	 * @param telefonoResponsableIgualdad the telefono responsable igualdad of this organizacion
	 */
	public void setTelefonoResponsableIgualdad(
		String telefonoResponsableIgualdad);

	/**
	 * Returns the cargo responsable igualdad of this organizacion.
	 *
	 * @return the cargo responsable igualdad of this organizacion
	 */
	@AutoEscape
	public String getCargoResponsableIgualdad();

	/**
	 * Sets the cargo responsable igualdad of this organizacion.
	 *
	 * @param cargoResponsableIgualdad the cargo responsable igualdad of this organizacion
	 */
	public void setCargoResponsableIgualdad(String cargoResponsableIgualdad);

	/**
	 * Returns the email responsable igualdad of this organizacion.
	 *
	 * @return the email responsable igualdad of this organizacion
	 */
	@AutoEscape
	public String getEmailResponsableIgualdad();

	/**
	 * Sets the email responsable igualdad of this organizacion.
	 *
	 * @param emailResponsableIgualdad the email responsable igualdad of this organizacion
	 */
	public void setEmailResponsableIgualdad(String emailResponsableIgualdad);

	/**
	 * Returns the cnaes of this organizacion.
	 *
	 * @return the cnaes of this organizacion
	 */
	@AutoEscape
	public String getCnaes();

	/**
	 * Sets the cnaes of this organizacion.
	 *
	 * @param cnaes the cnaes of this organizacion
	 */
	public void setCnaes(String cnaes);

	/**
	 * Returns the n centros of this organizacion.
	 *
	 * @return the n centros of this organizacion
	 */
	public long getNCentros();

	/**
	 * Sets the n centros of this organizacion.
	 *
	 * @param nCentros the n centros of this organizacion
	 */
	public void setNCentros(long nCentros);

	/**
	 * Returns the descripcion actividad of this organizacion.
	 *
	 * @return the descripcion actividad of this organizacion
	 */
	@AutoEscape
	public String getDescripcionActividad();

	/**
	 * Sets the descripcion actividad of this organizacion.
	 *
	 * @param descripcionActividad the descripcion actividad of this organizacion
	 */
	public void setDescripcionActividad(String descripcionActividad);

	/**
	 * Returns the convenio of this organizacion.
	 *
	 * @return the convenio of this organizacion
	 */
	@AutoEscape
	public String getConvenio();

	/**
	 * Sets the convenio of this organizacion.
	 *
	 * @param convenio the convenio of this organizacion
	 */
	public void setConvenio(String convenio);

	/**
	 * Returns the ambito of this organizacion.
	 *
	 * @return the ambito of this organizacion
	 */
	@AutoEscape
	public String getAmbito();

	/**
	 * Sets the ambito of this organizacion.
	 *
	 * @param ambito the ambito of this organizacion
	 */
	public void setAmbito(String ambito);

	/**
	 * Returns the comentario ambito of this organizacion.
	 *
	 * @return the comentario ambito of this organizacion
	 */
	@AutoEscape
	public String getComentarioAmbito();

	/**
	 * Sets the comentario ambito of this organizacion.
	 *
	 * @param comentarioAmbito the comentario ambito of this organizacion
	 */
	public void setComentarioAmbito(String comentarioAmbito);

	/**
	 * Returns the n hombres plantilla of this organizacion.
	 *
	 * @return the n hombres plantilla of this organizacion
	 */
	public long getNHombresPlantilla();

	/**
	 * Sets the n hombres plantilla of this organizacion.
	 *
	 * @param nHombresPlantilla the n hombres plantilla of this organizacion
	 */
	public void setNHombresPlantilla(long nHombresPlantilla);

	/**
	 * Returns the n mujeres plantilla of this organizacion.
	 *
	 * @return the n mujeres plantilla of this organizacion
	 */
	public long getNMujeresPlantilla();

	/**
	 * Sets the n mujeres plantilla of this organizacion.
	 *
	 * @param nMujeresPlantilla the n mujeres plantilla of this organizacion
	 */
	public void setNMujeresPlantilla(long nMujeresPlantilla);

	/**
	 * Returns the representacion legal of this organizacion.
	 *
	 * @return the representacion legal of this organizacion
	 */
	@AutoEscape
	public String getRepresentacionLegal();

	/**
	 * Sets the representacion legal of this organizacion.
	 *
	 * @param representacionLegal the representacion legal of this organizacion
	 */
	public void setRepresentacionLegal(String representacionLegal);

	/**
	 * Returns the n representacion legal hombres of this organizacion.
	 *
	 * @return the n representacion legal hombres of this organizacion
	 */
	public long getNRepresentacionLegalHombres();

	/**
	 * Sets the n representacion legal hombres of this organizacion.
	 *
	 * @param nRepresentacionLegalHombres the n representacion legal hombres of this organizacion
	 */
	public void setNRepresentacionLegalHombres(
		long nRepresentacionLegalHombres);

	/**
	 * Returns the n representacion legal mujeres of this organizacion.
	 *
	 * @return the n representacion legal mujeres of this organizacion
	 */
	public long getNRepresentacionLegalMujeres();

	/**
	 * Sets the n representacion legal mujeres of this organizacion.
	 *
	 * @param nRepresentacionLegalMujeres the n representacion legal mujeres of this organizacion
	 */
	public void setNRepresentacionLegalMujeres(
		long nRepresentacionLegalMujeres);

	/**
	 * Returns the representa totalidad of this organizacion.
	 *
	 * @return the representa totalidad of this organizacion
	 */
	@AutoEscape
	public String getRepresentaTotalidad();

	/**
	 * Sets the representa totalidad of this organizacion.
	 *
	 * @param representaTotalidad the representa totalidad of this organizacion
	 */
	public void setRepresentaTotalidad(String representaTotalidad);

	/**
	 * Returns the n no representados of this organizacion.
	 *
	 * @return the n no representados of this organizacion
	 */
	public long getNNoRepresentados();

	/**
	 * Sets the n no representados of this organizacion.
	 *
	 * @param nNoRepresentados the n no representados of this organizacion
	 */
	public void setNNoRepresentados(long nNoRepresentados);

	/**
	 * Returns the comentario representacion of this organizacion.
	 *
	 * @return the comentario representacion of this organizacion
	 */
	@AutoEscape
	public String getComentarioRepresentacion();

	/**
	 * Sets the comentario representacion of this organizacion.
	 *
	 * @param comentarioRepresentacion the comentario representacion of this organizacion
	 */
	public void setComentarioRepresentacion(String comentarioRepresentacion);

	/**
	 * Returns the departamento personal of this organizacion.
	 *
	 * @return the departamento personal of this organizacion
	 */
	@AutoEscape
	public String getDepartamentoPersonal();

	/**
	 * Sets the departamento personal of this organizacion.
	 *
	 * @param departamentoPersonal the departamento personal of this organizacion
	 */
	public void setDepartamentoPersonal(String departamentoPersonal);

	/**
	 * Returns the sindicatos of this organizacion.
	 *
	 * @return the sindicatos of this organizacion
	 */
	@AutoEscape
	public String getSindicatos();

	/**
	 * Sets the sindicatos of this organizacion.
	 *
	 * @param sindicatos the sindicatos of this organizacion
	 */
	public void setSindicatos(String sindicatos);

	/**
	 * Returns the repr comision organizacion of this organizacion.
	 *
	 * @return the repr comision organizacion of this organizacion
	 */
	@AutoEscape
	public String getReprComisionOrganizacion();

	/**
	 * Sets the repr comision organizacion of this organizacion.
	 *
	 * @param reprComisionOrganizacion the repr comision organizacion of this organizacion
	 */
	public void setReprComisionOrganizacion(String reprComisionOrganizacion);

	/**
	 * Returns the repr comision social of this organizacion.
	 *
	 * @return the repr comision social of this organizacion
	 */
	@AutoEscape
	public String getReprComisionSocial();

	/**
	 * Sets the repr comision social of this organizacion.
	 *
	 * @param reprComisionSocial the repr comision social of this organizacion
	 */
	public void setReprComisionSocial(String reprComisionSocial);

	/**
	 * Returns the repr plan organizacion of this organizacion.
	 *
	 * @return the repr plan organizacion of this organizacion
	 */
	@AutoEscape
	public String getReprPlanOrganizacion();

	/**
	 * Sets the repr plan organizacion of this organizacion.
	 *
	 * @param reprPlanOrganizacion the repr plan organizacion of this organizacion
	 */
	public void setReprPlanOrganizacion(String reprPlanOrganizacion);

	/**
	 * Returns the repr plan sociales of this organizacion.
	 *
	 * @return the repr plan sociales of this organizacion
	 */
	@AutoEscape
	public String getReprPlanSociales();

	/**
	 * Sets the repr plan sociales of this organizacion.
	 *
	 * @param reprPlanSociales the repr plan sociales of this organizacion
	 */
	public void setReprPlanSociales(String reprPlanSociales);

}