/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.plan.igualdad.liferay.portlet.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import com.plan.igualdad.liferay.portlet.manager.service.persistence.ParametricasFDDPK;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ParametricasFDD service. Represents a row in the &quot;planigualdad_ParametricasFDD&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.plan.igualdad.liferay.portlet.manager.model.impl.ParametricasFDDModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.plan.igualdad.liferay.portlet.manager.model.impl.ParametricasFDDImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ParametricasFDD
 * @generated
 */
@ProviderType
public interface ParametricasFDDModel extends BaseModel<ParametricasFDD> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a parametricas fdd model instance should use the {@link ParametricasFDD} interface instead.
	 */

	/**
	 * Returns the primary key of this parametricas fdd.
	 *
	 * @return the primary key of this parametricas fdd
	 */
	public ParametricasFDDPK getPrimaryKey();

	/**
	 * Sets the primary key of this parametricas fdd.
	 *
	 * @param primaryKey the primary key of this parametricas fdd
	 */
	public void setPrimaryKey(ParametricasFDDPK primaryKey);

	/**
	 * Returns the comp ID of this parametricas fdd.
	 *
	 * @return the comp ID of this parametricas fdd
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this parametricas fdd.
	 *
	 * @param compId the comp ID of this parametricas fdd
	 */
	public void setCompId(long compId);

	/**
	 * Returns the version ID of this parametricas fdd.
	 *
	 * @return the version ID of this parametricas fdd
	 */
	public long getVersionId();

	/**
	 * Sets the version ID of this parametricas fdd.
	 *
	 * @param versionId the version ID of this parametricas fdd
	 */
	public void setVersionId(long versionId);

	/**
	 * Returns the id parametrica of this parametricas fdd.
	 *
	 * @return the id parametrica of this parametricas fdd
	 */
	@AutoEscape
	public String getIdParametrica();

	/**
	 * Sets the id parametrica of this parametricas fdd.
	 *
	 * @param idParametrica the id parametrica of this parametricas fdd
	 */
	public void setIdParametrica(String idParametrica);

	/**
	 * Returns the tipo of this parametricas fdd.
	 *
	 * @return the tipo of this parametricas fdd
	 */
	@AutoEscape
	public String getTipo();

	/**
	 * Sets the tipo of this parametricas fdd.
	 *
	 * @param tipo the tipo of this parametricas fdd
	 */
	public void setTipo(String tipo);

	/**
	 * Returns the materia of this parametricas fdd.
	 *
	 * @return the materia of this parametricas fdd
	 */
	public Integer getMateria();

	/**
	 * Sets the materia of this parametricas fdd.
	 *
	 * @param materia the materia of this parametricas fdd
	 */
	public void setMateria(Integer materia);

	/**
	 * Returns the contenido of this parametricas fdd.
	 *
	 * @return the contenido of this parametricas fdd
	 */
	@AutoEscape
	public String getContenido();

	/**
	 * Sets the contenido of this parametricas fdd.
	 *
	 * @param contenido the contenido of this parametricas fdd
	 */
	public void setContenido(String contenido);

	/**
	 * Returns the seccion ID of this parametricas fdd.
	 *
	 * @return the seccion ID of this parametricas fdd
	 */
	public long getSeccionId();

	/**
	 * Sets the seccion ID of this parametricas fdd.
	 *
	 * @param seccionId the seccion ID of this parametricas fdd
	 */
	public void setSeccionId(long seccionId);

}