/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.plan.igualdad.liferay.portlet.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import com.plan.igualdad.liferay.portlet.manager.service.persistence.PreguntaPK;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Pregunta service. Represents a row in the &quot;planigualdad_Pregunta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.plan.igualdad.liferay.portlet.manager.model.impl.PreguntaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.plan.igualdad.liferay.portlet.manager.model.impl.PreguntaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Pregunta
 * @generated
 */
@ProviderType
public interface PreguntaModel extends BaseModel<Pregunta> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pregunta model instance should use the {@link Pregunta} interface instead.
	 */

	/**
	 * Returns the primary key of this pregunta.
	 *
	 * @return the primary key of this pregunta
	 */
	public PreguntaPK getPrimaryKey();

	/**
	 * Sets the primary key of this pregunta.
	 *
	 * @param primaryKey the primary key of this pregunta
	 */
	public void setPrimaryKey(PreguntaPK primaryKey);

	/**
	 * Returns the pregunta ID of this pregunta.
	 *
	 * @return the pregunta ID of this pregunta
	 */
	public long getPreguntaId();

	/**
	 * Sets the pregunta ID of this pregunta.
	 *
	 * @param preguntaId the pregunta ID of this pregunta
	 */
	public void setPreguntaId(long preguntaId);

	/**
	 * Returns the seccion ID of this pregunta.
	 *
	 * @return the seccion ID of this pregunta
	 */
	public long getSeccionId();

	/**
	 * Sets the seccion ID of this pregunta.
	 *
	 * @param seccionId the seccion ID of this pregunta
	 */
	public void setSeccionId(long seccionId);

	/**
	 * Returns the tipo of this pregunta.
	 *
	 * @return the tipo of this pregunta
	 */
	@AutoEscape
	public String getTipo();

	/**
	 * Sets the tipo of this pregunta.
	 *
	 * @param tipo the tipo of this pregunta
	 */
	public void setTipo(String tipo);

	/**
	 * Returns the pregunta of this pregunta.
	 *
	 * @return the pregunta of this pregunta
	 */
	@AutoEscape
	public String getPregunta();

	/**
	 * Sets the pregunta of this pregunta.
	 *
	 * @param pregunta the pregunta of this pregunta
	 */
	public void setPregunta(String pregunta);

}