/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.plan.igualdad.liferay.portlet.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import com.plan.igualdad.liferay.portlet.manager.service.persistence.PuestoTrabajoPK;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PuestoTrabajo service. Represents a row in the &quot;planigualdad_PuestoTrabajo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.plan.igualdad.liferay.portlet.manager.model.impl.PuestoTrabajoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.plan.igualdad.liferay.portlet.manager.model.impl.PuestoTrabajoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PuestoTrabajo
 * @generated
 */
@ProviderType
public interface PuestoTrabajoModel extends BaseModel<PuestoTrabajo> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a puesto trabajo model instance should use the {@link PuestoTrabajo} interface instead.
	 */

	/**
	 * Returns the primary key of this puesto trabajo.
	 *
	 * @return the primary key of this puesto trabajo
	 */
	public PuestoTrabajoPK getPrimaryKey();

	/**
	 * Sets the primary key of this puesto trabajo.
	 *
	 * @param primaryKey the primary key of this puesto trabajo
	 */
	public void setPrimaryKey(PuestoTrabajoPK primaryKey);

	/**
	 * Returns the puesto ID of this puesto trabajo.
	 *
	 * @return the puesto ID of this puesto trabajo
	 */
	public long getPuestoId();

	/**
	 * Sets the puesto ID of this puesto trabajo.
	 *
	 * @param puestoId the puesto ID of this puesto trabajo
	 */
	public void setPuestoId(long puestoId);

	/**
	 * Returns the version ID of this puesto trabajo.
	 *
	 * @return the version ID of this puesto trabajo
	 */
	public long getVersionId();

	/**
	 * Sets the version ID of this puesto trabajo.
	 *
	 * @param versionId the version ID of this puesto trabajo
	 */
	public void setVersionId(long versionId);

	/**
	 * Returns the comp ID of this puesto trabajo.
	 *
	 * @return the comp ID of this puesto trabajo
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this puesto trabajo.
	 *
	 * @param compId the comp ID of this puesto trabajo
	 */
	public void setCompId(long compId);

	/**
	 * Returns the nombre of this puesto trabajo.
	 *
	 * @return the nombre of this puesto trabajo
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this puesto trabajo.
	 *
	 * @param nombre the nombre of this puesto trabajo
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the area ID of this puesto trabajo.
	 *
	 * @return the area ID of this puesto trabajo
	 */
	public long getAreaId();

	/**
	 * Sets the area ID of this puesto trabajo.
	 *
	 * @param areaId the area ID of this puesto trabajo
	 */
	public void setAreaId(long areaId);

	/**
	 * Returns the responsabilidad of this puesto trabajo.
	 *
	 * @return the responsabilidad of this puesto trabajo
	 */
	public long getResponsabilidad();

	/**
	 * Sets the responsabilidad of this puesto trabajo.
	 *
	 * @param responsabilidad the responsabilidad of this puesto trabajo
	 */
	public void setResponsabilidad(long responsabilidad);

	/**
	 * Returns the n hombres of this puesto trabajo.
	 *
	 * @return the n hombres of this puesto trabajo
	 */
	public long getNHombres();

	/**
	 * Sets the n hombres of this puesto trabajo.
	 *
	 * @param nHombres the n hombres of this puesto trabajo
	 */
	public void setNHombres(long nHombres);

	/**
	 * Returns the n mujeres of this puesto trabajo.
	 *
	 * @return the n mujeres of this puesto trabajo
	 */
	public long getNMujeres();

	/**
	 * Sets the n mujeres of this puesto trabajo.
	 *
	 * @param nMujeres the n mujeres of this puesto trabajo
	 */
	public void setNMujeres(long nMujeres);

	/**
	 * Returns the baja of this puesto trabajo.
	 *
	 * @return the baja of this puesto trabajo
	 */
	public Date getBaja();

	/**
	 * Sets the baja of this puesto trabajo.
	 *
	 * @param baja the baja of this puesto trabajo
	 */
	public void setBaja(Date baja);

}