/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.plan.igualdad.liferay.portlet.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import com.plan.igualdad.liferay.portlet.manager.service.persistence.RespuestaPK;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Respuesta service. Represents a row in the &quot;planigualdad_Respuesta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.plan.igualdad.liferay.portlet.manager.model.impl.RespuestaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.plan.igualdad.liferay.portlet.manager.model.impl.RespuestaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Respuesta
 * @generated
 */
@ProviderType
public interface RespuestaModel extends BaseModel<Respuesta> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a respuesta model instance should use the {@link Respuesta} interface instead.
	 */

	/**
	 * Returns the primary key of this respuesta.
	 *
	 * @return the primary key of this respuesta
	 */
	public RespuestaPK getPrimaryKey();

	/**
	 * Sets the primary key of this respuesta.
	 *
	 * @param primaryKey the primary key of this respuesta
	 */
	public void setPrimaryKey(RespuestaPK primaryKey);

	/**
	 * Returns the comp ID of this respuesta.
	 *
	 * @return the comp ID of this respuesta
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this respuesta.
	 *
	 * @param compId the comp ID of this respuesta
	 */
	public void setCompId(long compId);

	/**
	 * Returns the version ID of this respuesta.
	 *
	 * @return the version ID of this respuesta
	 */
	public long getVersionId();

	/**
	 * Sets the version ID of this respuesta.
	 *
	 * @param versionId the version ID of this respuesta
	 */
	public void setVersionId(long versionId);

	/**
	 * Returns the seccion ID of this respuesta.
	 *
	 * @return the seccion ID of this respuesta
	 */
	public long getSeccionId();

	/**
	 * Sets the seccion ID of this respuesta.
	 *
	 * @param seccionId the seccion ID of this respuesta
	 */
	public void setSeccionId(long seccionId);

	/**
	 * Returns the respuestas of this respuesta.
	 *
	 * @return the respuestas of this respuesta
	 */
	@AutoEscape
	public String getRespuestas();

	/**
	 * Sets the respuestas of this respuesta.
	 *
	 * @param respuestas the respuestas of this respuesta
	 */
	public void setRespuestas(String respuestas);

	/**
	 * Returns the estado of this respuesta.
	 *
	 * @return the estado of this respuesta
	 */
	public long getEstado();

	/**
	 * Sets the estado of this respuesta.
	 *
	 * @param estado the estado of this respuesta
	 */
	public void setEstado(long estado);

}