/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.plan.igualdad.liferay.portlet.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Valoracion service. Represents a row in the &quot;planigualdad_Valoracion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.plan.igualdad.liferay.portlet.manager.model.impl.ValoracionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.plan.igualdad.liferay.portlet.manager.model.impl.ValoracionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Valoracion
 * @generated
 */
@ProviderType
public interface ValoracionModel extends BaseModel<Valoracion> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a valoracion model instance should use the {@link Valoracion} interface instead.
	 */

	/**
	 * Returns the primary key of this valoracion.
	 *
	 * @return the primary key of this valoracion
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this valoracion.
	 *
	 * @param primaryKey the primary key of this valoracion
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the valoracion ID of this valoracion.
	 *
	 * @return the valoracion ID of this valoracion
	 */
	public long getValoracionId();

	/**
	 * Sets the valoracion ID of this valoracion.
	 *
	 * @param valoracionId the valoracion ID of this valoracion
	 */
	public void setValoracionId(long valoracionId);

	/**
	 * Returns the comp ID of this valoracion.
	 *
	 * @return the comp ID of this valoracion
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this valoracion.
	 *
	 * @param compId the comp ID of this valoracion
	 */
	public void setCompId(long compId);

	/**
	 * Returns the version ID of this valoracion.
	 *
	 * @return the version ID of this valoracion
	 */
	public long getVersionId();

	/**
	 * Sets the version ID of this valoracion.
	 *
	 * @param versionId the version ID of this valoracion
	 */
	public void setVersionId(long versionId);

	/**
	 * Returns the user ID of this valoracion.
	 *
	 * @return the user ID of this valoracion
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this valoracion.
	 *
	 * @param userId the user ID of this valoracion
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this valoracion.
	 *
	 * @return the user uuid of this valoracion
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this valoracion.
	 *
	 * @param userUuid the user uuid of this valoracion
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the respuestas valoracion of this valoracion.
	 *
	 * @return the respuestas valoracion of this valoracion
	 */
	@AutoEscape
	public String getRespuestasValoracion();

	/**
	 * Sets the respuestas valoracion of this valoracion.
	 *
	 * @param respuestasValoracion the respuestas valoracion of this valoracion
	 */
	public void setRespuestasValoracion(String respuestasValoracion);

	/**
	 * Returns the observaciones of this valoracion.
	 *
	 * @return the observaciones of this valoracion
	 */
	@AutoEscape
	public String getObservaciones();

	/**
	 * Sets the observaciones of this valoracion.
	 *
	 * @param observaciones the observaciones of this valoracion
	 */
	public void setObservaciones(String observaciones);

	/**
	 * Returns the version valoracion of this valoracion.
	 *
	 * @return the version valoracion of this valoracion
	 */
	public Integer getVersionValoracion();

	/**
	 * Sets the version valoracion of this valoracion.
	 *
	 * @param versionValoracion the version valoracion of this valoracion
	 */
	public void setVersionValoracion(Integer versionValoracion);

	/**
	 * Returns the create date of this valoracion.
	 *
	 * @return the create date of this valoracion
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this valoracion.
	 *
	 * @param createDate the create date of this valoracion
	 */
	public void setCreateDate(Date createDate);

}