/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.plan.igualdad.liferay.portlet.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import com.plan.igualdad.liferay.portlet.manager.service.persistence.VersionPK;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Version service. Represents a row in the &quot;planigualdad_Version&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.plan.igualdad.liferay.portlet.manager.model.impl.VersionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.plan.igualdad.liferay.portlet.manager.model.impl.VersionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Version
 * @generated
 */
@ProviderType
public interface VersionModel extends BaseModel<Version> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a version model instance should use the {@link Version} interface instead.
	 */

	/**
	 * Returns the primary key of this version.
	 *
	 * @return the primary key of this version
	 */
	public VersionPK getPrimaryKey();

	/**
	 * Sets the primary key of this version.
	 *
	 * @param primaryKey the primary key of this version
	 */
	public void setPrimaryKey(VersionPK primaryKey);

	/**
	 * Returns the version ID of this version.
	 *
	 * @return the version ID of this version
	 */
	public long getVersionId();

	/**
	 * Sets the version ID of this version.
	 *
	 * @param versionId the version ID of this version
	 */
	public void setVersionId(long versionId);

	/**
	 * Returns the comp ID of this version.
	 *
	 * @return the comp ID of this version
	 */
	public long getCompId();

	/**
	 * Sets the comp ID of this version.
	 *
	 * @param compId the comp ID of this version
	 */
	public void setCompId(long compId);

	/**
	 * Returns the nombre of this version.
	 *
	 * @return the nombre of this version
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this version.
	 *
	 * @param nombre the nombre of this version
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the inicio periodo datos of this version.
	 *
	 * @return the inicio periodo datos of this version
	 */
	public Date getInicioPeriodoDatos();

	/**
	 * Sets the inicio periodo datos of this version.
	 *
	 * @param inicioPeriodoDatos the inicio periodo datos of this version
	 */
	public void setInicioPeriodoDatos(Date inicioPeriodoDatos);

	/**
	 * Returns the fin periodo datos of this version.
	 *
	 * @return the fin periodo datos of this version
	 */
	public Date getFinPeriodoDatos();

	/**
	 * Sets the fin periodo datos of this version.
	 *
	 * @param finPeriodoDatos the fin periodo datos of this version
	 */
	public void setFinPeriodoDatos(Date finPeriodoDatos);

	/**
	 * Returns the inicio periodo plan of this version.
	 *
	 * @return the inicio periodo plan of this version
	 */
	public Date getInicioPeriodoPlan();

	/**
	 * Sets the inicio periodo plan of this version.
	 *
	 * @param inicioPeriodoPlan the inicio periodo plan of this version
	 */
	public void setInicioPeriodoPlan(Date inicioPeriodoPlan);

	/**
	 * Returns the fin periodo plan of this version.
	 *
	 * @return the fin periodo plan of this version
	 */
	public Date getFinPeriodoPlan();

	/**
	 * Sets the fin periodo plan of this version.
	 *
	 * @param finPeriodoPlan the fin periodo plan of this version
	 */
	public void setFinPeriodoPlan(Date finPeriodoPlan);

	/**
	 * Returns the baja of this version.
	 *
	 * @return the baja of this version
	 */
	public Date getBaja();

	/**
	 * Sets the baja of this version.
	 *
	 * @param baja the baja of this version
	 */
	public void setBaja(Date baja);

	/**
	 * Returns the create date of this version.
	 *
	 * @return the create date of this version
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this version.
	 *
	 * @param createDate the create date of this version
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this version.
	 *
	 * @return the modified date of this version
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this version.
	 *
	 * @param modifiedDate the modified date of this version
	 */
	public void setModifiedDate(Date modifiedDate);

}