INSERT INTO `lfr-73-preving`.`legalplus_CCAA` (`ccaaId`, `nombre`) VALUES ('1', 'GALICIA');
INSERT INTO `lfr-73-preving`.`legalplus_CCAA` (`ccaaId`, `nombre`) VALUES ('2', 'ASTURIAS');
INSERT INTO `lfr-73-preving`.`legalplus_CCAA` (`ccaaId`, `nombre`) VALUES ('3', 'CANTABRIA');
INSERT INTO `lfr-73-preving`.`legalplus_CCAA` (`ccaaId`, `nombre`) VALUES ('4', 'PAIS VASCO');
INSERT INTO `lfr-73-preving`.`legalplus_CCAA` (`ccaaId`, `nombre`) VALUES ('5', 'NAVARRA');
INSERT INTO `lfr-73-preving`.`legalplus_CCAA` (`ccaaId`, `nombre`) VALUES ('6', 'CATALUÑA');
INSERT INTO `lfr-73-preving`.`legalplus_CCAA` (`ccaaId`, `nombre`) VALUES ('7', 'ARAGON');
INSERT INTO `lfr-73-preving`.`legalplus_CCAA` (`ccaaId`, `nombre`) VALUES ('8', 'LA RIOJA');
INSERT INTO `lfr-73-preving`.`legalplus_CCAA` (`ccaaId`, `nombre`) VALUES ('9', 'CASTILLA Y LEON');
INSERT INTO `lfr-73-preving`.`legalplus_CCAA` (`ccaaId`, `nombre`) VALUES ('10', 'MADRID');
INSERT INTO `lfr-73-preving`.`legalplus_CCAA` (`ccaaId`, `nombre`) VALUES ('11', 'EXTREMADURA');
INSERT INTO `lfr-73-preving`.`legalplus_CCAA` (`ccaaId`, `nombre`) VALUES ('12', 'CASTILLA LA MANCHA');
INSERT INTO `lfr-73-preving`.`legalplus_CCAA` (`ccaaId`, `nombre`) VALUES ('13', 'COMUNIDAD VALENCIANA');
INSERT INTO `lfr-73-preving`.`legalplus_CCAA` (`ccaaId`, `nombre`) VALUES ('14', 'ANDALUCIA');
INSERT INTO `lfr-73-preving`.`legalplus_CCAA` (`ccaaId`, `nombre`) VALUES ('15', 'MURCIA');
INSERT INTO `lfr-73-preving`.`legalplus_CCAA` (`ccaaId`, `nombre`) VALUES ('16', 'ISLAS BALEARES');
INSERT INTO `lfr-73-preving`.`legalplus_CCAA` (`ccaaId`, `nombre`) VALUES ('17', 'CEUTA');
INSERT INTO `lfr-73-preving`.`legalplus_CCAA` (`ccaaId`, `nombre`) VALUES ('18', 'MELILLA');
INSERT INTO `lfr-73-preving`.`legalplus_CCAA` (`ccaaId`, `nombre`) VALUES ('19', 'CANARIAS');
