INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('1', 'ARABA/ALAVA', '4', '20515');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('2', 'ALBACETE', '12', '7799');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('3', 'ALICANTE', '13', '7752');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('4', 'ALMERIA', '14', '7772');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('5', 'AVILA', '9', '7753');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('6', 'BADAJOZ', '11', '13');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('7', 'ILLES BALEARS', '16', '39889');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('8', 'BARCELONA', '6', '8103');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('9', 'BURGOS', '9', '7754');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('10', 'CACERES', '11', '41');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('11', 'CADIZ', '14', '3531');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('12', 'CASTELLON', '13', '9037');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('13', 'CIUDAD REAL', '12', '8553');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('14', 'CORDOBA', '14', '663');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('15', 'CORUÑA, A', '1', '4310');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('16', 'CUENCA', '12', '7778');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('17', 'GIRONA', '6', '36897');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('18', 'GRANADA', '14', '4832');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('19', 'GUADALAJARA', '12', '1850');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('20', 'GIPUZKOA', '4', '9675');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('21', 'HUELVA', '14', '822');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('22', 'HUESCA', '7', '39174');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('23', 'JAEN', '14', '8632');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('24', 'LEON', '9', '4311');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('25', 'LLEIDA', '6', '42288');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('26', 'RIOJA, LA', '8', '9212');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('27', 'LUGO', '1', '4290');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('28', 'MADRID', '10', '21');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('29', 'MALAGA', '14', '362');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('30', 'MURCIA', '15', '3491');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('31', 'NAVARRA', '5', '8978');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('32', 'OURENSE', '1', '8877');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('33', 'ASTURIAS', '2', '8893');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('34', 'PALENCIA', '9', '8823');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('35', 'PALMAS, LAS', '19', '1770');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('36', 'PONTEVEDRA', '1', '53978');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('37', 'SALAMANCA', '9', '8821');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('38', 'SANTA C. TENERIFE', '19', '1450');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('39', 'CANTABRIA', '3', '33047');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('40', 'SEGOVIA', '9', '8819');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('41', 'SEVILLA', '14', '347');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('42', 'SORIA', '9', '57108');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('43', 'TARRAGONA', '6', '57572');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('44', 'TERUEL', '7', '57876');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('45', 'TOLEDO', '12', '2810');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('46', 'VALENCIA', '13', '58636');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('47', 'VALLADOLID', '9', '8913');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('48', 'BIZKAIA', '4', '6950');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('49', 'ZAMORA', '9', '60173');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('50', 'ZARAGOZA', '7', '60561');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('51', 'CEUTA', '17', '33492');
INSERT INTO `lfr-73-preving`.`legalplus_Provincia` (`provinciaId`, `nombre`, `ccaaId`, `capitalId`) VALUES ('52', 'MELILLA', '18', '45849');
